### ISSUE TITLE
Enhancement: [Internal Link] Provide user with a message upon tapping 'Link' button

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-ios#1001]
### What
Text bubble notifying a user that note internal link was copied to the clipboard.

### Why
Will improve app feedback to the user. For new-coming user (like me) it was not immediately clear what button does. 

### How
Something similar to depicted below
![photo_2020-11-09 18 24 20](https://user-images.githubusercontent.com/73365754/98567637-d357b700-22b8-11eb-88e0-341be86a9648.jpeg)

**Comment by jleandroperez** [comment]
Thank you @pachlava, this will be addressed via #938

**Comment by charliescheer** [comment]
Closing, this was fixed in #1228
