### ISSUE TITLE
Share Analytics setting does not sync between devices

### ISSUE THREAD

**Issue by designsimply** [Automattic/simplenote-ios#1010]
### Expected
I expected the Share Analytics setting to sync between devices.

### Observed
The Share Analytics setting did not sync between devices.

### Reproduced
1. On an iPhone, go to Settings > Privacy Settings. 
1. Tap on "Share Analytics".
1. On an iPad, go to Settings > Privacy Settings. 
1. Tap on "Share Analytics".
1. Observe that the "Share Analytics" option is now toggled off in the iPhone view and on in the iPad view.

<img src="https://user-images.githubusercontent.com/1119271/98862062-82b09d00-2423-11eb-9f4b-5fcdc4232727.PNG" height="350" alt="IMG_4680"> <img src="https://user-images.githubusercontent.com/1119271/98862060-82180680-2423-11eb-9e09-4a5a12a371fc.PNG" height="350" alt="IMG_0567">

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPhone 11|iOS 14.1|Simplenote iOS 4.27.0.0 (MS App Center beta)
Apple|iPad Mini 4 (WiFi) (iPad5,1)|iOS 13.7|Simplenote iOS 4.27.0.0 (MS App Center beta)

**Comment by jleandroperez** [comment]
Thank you @designsimply !! I'm afraid we need the Analytics flag not to be sync'ed over. A bit of background:

1. Analytics are off by default, always
2. But we (used) to persist the Analytics flag state across devices
3. Logging into an account that **had** Analytics enabled caused Analytics to be on, right after installing the app

As per Apple's guidelines, Analytics must be off by default (and the users must opt in). 

This was the cause of a couple AppStore rejections: our reviewer would sign into an account that previously had this flag on, and would reject our binary (happened 2-3 times at least).

Ref. [macOS Issue here!](https://github.com/Automattic/simplenote-macos/pull/507)

😭
