### ISSUE TITLE
Screen Reading Voice Over Improvements.

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-ios#1018]
On IOS with Voiceover:

When in the list of all notes and swiping down for actions, the current
labels are ïcon trash", "icon pin", "icon link" and "icon share". That's
understandable, of course, but "delete", "pin', "copy link" and "share"
would be better.

Thank you. Also I just downloaded the IOS Beta and if there's something
in particular you would like me to test with Voiceover, I'm happy to.

Reported in 3487018-zen

I'm asking the user for more specific device information.

**Comment by azollafox** [comment]
Iphone 6s+, beta 14.3, Simplenote 4.27
