### ISSUE TITLE
Tag auto suggest not visible when full screen

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/simplenote-ios#102]
If you open up the iOS app full screen and try to add a tag the drop down which would normally appear to allow you to select an existing tag does not show up.

Would it be possible to detect full screen and have the suggest box appear above the tag input field?

**Comment by bummytime** [comment]
**Update 5/14/2019 →** no longer an issue in Simplenote 4.7.0 (the UI has changed). Closing.
