### ISSUE TITLE
Add scroll to bottom button for traversing long notes

### ISSUE THREAD

**Issue by dartiss** [Automattic/simplenote-ios#103]
A user has requested an enhancement to allow quick scrolling to the bottom of long notes...

> My note often accumulate quite long. Every time i want to add some more text to this note, i have to scroll for some time until reaching the bottom. It's quite annoying for me and other user who also keep a long note.
> 
> I suggest to add a little button, one pressed, it scroll to the end instantly.
> 
> To still keep it simple. I suggest this button only show up in long note we opened and it disappear if untouch in first command to keep the simplicity we love.
> 
> It's especially useful in mobile app.

As the user says, I think this is more a mobile app improvement but it's certainly worth considering with all platforms (I'm cross-posting this for all platforms).

Ticket is #2909376-t.

**Comment by jleandroperez** [comment]
Closed in favor of #733.

As per iOS 13, the standard mechanism involves "grabbing" the scrollbar, and traversing the document (in realtime).

Thank you all!!
