### ISSUE TITLE
"Empty" trash button remains enabled when notes are restored\deleted individually

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-ios#1037]
### Expected
"Empty" button in Trash should be disabled when there are no notes

### Observed
With scenario below, "Empty" button remains enabled even if there are no notes

### Reproduced
> 1. Make sure there's at least 1 note in Trash
> 2. In Trash, restore\delete all present notes individually by swiping
> 3. "Empty" button is still enabled

![Simulator Screen Shot - iPhone 11 - 2020-11-19 at 16 48 13](https://user-images.githubusercontent.com/73365754/99681670-13702400-2a87-11eb-97d9-16ae82ced388.png)

Make|Model|iOS Version|App Version
-|-|-|-
iPhone Sim. | 11 | 14.1 | 4.28

**Comment by jleandroperez** [comment]
Closed via #1093 by @charliescheer 

Thanks everyone!!
