### ISSUE TITLE
Introduce Folders and/or Tree Structure

### ISSUE THREAD

**Issue by dartiss** [Automattic/simplenote-ios#104]
A user would like to request the introduction of a more advanced note structure - a tree and/or folders.

> Your app Simplenote is really great! I use it everyday.
> 
> However, I usually transfer the notes Simplenote in a document on Google Drive because GD has a tree of files and folders. Although the tags are very convenient but if you had a tree of files and folders I would use only your solution.

As this applies to all the platforms, I'm cross posting this on all the issue logs.

Ticket is #2909181-t.

**Comment by jleandroperez** [comment]
Closing this one since this will likely not going to happen, given the product vision / design.

Thanks @dartiss!!
