### ISSUE TITLE
Nü Tags Edition Mode

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#1042]
### Details:
- [ ] Drop standard UITableView row deletion mechanism
- [ ] Implement a Right Accessory **Trash** Icon
- [ ] Implement Tag Deletion Conformation

Gentlemen, adding one of the new Spring Cleaning tasks!
cc @eshurakov @SylvesterWilmott 

<img width="300" src="https://user-images.githubusercontent.com/1195260/99992266-db255a00-2d94-11eb-8815-2bde20bb0684.png"> <img width="300" src="https://user-images.githubusercontent.com/1195260/99992273-dd87b400-2d94-11eb-85c4-19865f80023f.png"> <img width="300" src="https://user-images.githubusercontent.com/1195260/99992274-de204a80-2d94-11eb-91e7-3dab2d072746.png">

**Comment by pachlava** [comment]
[testing] Implementation verified on iPhone XR | iOS 14.3 | SN 4.31
All issues found during testing will be posted separately.
