### ISSUE TITLE
Force Touch on app icon to create a new note

### ISSUE THREAD

**Issue by charliescheer** [Automattic/simplenote-ios#1056]
### What

It would be great if it was possible to long press or force press on the Simplenote app icon and get a shortcut to open simplenote directly into creating a new note, similar to the Apple notes app icon:

<img height="500px" src="https://cdn-std.droplr.net/files/acc_593859/dbz4mT" />

### Why
Being able to jump into the app directly to where a user wants to be can make Simplenote easier to use with out adding complexity to the app.  Making it a faster easier user experience

**Comment by theck13** [comment]
I believe this has already been merged and will be included in the Simplenote iOS v4.29.0 release.  The [`RELEASE-NOTES.txt` file has the `Home screen quick actions #950` item](https://github.com/Automattic/simplenote-ios/blob/c2a4c276f7885eebc78e6b5bdb2f9b77503e4988/RELEASE-NOTES.txt#L7) listed referring to https://github.com/Automattic/simplenote-ios/issues/950, which was closed by https://github.com/Automattic/simplenote-ios/pull/1032.  See the screenshot below for illustration.

<a href="https://user-images.githubusercontent.com/3827611/101578354-0e700780-3997-11eb-82d0-cb93e73b2619.png"><img src="https://user-images.githubusercontent.com/3827611/101578354-0e700780-3997-11eb-82d0-cb93e73b2619.png" width="300"></a>

I'll leave this open for @jleandroperez or @eshurakov to confirm.

**Comment by charliescheer** [comment]
Aw nice.  Thanks!

**Comment by eshurakov** [comment]
Thank you @charliescheer and @theck13! 
It is correct, this feature will be available in 4.29 (currently available version in the App Store is 4.28).

Closing this :-)

**Comment by jleandroperez** [comment]
Thank you Charlie!!
