### ISSUE TITLE
Unable to input text in Split View on iPad

### ISSUE THREAD

**Issue by rwaynick** [Automattic/simplenote-ios#106]
#### Steps to reproduce
1. Open Simplenote on iPad
2. Turn on Passcode and Enable Touch ID
3. Open another App in Split View
4. Select an existing note and try to type in the note
5. Notice that the keyboard doesn't appear and it's not possible to input text
6. Even if Split View is closed, input is still not possible

#### Browser / OS version

My test device info:
iPad mini 4 wifi
iOS 10.1.1
Simplenote version 4.4.1

User's device info:
iPad Air 2 (wifi)
iOS 10.0.1
Simplenote v. 4.4.1

#### Screenshot

![img_0065](https://cloud.githubusercontent.com/assets/10882502/20684881/21ccd096-b599-11e6-9c16-da803a015060.jpg)

#### Context / Source
#user-report in #2931430-t

**Comment by jleandroperez** [comment]
Potentially related:

```
It is when my finger slips when typing at speed and the menu that controls wi-fi, Bluetooth etc pops from from the bottom of the screen. Once that is activated I have lost the keyboard and cannot type and cannot put in code for password I use for the app. I have deliberately activated the lower menu and it froze three times in a row.
```

**Comment by bummytime** [comment]
Just tested this in on an iPad running 12.2 — could not repro. Closing.
