### ISSUE TITLE
Update Designs for Information Sheet

### ISSUE THREAD

**Issue by SylvesterWilmott** [Automattic/simplenote-ios#1061]
This is an issue to request updated designs for iOS information sheet. See below for illustration.

<img width="377" alt="Screenshot 2020-12-18 at 09 54 37" src="https://user-images.githubusercontent.com/36532468/102600716-178b7200-4117-11eb-8183-d95b0c211c7a.png">

### Changes
- Title bar removed on iPhone
- Title replaced with "Document" on iPad
- Italic text removed from references titles
- Styling changed for "Referenced In" heading
- Separator removed for last child in document and referenced in lists
- Reference count added.

**Comment by charliescheer** [comment]
@SylvesterWilmott I have been putting in some work on these changes and am almost finished with them.

Question though, for the updating of the styling on Referenced In.  I see that we removed the uppercasing for that text, but are there any other changes you were looking for.  It seems like the text may have gotten a bit larger, but I wasn't sure.

Also for removing the title bar, I see you added a dismiss swipe bar at the top, is this an image that we are already using in Simplenote.  I dug around a bit to see if this might be built into iOS already and didn't see a way to activate it, but I may have missed something.

Thanks, will let you know if I have any more questions
