### ISSUE TITLE
Double autenthication required

### ISSUE THREAD

**Issue by PaoloC95** [Automattic/simplenote-ios#1078]
When biometric security (touch ID for my phone) is activated, at app start is required two times instead one.

There's no problem because can be cancelled the second time and allow your login, but isn't normal that.

iPhone SE (1st gen) | iOS 14.3 | Simplenote version 4.29

**Comment by eshurakov** [comment]
Thank you for the report.
This issue is fixed in version 4.30 (yet to be released) along with the updated passcode screen #761.

Closing it for now, if the issue still happens in version 4.30 feel free to reopen it.
