### ISSUE TITLE
[Note Editor] Last tag is not removed when removed on other device

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-ios#1098]
### Expected
When tags are edited on another device, the changes should be reflected immediately (or at least after some time). In my understanding, this relates both to tags list and to tags in note editor.

### Observed
Once tags are deleted from a note on another device (tested electron and native), the last tag will remain in note editor preview in iOS device, until the note is reopened

### Reproduced
> 1. iOS: create a new note and add several tags to it
> 2. iOS: keep the note editor open
> 3. Other device: Start deleting the tags from that note. Either from tags list, or just remove the tags from that individual note
> 4. Observe on iOS: While first tags from the deleted ones will disappear from iOS device in real time, the last tag will remain forever, unless note is reopened

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|XR|14.3|4.30

https://user-images.githubusercontent.com/73365754/105015719-8297d380-5a4a-11eb-8d2d-996785c6a95d.MP4

**Comment by illusaen** [comment]
Note: I looked into reproducing this bug, and it seems like it's not just the last tag; there's something about removing tags too quickly that will stop the display. The note will just keep showing the removed tags until the screen is somehow refreshed (either by leaving/re-entering the note, or by a different sync, i.e. changing the note itself in the other platform).

**Comment by illusaen** [comment]
After extensive testing, I can't get this to happen anymore after the changes that @eshurakov made. 👍 👍 👍 to @eshurakov !
