### ISSUE TITLE
Freeze after bringing the app to FG

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#110]
On an iPad running iOS 10.0.2, Simplenote keeps crashing: the keyboard freezes and the interface freezes upon returning to the app after leaving. When the user leaves the note (goes back to the screen with all notes listed under each other) before switching away from the app, and then returns to the app, all works well. When the user stays in the note and leaves from the note, upon return they get the bug. This is what happens:

```
– I start up the app and everything works

I switch away (leaving it on in the background)
after returning, the notes are frozen. No more text input possible. Keyboard is unresponsive and cannot be closed. Strangely enough, I can switch between notes. Just no input anymore.
after I actually close the app, at the next startup everything works again. Until I switch away.
etc.
```

**Comment by KokkieH** [comment]
Another report on iOS 10.1.1

Initially reported a month ago [here](https://twitter.com/user/status/795335353259278336)

User only replied with more info today, [here](https://twitter.com/user/status/806643279013945344)

**Comment by bummytime** [comment]
Tested on an iPad running iOS 12.2 — could not repro. Closing for now.
