### ISSUE TITLE
Add to Wind Down Shortcuts

### ISSUE THREAD

**Issue by rcstr** [Automattic/simplenote-ios#1100]
### What
Add Simplenote to the new Wind Down Shortcuts menu.

### Why
Right now is not possible to use Simplenote when Wind Down mode is active
### How
[Adding Shortcuts for Wind Down](https://developer.apple.com/documentation/sirikit/adding_shortcuts_for_wind_down)
![IMG_1839](https://user-images.githubusercontent.com/532402/105125621-750e3800-5aa2-11eb-801d-d4e89f3b2de7.PNG)

**Comment by charliescheer** [comment]
Hi there @rcstr 

Thanks for the suggestion!  Just so you know, you can add any shortcuts to your wind down options even if they aren't featured in one of the categories.

To do that, while in the add shortcut to wind down view and swipe all the way to the bottom and look for "All other apps"

<img src="https://cdn-std.droplr.net/files/acc_593859/eEbAuy" />

Choose that option and find Simplenote there.  You will see all of the Simplenote shortcut options in that menu

**Comment by jleandroperez** [comment]
Closing this one. Thanks for reaching out!
