### ISSUE TITLE
Always visible Sort Bar

### ISSUE THREAD

**Issue by eshurakov** [Automattic/simplenote-ios#1104]
Updates for Sort Bar:
* always visible on the note list screen
* unify 'normal' sorting and search sorting
* remove separate order button, both will be chosen at the same time
* update sort options
* use Tracks event: spios_settings_search_sort_mode

Sort Bar will support the following options in the following order:
```
Name: A-Z
Name: Z-A
Created: Newest
Created: Oldest
Modified: Newest
Modified: Oldest
```

|||
|-|-|
|![ios_sorting-7](https://user-images.githubusercontent.com/54751/105319179-c9a9d400-5bc4-11eb-9c5d-59e908e78a01.png)|![ios_sorting-3](https://user-images.githubusercontent.com/54751/105319595-65d3db00-5bc5-11eb-90a2-3f696f604b40.png)|

Ref: p2XJRt-2Ct

**Comment by jleandroperez** [comment]
Closing in favor of #1209, since this issue is no longer relevant: Sort Bar is scheduled out.

Thanks Evgeny!!
