### ISSUE TITLE
Copy Link URL With Standard Action Sheet

### ISSUE THREAD

**Issue by Titanas0** [Automattic/simplenote-ios#112]
When viewing a URL and tap and hold it, Simplenote only opens the URL. Instead it would be more useful and faster if the default iOS Action Sheet would appear with options such as Open, Copy, Share.

Reference: https://developer.apple.com/ios/human-interface-guidelines/ui-views/action-sheets/

Right now the only option to copy a URL is to edit the text in a note and select the URL as normal text.

**Comment by crankygeologist** [comment]
Yes, please.

**Comment by charliescheer** [comment]
Issue is fixed.  When in edit mode, the link is not parsed as a link and is just treated as text, when in preview a single press opens the link and a long press opens the standard apple link action sheet:

<img width="200px" src="https://cdn-std.droplr.net/files/acc_593859/hBkGpi" />

Closing issue

**Comment by crankygeologist** [comment]
Thank you!
