### ISSUE TITLE
Tags: Use comma as a delimiter when adding tags to a note

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/simplenote-ios#1120]
Currently, Web/Electron and native MacOS use the comma character as a delimiter when adding tags to a note. 
Based on some internal discussion p2XJRt-2Fi-p2 iOS should work the same way.

### What
When adding tags to a note inputting the comma character should submit the tag and be used as a delimiter instead of being part of the tag.

### Why
This would help be consistent across the other platforms and follow other conventions.

**Comment by jleandroperez** [comment]
@sandymcfadden Thank you for filing this one!
