### ISSUE TITLE
No welcome note after signup

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-ios#1121]
I just encountered this issue while testing the mixed-case email verification bug, I don't know if it's related, but I created a new account with a mix of uppercase and lowercase letters.

This is the first screen I see:

![IMG_9583](https://user-images.githubusercontent.com/52152/106552780-cb30a180-64cc-11eb-91f7-4b32a6f461c4.jpg)

Even logging out and logging back in did not cause the welcome note to appear.

As a side note, should "Create your first note" be a link or something? It looks very tappable!

### Expected
Welcome note should be added

### Observed
No welcome note

### Reproduced
iPhone 12 mini, iOS 14.3, Simplenote beta 4.31.0.0

**Comment by eshurakov** [comment]
> As a side note, should "Create your first note" be a link or something? It looks very tappable!

@SylvesterWilmott, what do you think?

**Comment by eshurakov** [comment]
As of the welcome note, we're now adding it only on clean app install. We should update our logic around creating a welcome note as it causes some other issues. I will create a separate ticket for that (#1131).

**Comment by SylvesterWilmott** [comment]
>As a side note, should "Create your first note" be a link or something? It looks very tappable!

That wasn't the original intention but there's no good reason why it shouldn't be tappable! Issue created for that #1132
