### ISSUE TITLE
View trashed note content

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-ios#1126]
### What
User should be able to tap a trashed note and see its content

### Why
Viewing trashed notes is available in Electron / macOS / Android. p2XJRt-2FK-p2

**Comment by Dhanoosh** [comment]
Hello @pachlava @charliescheer,

I'm a Simplenote user and would like to contribute to the project. I've noticed that the issue #1126, "View trashed note content," still exists in the iOS app. I'm interested in working on this feature to align the iOS app's functionality with other platforms.

I'll start working on the issue and submit a PR once it's ready. If there's any additional information or guidance you can provide before I begin, please let me know.

Thank you!
