### ISSUE TITLE
Add monospace font

### ISSUE THREAD

**Issue by rnsi-4** [Automattic/simplenote-ios#113]
Please, add font selection in settings menu. 
I do realy need monospace font for formatting of the notes.

**Comment by danilomm** [comment]
Me too!

**Comment by jerry-bonner** [comment]
Yes!

**Comment by walrusk** [comment]
+1 on this feature. A monospaced font would make simplenote 10x more useful to me.

**Comment by hjma29** [comment]
+1

**Comment by kngtani** [comment]
+1

**Comment by lparsons** [comment]
Yes please!

**Comment by mizejewski** [comment]
Is a monospace font to be added soon?

**Comment by jasonbraganza** [comment]
Please! Pretty please!

**Comment by setekhid** [comment]
+1 my table of markdown format shows like a shit

**Comment by meesern** [comment]
+1

**Comment by dskrad** [comment]
Please add monospace font to web app and mobile apps.

**Comment by t3t3** [comment]
++ monospace

**Comment by bjornakr** [comment]
+1

**Comment by atheoang3l0** [comment]
+1

**Comment by brentirwin** [comment]
+1

**Comment by bummytime** [comment]
Closing in favor of #32
