### ISSUE TITLE
Cursor changes position on new note.

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/simplenote-ios#114]
Reported by a user:

> you create a note and you start with the title and skip a line, when long tapping to paste some text from the clipboard the cursor jumps to a line above, thus removing the skipped line.

I was able to replicate the issue on my own device (iOS 10.1.1). To replicate:

1. Copy text from another note or web page.
2. Start a new note.
3. Type in a title.
4. Hit the Return key twice to skip a line after the title.
5. Hold down on the line to paste the copied text.

This only opens the first time you attempt to paste in this manner; if you hit Return again to make the line spacing, it doesn't move back to the line above.

**Comment by bummytime** [comment]
Closing in favor of #27
