### ISSUE TITLE
[Info Sheet] References count is not counting right

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-ios#1147]
### Expected
References count should show the count of usage in every note separately

### Observed
When the note is referenced in other notes, the ref. count will show the same number for each note where it's referenced (i.e. total number of references VS individual number of references):

![Screenshot_2021-02-12 11 44 50_ooWsfL](https://user-images.githubusercontent.com/73365754/107752872-febec780-6d27-11eb-8318-63887d50a700.png)

### Reproduced
1. Copy an internal like of Note1
2. Insert the link into Note2 once and Note3 also once
3. Open Note1
4. Open Info Sheet and check the references number ~> 

**Actual**: it shows '2' for Note2 and '2' for Note3.
**Expected**: should show '1' for both

**Additionally**: it also looks like references inside note are not counted correctly. For example, referencing Note1 in Note2 twice will still show 1 reference.

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|XR|14.3|4.32.0.0
iPad|Pro (Sim)|14.4|4.32.0.0

**Comment by charliescheer** [comment]
Thanks for flagging this @pachlava 
The original updates to the info sheet that included the references where done in response to #1061 

The design for that had each reference showing the total number of references, as it currently does. @SylvesterWilmott  with the redesign of the info sheet, is the reference count supposed to show the total number of references as shown in the image above?  Or was it supposed to display a different value?

**Comment by SylvesterWilmott** [comment]
The references label indicates the number of individual references of the current note contained within each one of the references. So if I mention the current note 10 times in one reference then it should show "10 references". I had no idea it was working differently.

**Comment by charliescheer** [comment]
That was my mistake.  Seems rather obvious now....  It is currently just showing the total number of times a note is being referenced from any note.

**Comment by SylvesterWilmott** [comment]
No worries, now that I look back at the design it wasn't so clear because they all say the same number.
