### ISSUE TITLE
Swiping right while viewing a note opens a new note.

### ISSUE THREAD

**Issue by charliescheer** [Automattic/simplenote-ios#115]
Reported by user

> When in a note, can swipe to the right to go back to the list view, but if action isn't completed (e.g. swipe partially across the screen and lift finger, with not enough total travel to trigger the back action) blank note page is revealed. 

I was able to recreate this issue.  Steps to do so,

1. Open a note
2. Swipe to the right just a bit, so that the list of notes is just starting to show.
3. Lift finger

You should now see a new note that has not been created and will not save.

**Comment by Lochlaer** [comment]
Another user reports a similar issue in #3135675-t. He's actually saying that the note he is just semi-swiping *from* goes blank, but I'm clarifying to check if what he's really seeing is a new note that's just been created.

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Just tested this on Simplenote 4.7.0, iOS 12.2 and was not able to repro. Closing this issue for now.
