### ISSUE TITLE
iPad mini: App won't rotate if tag list is open

### ISSUE THREAD

**Issue by catkit** [Automattic/simplenote-ios#117]
## Description:
A user reported that the iPad app rotates correctly normally according to the device position, but does not rotate at all with the tag list open. Once the tag list is closed the app rotates.

## What I expected:
The app should rotate to match device orientation with or without the tags list open.

## What happens:
The app doesn't rotate while tags list is open.

## Steps to reproduce:
1. open the tag list 
2. rotate the device
3. close the tag list.

**Device and app versions:** iPad Mini 1st gen (non-Retina display) running iOS 9.3.5 and Simplenote 4.4.1.

**Comment by catkit** [comment]
Support Ticket: #2922404-t

**Comment by bummytime** [comment]
Works as designed. Closing.
