### ISSUE TITLE
Crash when searching with English + non-English combinations

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-ios#1193]
It was originally reported in 3780689-zen that when searching for notes using English + Japanese characters, the app crashes when they tap on the search result.

I was able to replicate this with the English + Chinese combination.

### Expected

I would expect the app doesn't crash when I tap on the search result after performing a search using English + non-English (Japanese/Chinese) characters.

### Observed

The app crashes when I tap on the search result after performing a search using English + non-English (Japanese/Chinese) characters.

### Reproduced

1. Create a note with a combination of English + Japanese/Chinese characters (e.g. Abc中文）
2. Search the note with this keyword: Abc中文
3. Tap the search result and the app crashes

Video recording: https://d.pr/v/bh9rOc/6fWEeWoEl4

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPhone SE|14.4|4.32
Apple|iPhone X|14.4|4.32
Apple|iPod touch 7th|14.4|4.32
Apple|iPad mini 5th|14.4|4.32

**Comment by pachlava** [comment]
Also reproduced with

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|XR|iOS 14.4|Simplenote 4.33.0.0

Wondering if it can have same roots as #1195

**Comment by eshurakov** [comment]
This can also be reproduced the following way:
1. Create a note.
2. Add a tag.
3. Go to your list of notes.
4. Search for the previously added tag.
5. On the list of notes that contain that tag, click on the note.

**Comment by eshurakov** [comment]
Crash reference: SIMPLENOTE-IOS-9W7
