### ISSUE TITLE
Registration is not working on iOS 14.4

### ISSUE THREAD

**Issue by alexchhll** [Automattic/simplenote-ios#1194]
Registration is not working on iOS 14.4

### Expected
The user should be able to register with the iOS app.

### Observed
The user can't register with the iOS app.

### Reproduced
1. Click on Register.
2. Fill the form (email address and password).
3. Click on Register.
4. The following message is showing: "Désolé ! Nous rencontrons des problèmes. Veuillez réessayer dans quelques instants." (Sorry, We are facing some issues. Please retry in a moment.")

### Screenshot
<img src="https://user-images.githubusercontent.com/48022351/110349478-0a559380-8033-11eb-8832-3c7ca925d5d5.png" width="250" />

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPhone XS Max|iOS 14.4|Simplenote 4.32

**Comment by jleandroperez** [comment]
Thank you for reaching out @alexchhll, we're working on this at the moment.

Closing the issue since it's not needed.
