### ISSUE TITLE
Crash when trying to open a Japanese note from Search, if character count is high

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-ios#1204]
This user has reported that when they perform a note search in Japanese, the app crashes as long as they try to open a note if the search query was "long", for example long queries or multiple using words. If the query has not many characters, notes seem to open normally.

It seems to work with 3-5 character long words, like "ロール" but fails if search queries are longer than that.

### Expected
To be able to open the notes without crashing

### Observed
The app crashes when you try to open a note, if the word query used had more than 3 characters, or multiple words.

### Reproduced
I couldn't reproduce this. Some cases shared by the user:

- I write "ロールスクリーン" with Japanese characters in the search box, the app shows one note rightly. Then I try to open this note, app crashes.

- I reduce the number of characters of the search word from "ロールスクリーン" to "ロールスクリー", "ロールスクリ", "ロールスク", "ロールス". In every cases, when I try to open the note, the app crashes.

- I write "ロール" , the app responds rightly; showing 5 notes. This time, I can open every 5 notes without cash.

- I open the one note, it shows highlight position wrongly, although other 4 notes shows highlight position rightly.

Apple |  iPhone 11 | IOS 13.5.1 | Simplenote 4.32

**Comment by pachlava** [comment]
@iamgabrielma thanks for the report! Wondering if this has the same roots as #1193

**Comment by mdrockwell** [comment]
Possibly another related instance here: 3805837-zen (bug 1)

> If try to open a note including a Japanese compound word via search results, Simplenote app will force-quit.
> This bug has occurred since v4.32

They also shared a video in the ticket and these steps to reproduce:

1. Create a new note and input a Japanese compound word "てんぷらそば" in the note.
2. Search for the word "てんぷらそば" in the app.
3. Open a extracted note.
4. The app will force-quite.

**Comment by charliescheer** [comment]
Tested this just now and the problem is the same as #1193 
Created a PR that fixes #1193  
Tested that against this issue and it fixes this one as well :)
