### ISSUE TITLE
TagsEditor Stuck When swiping to markdown preview

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#1211]
### Details
While testing #1200 I've spotted a VoiceOver bug:

1. Open the Editor
2. Enable VoiceOver
3. Push the Markdown Preview via the 3 finger right swipe
4. Go back to the editor

As a result, the Keyboard will be dismissed, but the Tags Editor will remain visible in the middle of the screen.

### Demo
https://user-images.githubusercontent.com/1195260/111329169-b0198b80-864d-11eb-920b-67bbd634c131.mp4

**Comment by charliescheer** [comment]
Did some testing, and it is not a voiceover bug.  Happens if you swipe to markdown w/o voiceover too.  Updated issue title
