### ISSUE TITLE
Simplenote Always Opens to a Tag List Instead of All Notes

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/simplenote-ios#1218]
### Expected
Switching to All Notes before closing the app should force the app to open to All Notes again when reopening.

### Observed
If you force quit the app, when relaunching the app, it will always launch to a tag list.

### Reproduced
1. Open a note from All Notes.
2. Add a tag to the note.
3. Go back to All Notes
4. Tap on Menu then tap on a tag from the list.
5. Force quit the app.
6. Relaunch Simplenote.
7. Switch to the All Notes view.
8. Force quit the app.

It will now always open to the tag view, even if the tag is removed from the note and the tag is deleted from the tag list.

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPhone 11 Pro|14.4.1|4.33.0.0

**Comment by jleandroperez** [comment]
Closing this one as `wontfix`. This is related to the way State Restoration works on iOS (on force quit the previous state isn't expected to be restored, **unless** the user backgrounds the app first).

Thank you sir!

**Comment by pachlava** [comment]
@mdrockwell beautiful find! Definitely irritating, but I've noticed that re-login solves the issue.

**Comment by mdrockwell** [comment]
@jleandroperez This does appear to occur when you close the app and it is removed from memory as normal (that's my understanding of what happens on iOS, anyway).

So at the moment, every time I launch Simplenote on my iPhone, it opens with a specific tag selected instead of All Notes. Even though each time I head back to the home screen, I switch to All Notes first.

To clarify, I'm not force quitting the app anymore, I'm just closing it as normal. If I launch it immediately (and it's still in memory), it works as expected. But if I wait long enough for it to be purged from memory, I get the tag selected.

**Comment by mdrockwell** [comment]
Possibly related: 3848206-zd-woothemes

> My Simplenote always starts with the trashcan

> I use an iPhone XR with OS 14.4.1. and Simplenote 4.33.1

**Comment by jleandroperez** [comment]
We're using the standard State Restoration mechanisms, not sure what might be going on, but sounds like a deeper investigation is due.

I'll take a look at this, thanks for reopening!!

**Comment by reginabally** [comment]
Another report in 3871135-zd-woothemes (with screen recordings). iPhone X, iOS 14.4.2, Simplenote 4.33.1.

**Comment by rossanafmenezes** [comment]
Another report here 3908033-zen

**Comment by thabotswana** [comment]
Another report in 3958442-zen

iPhone 11 Pro
iOS 14.5
Simplenote 4.34

**Comment by rossanafmenezes** [comment]
Another report here 3964865-zen

**Comment by reginabally** [comment]
Another report in 4029137-zd-woothemes

**Comment by eduardozulian** [comment]
Also in 4048547-zen

**Comment by reginabally** [comment]
Another report in 4073667-zd-woothemes

**Comment by ggteixeira** [comment]
I'm facing the same problem. Simplenote 4.37. iOS 14.6.

**Comment by mdrockwell** [comment]
Another: 4104336-zd-woothemes

**Comment by mdrockwell** [comment]
Another: 4106796-zd-woothemes

**Comment by mdrockwell** [comment]
Another: 4117775-zd-woothemes

**Comment by reginabally** [comment]
Another report in 4123166-zd-woothemes

**Comment by eduardozulian** [comment]
Another in 4126920-zen
