### ISSUE TITLE
Unable to pin note to top during note creation

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-ios#1236]
It was reported in 3885636-zd-woothemes that when you create a new note, the first attempt to pin a note to the top isn't working. 

### Expected

I would expect to be able to pin a note to the top when I create a new note.

### Observed

The note didn't get pinned to the top, I need to enable the "Pin to Top" option the second time for it to work.

### Reproduced

1. On the Simplenote iOS app, create a new note
2. Type some text in the note
3. Tap the Options (three dots) button, enable the "Pin to Top" option, and tap "Done"
4. Go back to the note list and see that the note isn't pinned to the top

Video recording: https://d.pr/v/x8NRjg/DPpEUoWRQU

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPad|iOS 14.4.2|4.34
Apple|iPhone SE|iOS 14.4.2|4.34

**Comment by pachlava** [comment]
While testing, I noticed it was depending on how fast is all was executed... tend to happen more often when it's fast (note is pinned before it's created?, not sure). I also reproduced this in Electron, but under a condition when the window is so narrow that it allows showing only the note list or note editor

**Comment by charliescheer** [comment]
Hmmm, I am not able to replicate this.  Can't imagine anything has changed to fix it... maybe the hardware is faster and previously we were trying to pin a note before it existed?  I'm gonna close this for now but if the problem starts occurring again feel free to open
