### ISSUE TITLE
Pin lock UI can become misaligned

### ISSUE THREAD

**Issue by frosty** [Automattic/simplenote-ios#126]
Whilst testing the fix for #125, I found an issue where the pin lock UI can become left aligned on iPad instead of centre aligned.

![simulator screen shot 23 jan 2017 10 29 57](https://cloud.githubusercontent.com/assets/4780/22201263/c3598606-e15a-11e6-9f64-5fe1a7560a44.png)

To recreate:

* Open Simplenote in a multitasking split pane (left or right).
* Enable pin lock
* Double tap the home button to open the app switcher.
* Simplenote will show the pin lock screen, but the pin entry UI will now be offset to the left until you unlock the app.

**Comment by jleandroperez** [comment]
Closed by @charliescheer  via #671 

Thank you sir!
