### ISSUE TITLE
Markdown: Preview should support HTML tags

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-ios#127]
It was brought up by a user that the iOS app doesn't support HTML tags in the markdown preview. We should add support for these in the iOS app since the web app and android support it as well.

Security-wise we should ensure that we don't expose anything dangerous with this (not allow `<script>` tags for example).

**Comment by roundhill** [comment]
OK, thanks for investigating. I wouldn't think this is a big deal, but because you can share notes with another user I think there's a potential for some security issues there.

**Comment by jleandroperez** [comment]
Closing as `wontfix` (at least for the time being). Let's reopen, if needed, in the future.

Thanks gentlemen!!
