### ISSUE TITLE
URLs not clickable in search

### ISSUE THREAD

**Issue by fditrapani** [Automattic/simplenote-ios#130]
A note from one of our users in #3045296-T:

> I use notes to store urls and can click on these to go directly to a web page.
>
> HOWEVER: if i search for a particular term and retrieve a note containing a url, then the search term is highlighted in the note and the url is not clickable.

**Comment by jleandroperez** [comment]
Closing as cannot repro. **Potentially** fixed via #248, since we used to have a custom linkifier (and it may have had interfered when search was active).

Thank you!
