### ISSUE TITLE
[Question] Isn’t GPL code banned on the App Store? 

### ISSUE THREAD

**Issue by colbyn** [Automattic/simplenote-ios#1300]
Personally I'm fine with the license, but isn't GPL code banned on the App Store?

**Comment by jleandroperez** [comment]
Hey there @coldbyn,

Apple's AppStore and GPL aren't incompatible, as long as you [hold the rights of the source](https://apple.stackexchange.com/questions/6109/is-it-possible-to-have-gpl-software-in-the-mac-app-store). 

Thank you for reaching out!!

**Comment by colbyn** [comment]
Oh that makes sense, @jleandroperez  thanks for your reply.
