### ISSUE TITLE
Infinite failed passcode attempts

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-ios#132]
Not sure if this is intended but failing to enter the correct passcode allows you to keep trying an infinite (tested up to 34 on my end) number of times

**Steps to reproduce:**
- Launch Simplenote.
- Activate the Passcode feature under Settings > Passcode > On.
- Add a 4 digit passcode, for instance 1234.
- Close the app and relaunch.
- Enter a wrong passcode.
- Keep entering the wrong passcode.
- You'll get the "x Failed Passcode Attempts" message.

**What would I expect?**
As you get stuck in the "Unlock Simplenote" screen and there's no message for the user on how to workaround that or access to their notes, I'd suggest a message after 3 failed attempts on the lines of 

> "Have you lost access to Simplenote? You can regain access by re-installing the app and logging into your account."

As reinstalling the app would request your email and password in order to log in, that should be alright and at the same time there's an effective way to get out of the loop of not being able to access to your account and not getting a message on how to solve that.

**Comment by iamgabrielma** [comment]
Same issue for the Android version here: https://github.com/Automattic/simplenote-android/issues/427

**Comment by jleandroperez** [comment]
Closed via #140
