### ISSUE TITLE
Face ID gets activated if app is killed while `Set up Passcode` is shown

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-ios#1327]
### Expected
Face ID should not be activated unless passcode is set.

### Observed
Face ID switch is activated (but not really used) if the app is killed when `Set up Passcode` prompt is shown. Probably because the switch is turned on in the background, while the prompt is shown:

https://user-images.githubusercontent.com/73365754/122121292-1d4ae180-ce34-11eb-87d2-72b56cedb51a.MP4

### Reproduced
1. Have Face ID and passcode deactivated
2. Activate Face ID ~> you will see a prompt
3. While prompt is shown, kill the app
4. Open the app again and open settings ~> Face ID is active while passcode is not set.

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|XR|14.6|4.38.0.0

**Comment by charliescheer** [comment]
I fixed this a few months back.  Appears I forgot to link the issue to the PR.  https://github.com/Automattic/simplenote-ios/pull/1595
