### ISSUE TITLE
Sharing from WordPress for iOS does not include URL or any text

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-ios#133]
### Expected behavior

If I share a blog post from the WordPress for iOS app to Simplenote, it should include the target name (Simplenote) and at least a link to the blog I'm sharing.

### Actual behavior

Nothing (no URL and no text) is shared from the WordPress app, and Simplenote isn't identified as the sharing target.

![2017-02-09 20 57 57](https://cloud.githubusercontent.com/assets/8658164/22929931/faf82b3c-f2b5-11e6-89c5-3dc1cb806008.png)

The same post shared from Safari includes the post title, site title, and a link to the post in the note.

#### Steps to reproduce

1. Open the WordPress for iOS app.
2. Open the Reader.
3. Find a post and share it.
4. Select Simplenote as the sharing target.
5. Note that the share box is empty and you have to enter text to enable the "Post" action.
6. Tap "Post" to share it to Simplenote.
7. Open the note in Simplenote.

Result: The note is empty except for the text you entered.

You can repeat the same steps with sharing from other parts of WordPress (e.g. from the Blog Posts list or after publishing a new post) with the same results.

##### Tested on iPhone 6, iOS 10.2.1, Simplenote 4.4.2 & WPiOS 6.9.0.20170210 (beta).

**Comment by dschneiderch** [comment]
I'm seeing something similar on another website: https://support.mozilla.org/en-US/kb/whats-new-firefox-ios-version-10 (I was just testing the simplenote app for the first time)
when I access the share menu from firefox on my iphone and choose simplenote, I see the title of the webpage 'What's new in Firefox for iOS (version 10) | How to | Mozilla Support' and a thumbnail for the webpage. But when I open simplenote, I only have the title of the webpage in the note and no url or link. I was expecting the link to be copied too.

I'm running on an iPhoneSE,  iOS 11.0.3, Simplenote 4.4.3

**Comment by bummytime** [comment]
From WPiOS, we should take advantage of the updates that @nheagy just landed: https://github.com/wordpress-mobile/WordPress-iOS/pulls?q=is%3Apr+is%3Aclosed+label%3A%22Share+Extension%22+author%3Anheagy

**Comment by jleandroperez** [comment]
Closing this one since, as of the latest build, the associated resource URL is indeed being shared.
Please feel free to reopen if needed.

Thanks everyone!
