### ISSUE TITLE
Swiping Left on Markdown note should lead to All Notes View

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/simplenote-ios#135]
On a normal note, swiping left from the note editor leads to the All Notes view.
On a note where markdown is enabled this fails and the "<Notes" button must be pushed.

**Steps to replicate**
1. Add a note in Simplenote for iOS
2. Enable markdown for the note
3. Add some markdown content
4. Swipe to see markdown preview
5. Swipe back note editing
6. Swipe back to Notes view, but notice it fails

**Context**
User-reported in 3077931-t

**Comment by bummytime** [comment]
Verified in iOS 12.2, Simplenote 4.7.0.

**Comment by jleandroperez** [comment]
Closing in favor of #491. Scheduled to be fixed in the next release, apologies it took us so long to get to it!!

Thank you!!!
