### ISSUE TITLE
Hi there, why remove the new note bar ?

### ISSUE THREAD

**Issue by zlorn** [Automattic/simplenote-ios#1362]
Since the new note button was changed to the lower right corner, I like it very much, because I can use my right thumb to create a new note with one hand, just like Apple's own notes. But for the new version, you deleted it, That was disappointing. If some users don't like it, I hope you can add a setting to let users decide the location of the new note button, thank you!

**Comment by jleandroperez** [comment]
Thank you for reaching out @Zaolon !! I'll pass your feedback to the design team 😄 

Hope you have a great day over there!
