### ISSUE TITLE
Preview mode default

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-ios#137]
Allow preview mode to be the default view when you open a note.

Same as this request - https://github.com/Automattic/simplenote-electron/issues/381 - but for iOS

Requested in #3092681-t

**Comment by jleandroperez** [comment]
Closing as duplicate of #403. (Actually it's the other way around, but #403 links to the Android issue that has been already solved!!).

Hope you're doing great Rachel, thank you!
