### ISSUE TITLE
Dark Mode: code block is not dark in note preview

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/simplenote-ios#1372]
When using dark mode, the preview note option in the web app shows a nice dark color scheme for code blocks. The same does not happen when previewing the note from the iOS app instead.

### Expected
To see code blocks in a dark color scheme like we do in the web app:

<img width="853" alt="Captura de Tela 2021-07-30 às 12 03 09" src="https://user-images.githubusercontent.com/1136160/127673027-4118c0cd-665b-44b7-b38a-8b51a2955b4f.png">

### Observed
Code blocks are not changed at all:

<img width="450" alt="Captura de Tela 2021-07-30 às 12 03 09" src="https://user-images.githubusercontent.com/1136160/127673726-2254c892-99d4-4be0-b78b-26f00184ba47.PNG">

### Reproduced
1. Add a code block to a note
2. Change the theme to dark
3. Choose to preview the note

#### Internal reference: p1616480324000200-slack-C0133BTEDLJ

**Comment by charliescheer** [comment]
@SylvesterWilmott question for you.  I did a quick check on this, and currently there is no background color set up for `<code>`  in the markdown preview dark colors.  What are the colors you would want for code formatting in the markdown preview?
