### ISSUE TITLE
Chinese inputs are not correctly defined

### ISSUE THREAD

**Issue by Hywan** [Automattic/simplenote-ios#139]
A note from one of our user in #3138309-T:

> Use the Chinese stroke input method, enter the label can not be used normally, each press a key will appear a long string of compliance, as shown.
>
> ![img_4538](https://cloud.githubusercontent.com/assets/946104/24706879/b65b93be-1a11-11e7-8737-58d19147cc55.PNG)

**Comment by Hywan** [comment]
Test data:

> 使用中文笔画输入法，输入标签时无法正常使用，每按一个键会出现一长串符合，如图所示。

**Comment by kristarella** [comment]
This might be similar to the Korean issue https://github.com/Automattic/simplenote-ios/issues/55

**Comment by rachelsquirrel** [comment]
I have a user reporting the same thing for Japanese. 

They input すし and it changes to すすすすすすすすすしすすすすすすすすすすすしすしすし

#3223741-t
