### ISSUE TITLE
Account deletion alert lacks two dots `.`

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-ios#1393]
### Expected
The ends of sentences should be marked with dots. Also, [blueprints](https://simplenotep2.wordpress.com/2021/07/15/account-settings-delete-account-i3/).

### Observed
There are missing dots at the end of user email, and at the end of the very last sentence

![photo_2021-08-10 15 55 35](https://user-images.githubusercontent.com/73365754/128870521-35bf332d-d6ea-473a-8688-d861e4b7fbaa.jpeg)

### Reproduced
1. Log in
2. Tap `Delete Account` in Settings
3. Tap `Request Account Deletion` ~> you will see the dialog depicted above.

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|XR|14.6|4.42.0.0

**Comment by jleandroperez** [comment]
cc @charliescheer (Thank you gentleman!!)

**Comment by charliescheer** [comment]
I have fixed this in a commit on #1395
