### ISSUE TITLE
Delete single notes from Trash

### ISSUE THREAD

**Issue by KokkieH** [Automattic/simplenote-ios#141]
Reported via [Twitter](https://twitter.com/MicahOnly/status/854220174563700736)

In the iOS app it's not possible to delete single notes from Trash, only to Empty Trash.

This is inconsistent with the Android and Electron apps where a single note can be selected in Trash for deletion. The Web and native Mac OS app also don't allow for removing individual notes from Trash.

**Comment by shabirjan** [comment]
PR [#143](https://github.com/Automattic/simplenote-ios/pull/143) 
Added ability to delete single notes from trash.

**Comment by jleandroperez** [comment]
Closed via #143. Props to @shabirjan, thank you sir!!
