### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by notDavid** [Automattic/simplenote-ios#142]
Hi, just wondering, are notes encrypted on the device (protected by pin/touch id)? I'm not talking about a "screen passcode" or something like that, but proper file based encryption.

Are the notes encrypted with a (local-device-only) passcode before being send to the cloud?

Thanks.

**Comment by jleandroperez** [comment]
Hello there,

Simplenote relies on iOS's Filesystem Encryption to secure your data. I'm afraid due to technical requirements, we do not apply a second encryption layer on top of that.

Data is sent via encrypted connections to our servers
