### ISSUE TITLE
Chrome sharing sheet does not include URL

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-ios#145]
If you use the sharing sheet in Safari to share a web page with Simplenote it copies the URL and title of the page. However in Chrome it only copies the page title and does include a link to the page which is pretty useless. I'm not sure whether this is a Chrome problem but if it is we should remove the option to share a web page with Simplenote if using the Chrome browser.

**Comment by jleandroperez** [comment]
Closing in favor of #390 

Thank you all!!
