### ISSUE TITLE
Conflict with gboard app

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-ios#146]
Searching doesn't work correctly when Google's swipe keyboard (gboard) is installed on the device. 

Steps to reproduce
1. Install gboard and activate it in the settings.
2. Create a note with the letters coto.
3. Start searching for this note by typing in cot.
4. The note is found. Then type the full string "coto" and the note disappears from the search results.

**Comment by jleandroperez** [comment]
Closing as cannot repro / iOS 13 / Simplenote 4.16.

Please feel free to reopen if needed. Thank you!

**Comment by ZubairAslamAksa-sds** [comment]
i am facing issue with gboard, when i resume my app and open gboard, gboard overlaps my inputview ,then after some seconds view updates and my inputview comes up from behind the gboard. Kindly help me about this issue.
Regards

**Comment by pachlava** [comment]
Hi @ZubairAslamAksa-sds ! Thanks for the report. While I was trying to reproduce the issue, I [found this](https://github.com/Automattic/simplenote-ios/issues/1356), however, it's reproducible for the native iOS keyboard as well (though the video is recorded using the Gboard). Please let us know if this is the issue that you describe. If not, could you please provide more information? Thanks a lot!
