### ISSUE TITLE
Bug: Searching with a space

### ISSUE THREAD

**Issue by Jokerman53** [Automattic/simplenote-ios#1481]
Trying to search for a specific word by putting a space on the end of the word or text string.

### Expected
In search notes or tags I type in ‘PR ‘, ie. PR with a space after the R, no quotes used.

I expect to find all references to ‘pr ‘ and ‘PR ‘ within any note in Simplenote.

### Observed
What I obtain is are all the notes that have printed, procedures, prior, approaching etc in them. So it appears to me that the search facility ignores the space and wont search for the word I specify. 

If I wanted to pick up print, prints printed, printing, then I’d use print with no trailing space.

If I type ‘with ‘ in the search area it does pick up the individual word with but also withdrawn, withdrawal, within etc which I don’t want.

If I use ‘PR ‘, ie. using the quotes in this case, it physically finds a string that starts ‘pr ignoring subsequent characters, ie. the space and quote. So now I obtain notes that have the strings ‘Probable and ‘prime’ in them.

If I use “PR “ using the double quotes, I find notes with “Probable”. So again the search function seems to throw away the space and end double quote in my search string.

Make|Model|iOS Version|App Version
IPad (7th Gen)| iOS 15.4.1| V4.47

This also happens in my MacOS version of Simplenote. Mac Mini | MacOS 11.4 | Simplenote v2.17

Thanks for your time.

**Comment by Jokerman53** [comment]
> 

I added Bug and it is tagged as such.

**Comment by jleandroperez** [comment]
Closing this one, since "exact match" isn't a supported feature. 

That being said, I've added a vote in our (internal) features request system, for this enhancement.

Thank you for reaching out!!

**Comment by Jokerman53** [comment]
Thanks for adding my suggestion to the features list.

regards,
Gordon Clarke
Aviation Historian (WW1 & WW2),
Author of “This Smuttee Squadron”
Member of ASWW1AH, AHSA and Cross & Cockade International
I acknowledge the Giabal and Jarowair people on whose land I write.
