### ISSUE TITLE
Simplenote Becomes Unresponsive After Creating Note With Checklist

### ISSUE THREAD

**Issue by lromero16** [Automattic/simplenote-ios#1484]
Simplenote running on iPhone 6, running iOS 12 (version 4.45.1) becomes unresponsive when creating notes with checklists.  Unresponsiveness only happens when using checklists.

### Expected
***Simplenote should not freeze when creating notes using checklists*** 

### Observed
***User reports this issue only happens on their particular device, and they are not able to update their iOS software.  They are able to use simplenote successfully on other platforms*** 

### Reproduced
***I have not been able to reproduce, as I don't have an iPhone 6 running iOS 12.  These are the users notes on how to reproduce:***
> 1. Open Simplenote
> 2. Create new note
> 3. Add Checklist
>4. App becomes unresponsive for 10 or more minutes

Make|Model|iOS Version|App Version

iPhone 6, iOS 12, Simplenote 4.45.1

**Comment by charliescheer** [comment]
As of a recent update, the minimum supported version of iOS for Simplenote is 13.  Since this seems to be an iOS 12 specific issue I am gonna close this issue
