### ISSUE TITLE
iPad: Crash when tapping on Simplenote Sustainer button in sidebar

### ISSUE THREAD

**Issue by spencertransier** [Automattic/simplenote-ios#1499]
### Expected
On iPad, tapping the Sustainer button in the sidebar should open the action sheet

### Observed
On iPad, tapping the Sustainer button in the sidebar crashes the app

### Reproduced
1. Open Simplenote 4.48 on an iPad
2. Open the sidebar
3. Tap the Sustainer button
4. The app crashes

### Screen Recording

Uploading RPReplay_Final1668474704.MP4…

### Device Info
Apple - iPad Pro 11 - iPadOS 16.1.1 - 4.48.01

**Comment by jleandroperez** [comment]
Closed via #1501.

Thank you Spencer!!
