### ISSUE TITLE
Collaboration doesn't work on iPad (iOS 7 only)

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#15]
If you try to collaborate a note on an iPad in iOS 7, no field appears to enter email addresses.

Works fine on iOS 8. Might also impact iPhone, I didn't test that.

Opened by @roundhill

**Comment by kevmarsden** [comment]
The collaboration button works properly on an iPhone running iOS 9.3.5.  Confirmed that it does not work on an iPad running iOS 9.3.5.

**Comment by kevmarsden** [comment]
Related issue for iOS 9 in #80.

**Comment by jleandroperez** [comment]
Closed via #81. Thanks @kevmarsden, we'll be releasing a new build with the fix soon!
