### ISSUE TITLE
Add Bitwarden password manager autofill

### ISSUE THREAD

**Issue by 211217613** [Automattic/simplenote-ios#1516]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected
***(Required)*** Add a concise description of what you expected.
- username and password should auto fill
- 
### Observed
***(Required)*** Add a concise description of what you observed.
- auto fill doesn't work. Only option is to copy the username

### Reproduced
***(Required)*** If you cannot reproduce this bug consistently, please elaborate.  List the steps to reproduce the behavior.  For example:
1. download app
2. go to login screen
3. auto fill credentials
4. only copy username is available

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

***(Optional)*** If you reproduced the bug on a specific device, please replace DEVICE_MAKE, DEVICE_MODEL, IOS_VERSION, and APP_VERSION below with the details for that device.  If you reproduced the bug on multiple devices, please add a row for each device.

Make|Model|iOS Version|App Version
-|-|-|-
DEVICE_MAKE|DEVICE_MODEL|IOS_VERSION|APP_VERSION

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
