### ISSUE TITLE
Tabs lost when printing

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-ios#152]
A user reports than when they print from the iOS app using the icon in the sharing sheet, all their tabs and spacing is gone. It shows up correctly in the print preview before it's printed but these are removed when it is sent to the printer. I have not been able to test because I don't have any ink in my printer. 

629250-zen

**Comment by charliescheer** [comment]
Tested this and was not able to repo.

Print preview with tabs:
<img width="300px;" src="https://cdn-std.droplr.net/files/acc_593859/gCOw5y" />

Print:
<img width="300px;" src="https://cdn-std.droplr.net/files/acc_593859/M3E3vl" />
