### ISSUE TITLE
Unable to set up Simperium credentials for Simplenote iOS app

### ISSUE THREAD

**Issue by Dhanoosh** [Automattic/simplenote-ios#1529]
I am trying to set up and run the Simplenote iOS app on my local machine for development purposes. I followed the instructions in the README file to set up the Simperium credentials:

```
mkdir -p ~/.configure/simplenote-ios/secrets && cp Simplenote/SPCredentials-demo.swift ~/.configure/simplenote-ios/secrets/SPCredentials.swift
```

However, I am unable to register for a new Simperium account, as the registration is closed. This prevents me from obtaining the necessary `simperiumAppID` and `simperiumApiKey` to properly configure the app.

As a result, I can only see the login or sign up screen when running the app in the simulator.

Could you please provide guidance on how to proceed with setting up the app for development without a Simperium account, or if there is an alternative method to obtain the required credentials?

**Comment by Dhanoosh** [comment]
> Fails
> 🚫	
> Please add a type label to this issue. e.g. '[Type] Enhancement'
> 
> 🚫	Please add a feature label to this issue. e.g. 'Stats'
> Generated by 🚫 [dangerJS](https://danger.systems/js)

I don't have permission to add labels. Perhaps a "Question" will be a right label for this.

**Comment by azollafox** [comment]
As you've noted it isn't possible to sign up for a new Simperium account at this time. We've had a similar issue [raised on our Mac OS repository you can check out for details though on how to get started anyway](https://github.com/Automattic/simplenote-macos/issues/1080)


While you wont be able to access the production environment, you can use [the demo credentials included in the repository as shown in a comment on the above issue](https://github.com/Automattic/simplenote-macos/issues/1080#issuecomment-1380418325)
 
After that you’ll need to manually signup for a (user) account. That involves invoking a REST endpoint, [manually as you see at another comment on the issue](https://github.com/Automattic/simplenote-macos/issues/1080#issuecomment-1381935398).
