### ISSUE TITLE
Tags and new icon disappear iOS 11

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-ios#154]
Steps to reproduce:

1. Test on an iPad with iOS 11 beta 6.
2. Try searching for a tag then clear the search field to return to the list of notes.

On returning to the list of notes the tag icon and new note icon are gone.

![image4](https://user-images.githubusercontent.com/7946521/29818645-403e02d6-8cb5-11e7-9f44-429def15b7f6.jpg)

650183-zen

**Comment by rachelsquirrel** [comment]
Some additional information from the user:

![image1](https://user-images.githubusercontent.com/7946521/30023327-bff4f074-9166-11e7-9161-6cefb44e2685.jpg)

**Comment by jleandroperez** [comment]
Closing as cannot repro. Tested in iOS 12 + 13, Simplenote 4.14.

Thank you all!!
