### ISSUE TITLE
Offline changes not syncing

### ISSUE THREAD

**Issue by nextpulse** [Automattic/simplenote-ios#155]
Using the app offline for 3 days.
Came back online and now nothing syncs (ios app, mac desktop and web).
Signing out and then signing in again brings up the versions before I went offline.
However, any new changes on any of the platforms are no longer being synced (version history for previous notes are all stuck at 3 days ago). 
Basically, the system is stuck at the versions before I went offline and not syncing any new changes.

New/Delete actions on notes are not synced either.

**Comment by jleandroperez** [comment]
For support, please, [contact us here](https://simplenote.com/contact-us/) on or after Sept 18th.

Thank you!
