### ISSUE TITLE
Layout issues on iPhone X in Landscape

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-ios#157]
Tried out the app in an iPhone X simulator, looks like we need to make some adjustments to the landscape layout:

<img width="864" alt="screen shot 2017-09-26 at 12 51 24 pm copy" src="https://user-images.githubusercontent.com/789137/30881618-40db487c-a2bb-11e7-8e79-ccb67cd16163.png">

**Comment by davipontesblog** [comment]
Another report here - 953732-Zen

**Comment by wildmaples** [comment]
This also seems to be fixed on iOS 11 and 12.
