### ISSUE TITLE
Explore siri integration

### ISSUE THREAD

**Issue by charliescheer** [Automattic/simplenote-ios#1570]
As part of refreshing the iOS shortcut support in Simplenote, it should be possible to use the app intents based shortcuts to add Siri integrations.

It should be explored if this is possible with app intents, and if it is we should update the new shortcuts to work with Siri 

ref: #1566

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by charliescheer** [comment]
For now I think we should not add to siri with the shortcuts.  closing this issue
