### ISSUE TITLE
Photos [enhancement]

### ISSUE THREAD

**Issue by SupremeRumHam** [Automattic/simplenote-ios#158]
Allow photos to be uploaded as notes.

**Comment by cecilerainon** [comment]
Another request here: https://woothemes.zendesk.com/agent/tickets/995141

**Comment by ImHUan** [comment]
Badly need this feature

**Comment by jleandroperez** [comment]
I've added this to our feature requests. Thanks for the suggestion!

**Comment by Jason4V** [comment]
> I've added this to our feature requests. Thanks for the suggestion!

Glad to hear! When will it launch?

**Comment by jleandroperez** [comment]
Actually we've moved all of the feature requests to an internal system, which allows us to track how many times a feature has been requested, all across platforms.

And definitely Photos is ranking very high. Thank you for the request @Jason4V !!
