### ISSUE TITLE
Magic Links: Switch to Code Authentication

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#1611]
### Details:
- [x] Wire the new code-based endpoints
- [x] Update the Magic Link Handler so that it manages the new parameters
- [x] Implement a new flow that would allow users to type the code
- [x] Code UI requires a header
- [x] Verify the Invalid Token UI is still triggered
- [x] Verify the Magic Link Flow is still supported
- [x] Improve Error Handling: 429 / Request Code directly in the Code UI?
- [x] Fix Unit Tests
- [x] Return nil when fields are empty

### Mockups
<img width="300" src="https://github.com/user-attachments/assets/1a92828c-d57b-43ba-b5a7-4f282e22a3c9">
<img width="300" src="https://github.com/user-attachments/assets/f18687cd-333b-436f-9e5a-dd1d422c1489">
<img width="300" src="https://github.com/user-attachments/assets/f07bc74d-148d-4ae3-832a-7a0801c0093c">
<img width="300" src="https://github.com/user-attachments/assets/a75d5e83-3193-4b2b-adfd-8f875eae3b90">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
