### ISSUE TITLE
FeatureRequest: Multiple platform supoort.

### ISSUE THREAD

**Issue by rahulmehtas** [Automattic/simplenote-ios#1629]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

### What
***(Required)*** What is the feature you are requesting?  Add a concise description of the feature being requested.

### Why
***(Required)*** Why are you requesting this feature?  Add a concise description of the problem this feature solves.

### How
***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate how the feature could be done.

Such as MacOS.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jleandroperez** [comment]
Thank you for your interest in Simplenote @rahulmehtas 😄 

https://github.com/Automattic/simplenote-macos
https://github.com/Automattic/simplenote-android
https://github.com/Automattic/simplenote-electron

**Comment by rahulmehtas** [comment]
Thanks.
