### ISSUE TITLE
iOS code vs macOS one

### ISSUE THREAD

**Issue by Pacerier** [Automattic/simplenote-ios#163]
Are there much similarities?

**Comment by jleandroperez** [comment]
You're welcome to look at the macOS code [here](https://github.com/Automattic/simplenote-macos)!.

But as a short reply: iOS is based on an Apple framework called UIKit, while the macOS codebase uses the macOS counterpart.

Nevertheless: both, macOS and iOS use the same [Sync'ing Core](https://github.com/Simperium/simperium-ios).

Hope that helps!
