### ISSUE TITLE
Alphabetic index on the right edge of the screen

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/simplenote-ios#164]
Copying here a -happy- user suggestion 

`"I did wonder whether it might be worth adding an alphabetic index on the right edge of the screen in the mobile apps (similar to that in e.g. the native iOS contacts app - to allow quick access to contacts/notes starting with a particular letter)."`

#741594-zen

**Comment by jleandroperez** [comment]
Closing as `wontfix` since sorting isn't only alphabetical, and this doesn't really cover every single case we've got.

Thanks everyone!!
