### ISSUE TITLE
Installable EXE or portable ZIP file

### ISSUE THREAD

**Issue by dcrossmier** [Automattic/simplenote-ios#166]
I would like to try the improvements you’ve made to Simplenote. But I’m not a developer, so I’m hunting for an EXE or portable ZIP file. I’ve been told by your support staff that they won’t be found on Github. Although, it seems to me that Github could allow the developer to upl

**Comment by jleandroperez** [comment]
Hello there,

I'm afraid we don't offer alternative binaries. Simplenote iOS is available only via the Apple's AppStore.
A new version will be released soon, with all of the latest features.

Thanks for your interest in our app!

**Comment by roundhill** [comment]
@dcrossmier are you looking for https://simplenote.com? You can download the app there.
