### ISSUE TITLE
"Cancel" link missing from search window

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-ios#167]
After using the search field and then clicking the "x" in the search, the "Cancel" link doesn't reappear and there's no way to get the tags icon and new note icon back. Reported in 743798-zen on an iPad running iOS version 11.0.3. 

I can't reproduce but the user sent in a screenshot.

![ipad](https://user-images.githubusercontent.com/7946521/31954869-a2cc9070-b8de-11e7-84d9-47299000ef1f.png)

**Comment by jleandroperez** [comment]
Closed via #171. Thanks Rachel!
