### ISSUE TITLE
Unexpected characters appearing when typing double byte characters

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/simplenote-ios#174]
This was reported here: 782536-zen

When I will be entering double byte character エントリー as a tag, unexpected characters will be entered like えええんんんエ. Would you please fix the issue?

I replied to the user to ask for more information about the app version and if this has happened at other times.

**Comment by rachelsquirrel** [comment]
This is probably related to these issues:

https://github.com/Automattic/simplenote-ios/issues/58
https://github.com/Automattic/simplenote-ios/issues/55

**Comment by rachelsquirrel** [comment]
Similar report in 871812-zen

**Comment by eduardozulian** [comment]
Another report in 877182-zen
