### ISSUE TITLE
List of notes appears for a fraction of a second before passcode screen loads

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#18]
Tested on an iPhone 4s with Simplenote 4.0.15 and IOS 8.1.3

Steps:
1. Close the Simplenote app by pressing the menu button and swiping the app off the screen
2. Open the Simplenote app

The list of notes is visible for a fraction of a second which was long enough for me to take a screenshot of it before the passcode screen appeared. 

t-61986

Opened by @rachelsquirrel

**Comment by kriskarkoski** [comment]
Another report in 2877694-t including a video

I have asked for Simplenote version, iOS version, and phone type that I'll add here once I have them

**Comment by bummytime** [comment]
Could not repro on 12.2. Closing.
