### ISSUE TITLE
Character count for Chinese/Japanese/Korean characters is incorrect

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [Automattic/simplenote-ios#191]
Currently Simplenote does not count words correctly for Chinese, Japanese, and Korean when I tested on my iPad. This was originally 
Ideally, for these languages a character count would suffice as it's not commonplace to do word counts like we do in English. 

iPad(ver 4.4.5)
![image uploaded from ios](https://user-images.githubusercontent.com/17694715/36003642-c4f78f2a-0ce3-11e8-8caf-01b47a0ab581.png)
It says 15 words, when there are actually 7 words. 

Total characters(without spaces): 18

**Comment by bummytime** [comment]
Fixed by #224
