### ISSUE TITLE
Speech to text in newly created note deleted when returning to the note list

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-ios#198]
**Steps**
1. Create a new note.
2. Use the audio dictation to record text in the note.
3. Tap the "Notes" link at the top left to return to the note list. 

The newly created note appears in the list as "New note..." but without any of the recorded text. The problem can be avoided if the keyboard is dismissed before returning to the note list.

Reported in #1031737-zen

**Comment by bummytime** [comment]
Tested in iOS 12.2 — unable to repro issue. Closing.
