### ISSUE TITLE
Note List Sorting: Not consistent with other clients

### ISSUE THREAD

**Issue by formosattic** [Automattic/simplenote-ios#204]
At the moment, iOS only support sort by alphetical notes.

 It'd be good to have consistent sorting options throughout the different platforms, like having sort order by creation date as available on iOS.

Additional sorting options available on Android: https://github.com/Automattic/simplenote-android/blob/95b60752061d7ccd9667c6e3606dd14e4f6f69af/Simplenote/src/main/res/values/strings.xml#L77

User request: zd-1246252

**Comment by slimjim777** [comment]
It would be useful to have all the same sort options as on Android, including the reverse/descending sorts.

**Comment by bummytime** [comment]
Current iOS sorting options for note list (alphabetically):
![ios_sort](https://user-images.githubusercontent.com/154014/58281376-a7651080-7d68-11e9-953f-93e834a824ea.jpeg)

### Android:
![android_sort_3](https://user-images.githubusercontent.com/154014/58281442-cd8ab080-7d68-11e9-8e66-b3559e64cae5.png)

### Electron:
<img width="651" alt="electron_sort_1" src="https://user-images.githubusercontent.com/154014/58281483-e4310780-7d68-11e9-93ea-04748d125d87.png">
