### ISSUE TITLE
Markdown Preview and Publish Using Incorrect Fonts

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/simplenote-ios#205]
What's Expected:

When previewing or publishing a note, sans-serif fonts will be displayed, as they are in the featured image here: [https://simplenote.com/2016/08/25/markdown-added-in-latest-ios-app-update/](https://simplenote.com/2016/08/25/markdown-added-in-latest-ios-app-update/)

Steps:

1. Write note using Markdown
2. Swipe left to see the preview of the note -- headers will be in sans-serif (as expected), body text will be serif
3. When the note is published, the body font will also be in serif font

Screenshots available here:

Editor: [http://take.ms/ynkXe](http://take.ms/ynkXe)
Preview: [http://take.ms/ZnkCw](http://take.ms/ZnkCw)
Publish: [http://take.ms/Iz7rd](http://take.ms/Iz7rd)

Reported in ticket: #1234099-zen

**Comment by roundhill** [comment]
This is expected behavior, the serif font is used for both preview and published note view.
