### ISSUE TITLE
orgmode support

### ISSUE THREAD

**Issue by kimim** [Automattic/simplenote-ios#208]
Shall we add org mode support as same as Markdown. It will make life easier for 
[simplenote2.el](https://github.com/alpha22jp/simplenote2.el) users, because orgmode is the premium note format for Emacs users.

**Comment by bummytime** [comment]
Thank you for submitting this feature request @kimim. Unfortunately, org-mode support is not something which is on our current roadmap. I'll leave this issue open, but I just wanted you to be aware.

**Comment by jleandroperez** [comment]
Adding a +1 vote for orgmode to our (internal) feature requests system.

Thanks for reaching out!
