### ISSUE TITLE
Alphabetise tag list

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#21]
It would be great to be able to sort the list of tags alphabetically

another request #2685197-t

Another request #2726533-t

Opened by @rachelsquirrel

**Comment by rantoncuadrado** [comment]
#43423423-zen

**Comment by gracie** [comment]
Also requested in #1211447-zen

**Comment by cademis** [comment]
+1 for this change. I understand this is by design cross-platform, however, I find myself manually ordering my tags alphabetically to allow me to find tags quickly (150+ tags)

**Comment by Shtalin** [comment]
Why it is open? I can sort tags

**Comment by jleandroperez** [comment]
Closing this one since there's an option to Sort Tags alphabetically.
