### ISSUE TITLE
SmartNews sharing doesn't include URL

### ISSUE THREAD

**Issue by Robertght** [Automattic/simplenote-ios#210]
From the user:

>Now on SmartNews, I click on share, choose Simplenote, the text of the article appears but no link. But if I share to iMessage, I get text and URL, not so on Simple Note.

[Video demo](https://www.youtube.com/watch?v=n6bbKm_9I6Y&feature=youtu.be).

Ticket: 1310546-zen

**Comment by jleandroperez** [comment]
Closing as cannot repro. iOS 14, SmartNews 8.10, Simplenote 4.27.

Please feel free to reopen if needed, thank you!
