### ISSUE TITLE
Feature Request: Show note tags on the left of screen

### ISSUE THREAD

**Issue by caimin-j** [Automattic/simplenote-ios#211]
From Jim in Atlanta, who describes himself as a "happy user":

> Observation: ‘long’ note entry doesn’t allow me access to the ‘Tag’ listing- gotta scroll all the way to the bottom to see the bar to view/edit tags.
> 
> Suggestion- why not show the tags assigned to a note via the ‘tags’ flyout on the left side of the screen? Maybe put a little indicator (asterisk?) next to each tag assigned to the current note. Allow the user to select/deselect tags assigned to the note in the right-side pane.

ZD: https://woothemes.zendesk.com/agent/tickets/1337550

**Comment by jleandroperez** [comment]
Closing this one *for now*, we'll be refreshing the UI soon-ish.

Thanks sir!
