### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by chantalcoolsma** [Automattic/simplenote-ios#214]
I found some issues in the translation of Simplenote for iOS. Checked localisable strings, but can't find them there.

1. When previewing a note, the header shows English strings:

![img_9526](https://user-images.githubusercontent.com/867632/44324212-3600d600-a455-11e8-8947-7aedfcc4391c.jpg)

2. The tags sidebar shows 'Edit':

![img_9528](https://user-images.githubusercontent.com/867632/44324244-5a5cb280-a455-11e8-8525-3f001fd8fbc9.jpg)

3. If I tap the info button at a note, the bottom section shows some strings which have no spacing (arrow) and one button with truncated text, as a new user I don't know what is says:

![img_9527](https://user-images.githubusercontent.com/867632/44324355-b45d7800-a455-11e8-85c8-74fc5dede79a.jpg)

4. If I tap to show the tags sidebar and then tap Settings, I see two strings which aren't translatable:

![img_9529](https://user-images.githubusercontent.com/867632/44324413-e373e980-a455-11e8-9128-70fab7a3ae00.jpg)

**Comment by jleandroperez** [comment]
1. Preview Strings are currently localized
2. Sidebar's Edit is also properly localized
3. Action Sheet clipping will be addressed soon (Tracked down in #457)
4. About is localized as well!

Tested in develop / Simplenote 4.16.

Thanks for helping us improve Simplenote!
