### ISSUE TITLE
Add support for dynamic type

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#22]
Allow users to increase the size of fonts in the app by changing the accessibility settings on their device at Settings > General > Accessibility > Larger Text.

t-62760, t-2493975

Opened by @rachelsquirrel

**Comment by gracie** [comment]
+1 in #3134071-t

**Comment by bummytime** [comment]
Update 5/13/2019: Dynamic type is not fully supported yet in the app.

**Comment by aheckler** [comment]
2395781-zen

**Comment by jleandroperez** [comment]
**Update 10/23/2019:**

Dynamic Type support has been fully added to:

- Authentication (Login / Signup) 
- Notes List
- Tags List
- Editor

Only pending is the `Info Sheet`, to be revisited via Spring Cleaning Mark II.
