### ISSUE TITLE
iOS app crashes on pasting large amount of text

### ISSUE THREAD

**Issue by gmdjango** [Automattic/simplenote-ios#225]
Large text files (not sure the number of lines, perhaps 2000..) the app crashes on paste. Even though iOS native Notes app can handle this paste operation. Sometimes (I guess depending on the size of the file) it is possible to close other apps running in the background and then the paste goes through. But if the file is large enough it crashes the simplenote app even if it’s the only app running on the device. If the app crashes the text is not pasted into the note.

**Comment by bummytime** [comment]
Thanks for the report @gmdjango. I just tested pasting a few large large text files (36,000-50,0000 words, 850-1000 paragraphs) into Simplenote 4.7.0 on iOS 12.2 and was not able to crash the app. 

I am going to close this issue for now. However, if you could provide some specific steps to reproduce the crash, we can reopen this issue.
