### ISSUE TITLE
Remove NavBar Hacks

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#23]
Since we're bumping up the deployment target, we may use UIKit's standard "Shrink Navbar" mechanism:

`navigationController?.hidesBarsOnSwipe = true`

Props to @frosty for pointing it out!

Opened by @jleandroperez

**Comment by jleandroperez** [comment]
Closing this one as wont fix. Reason: the current behavior is VERY custom, we're manually resizing the icons, not simply hiding the navigationBar.

🖖
