### ISSUE TITLE
Feature request: 3D Touch shortcuts 

### ISSUE THREAD

**Issue by Arc676** [Automattic/simplenote-ios#233]
Apple’s notes app includes 3D Touch shortcuts to create a new note, among other things. A similar shortcut with Simplenote could be quite useful. 

I might be able to work on this myself.

**Comment by jamesrisberg** [comment]
@Arc676 I'm interested in this as well, wanna chat about getting it done in the near future?

**Comment by Arc676** [comment]
@jamesrisberg Sure. How would you like to proceed?

I'm currently stalled on this from other work and the fact that I can't run this on my phone due to code signing issues (see screenshot) and the iOS simulator doesn't support 3D Touch so I can't test it on my Mac either.

Any solutions to either of these problems?

![screen shot 2018-11-03 at 22 18 23](https://user-images.githubusercontent.com/30745465/47957465-7c76c300-dfb6-11e8-9461-d7930260a69c.jpg)

**Comment by bummytime** [comment]
Closing this in favor of #26
