### ISSUE TITLE
Markdown Live Highlight

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#24]
#### Description:

Let's add a Live Markdown highlight, for basic markers, such as tiles, bold and italics.
#### Details:
- Add a markdown toggle to iOS info sheet
- No global setting for markdown keeping a per-note markdown setting, behavior will be: If last new note created has markdown, then next new note will be markdown enabled (markdown enabled = `systemTags` has `markdown`) 
- Live Highlight should only change the font style, and shouldn't perform any kind of text replacement in order to hide the "markers".

cc @fredrocious 

Opened by @jleandroperez

**Comment by bummytime** [comment]
Closing in favor of #305
