### ISSUE TITLE
Delay when entering passcode, typing, and app freeze 

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-ios#243]
This was reported on 1512590-zen

> Every time I open it it takes about 7 seconds to register that I want to enter my passcode - there’s a big delay in the typing as well, every 4th word or so it freezes and I have to wait 8 seconds to type again. This never used to happen, it’s started in the last month - I’m using the latest version but it started happening even before I updated. 

I'm not entirely sure if this is more related to the user system / device, as I'm not able to reproduce this, neither seems that we have had other similar reports. Any advice I can pass to the user would be appreciated.

#### Simplenote version
Simplenote v 4.6.5.

#### iOS version
iPhone 6. 
iOS 12.0.1.

**Comment by bummytime** [comment]
I am not able to repro this issue on iOS 12.2, Simplenote 4.7.0. Since we don’t have any other reports of this issue, I am going to close this for now.
