### ISSUE TITLE
Link Clicking/Editing can be sporadic 

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-ios#246]
Occasionally links don't seem to `Linkify` in the editor, and it can be hard to discover that you need to long-press to open a link in the browser.

Perhaps we can do something like Notes.app, it links urls when you open a note, but as soon as the editor receives focus all links are disabled in edit mode.

**Comment by jleandroperez** [comment]
Just a heads up Dan!. This used to be (and is the standard behavior):

```
Perhaps we can do something like Notes.app, it links urls when you open a note, but as soon as the editor receives focus all links are disabled in edit mode.
```

We've rolled out our own Linkifier because of performance issue reports. (The original issue should be in the legacy github repository!!)
