### ISSUE TITLE
Crash when tapping in-note links

### ISSUE THREAD

**Issue by michaelwexler** [Automattic/simplenote-ios#247]
#### Steps to reproduce

Using below to make a "table of contents":

```
# Table of Contents
1. [Example](#example)
2. [Example2](#example2)
3. [Third Example](#third-example)

## Example
## Example2
## Third Example
```

When viewing ios "preview" mode, tapping on the blue links to locations in the same note causes app to crash and close. 

#### What I expected
Tap on link, note scrolls to expected header.   

#### What happened instead
Crash and App closed

#### Simplenote version
Ios 4.6.5

#### iOS version
12.0.1

**Comment by bummytime** [comment]
Verified in Simplenote 4.7.0, iOS 12.2.

**Comment by michaelwexler** [comment]
Thanks for fixing!

**Comment by jleandroperez** [comment]
@michaelwexler thank **you** for helping us improve Simplenote!!
