### ISSUE TITLE
Add "Share" Details

### ISSUE THREAD

**Issue by rileybrook** [Automattic/simplenote-ios#252]
> The inherent problem is that the **- sharing options are only visible to the owner of the document -** especially on the iphone app. So, if you have lots of documents, some you own and some shared with you, **- on the iphone app there's no way to tell which notes are shared and which notes are not. -** On the web app, there is a little broadcast button to the left of the document that shows it is a shared document, but it **- still provides no way to tell who it is shared with.** 
>
>So, there is a usability "snag" that requires the simplenote user to know & remember, out of all of their documents, which are shared and who they are shared with. Most modern collaboration platforms making the sharing permissions transparent at the document level. In my case, if my wife could have looked at the note and seen that it was shared with me, we would have avoided this issue.
> 
> I understand that simplenote tries to keep things simple, but this is a hindrance to smart usability and will hamper the platform.

This seems more like General feedback than an enhancement request - but will post just in case.
[1604042](https://woothemes.zendesk.com/agent/tickets/1604042)

**Comment by jleandroperez** [comment]
Adding a vote for `Shared note Indicators` to our (internal) feature requests system.

Thank you for helping us improve Simplenote!!
