### ISSUE TITLE
Feature Proposal: Add an 'Dark at night only' option to the theme selection options 

### ISSUE THREAD

**Issue by iskandergaba** [Automattic/simplenote-ios#253]
I use Simplenote at different times of the day. While I prefer the Light theme during the daylight, I also like the dark theme during the night. A very common use case is the user, i.e. me, writing some notes while on the bed just before sleeping. In this case, the light theme kind of hurts the eyes and the dark one is much more eye friendly.

I propose adding a third option, Dark at night only, to the theme selection menu. If the user selects this option, the application will decide, upon start, on what theme to use depending on the time of day. Just like Twitter's application auto setting of night mode. I believe this is better than me switching back and forth between the themes.

While I have already [implemented this feature on the Android application](https://github.com/Automattic/simplenote-android/issues/581), I am not an iOS developer, and I do not have access to a Mac, so... no can do. Nevertheless, I believe this is one cool feature that iOS users should have as well just like Android users.

I did some research on the matter and apparently it is possible. I would also argue that the required modification is fairly simple. I think this would be a great first issue for new contributors.

@martinhering made an excellent implementation of this for his [InstaCast application](https://itunes.apple.com/app/instacast-core/id1083868334) and shared it online. Again, the code is really short and simple and easy to understand. It would be a waste not to add such a cool feature if the implementation is as easy. I hope somebody picks this up and works on it.

Below are the links you should look at:

https://martinhering.me/post/0/night-mode-for-your-ios-app
https://github.com/martinhering/ICAppearanceDaylightCalculator/tree/master

**Comment by jleandroperez** [comment]
Adding a vote for this feature in our internal feature requests system.

Thanks for reaching out, and apologies it took us a while to get back to you!
