### ISSUE TITLE
New note created when an existing note is deleted

### ISSUE THREAD

**Issue by drspock007** [Automattic/simplenote-ios#257]
#### Steps to reproduce
Issue was reported by a user: https://woothemes.zendesk.com/agent/tickets/1620499
We could not reproduce the steps: https://a8c.slack.com/archives/C03P63CP9/p1543998887071000

#### What happened instead

User message:

Which app do you need help with?: iOS

How can we help?: On my iPhone, each time I delete a note, a new "title" is created that

says "New note..." in bold typeface

This cannot be deleted, so that I have an ever growing stack of the tag "New note..." on my list.

If I delete a note on the desktop the same thing happens, but it only shows up on the iPhone.

**Comment by bummytime** [comment]
Could not repro in iOS 12.2. It’s possible this is related to a sync issue, but unsure at this point. Closing this issue for now - will reopen if needed.
