### ISSUE TITLE
Add 3D Touch Niceties to the App Icon

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#26]
We can add a 3D touch popup menu to the app icon. Ideas so far:
- New note
- Search

Would something like jumping straight to your most recent note or your top pinned note be useful?

"User suggested a 3D shortcut to create a new note or access the pinned ones

https://twitter.com/jssrea/status/656376061912031232"

Opened by @roundhill

**Comment by clclementsj** [comment]
I think all four of the suggestions are great ones (New note, Search, Most Recent Note, Top Pinned Note). These same selections would be useful in a widget as well.

**Comment by jleandroperez** [comment]
Closing in favor of #901
