### ISSUE TITLE
No text in note edit pane on iPad 11 2018

### ISSUE THREAD

**Issue by jonnymind** [Automattic/simplenote-ios#260]
I think the issue is critical, as it makes the app completely unusable on newer iPads

#### Steps to reproduce
1. Create a new note on iOS 12 / iPad 11
2. Or, edit an existing note
3.
4.

#### What I expected
To be able to Read the content of the note or write a new one

#### What happened instead
Text window is dead. No text nor cursor is displayed.
However, the text is taken if typed, although the window stays dead.

#### Simplenote version
4.6.7

#### iOS version
12.1.1

#### Screenshot / Video
It would be an empty window...

**Comment by jonnymind** [comment]
I think the issue is critical, as it makes the app completely unusable on newer iPads

**Comment by roundhill** [comment]
I think you may have run into this issue: https://github.com/Automattic/simplenote-ios/issues/268

Can you try closing the app (swipe it away from the app switcher view) and see if that fixes it?

**Comment by jonnymind** [comment]
I previously closed and reopened the app several times, but it didn't fix it. 
It seems that restarting the system did it.
I am under the impression that the combination of new hardware and OS was badly interacting with some widget, and some update pending at restart was sneaked in silently -- because the application UI itself looks somewhat slightly different.
Everything is fine now.
