### ISSUE TITLE
Changing theme isn't always applied correctly to the editor

### ISSUE THREAD

**Issue by frosty** [Automattic/simplenote-ios#263]
I can't consistently reproduce every time, but if I've already opened an editor view that contains checkmarks (a list), and then toggle the app's theme, the checkmarks often get updated using the old theme not the new theme. This results in black (hard to see) checkmarks using the dark theme, and white (invisible) checkmarks using the light theme:

<img width="413" alt="screenshot 2019-01-07 at 16 05 08" src="https://user-images.githubusercontent.com/4780/50778672-7b079680-1296-11e9-91d6-371dd93f761f.png">

I added a breakpoint in `- [SPEditorTextView processCheckLists]`, and confirmed that the `theme` being used was the old theme and not the new one. 

Simplenote 4.6.8, iOS 12.1

**Comment by bummytime** [comment]
Addressed in #266
