### ISSUE TITLE
Hebrew Language Interferes with Menu

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-ios#267]
When the language is set to Hebrew (which is RTL) the text of notes interferes with the menu options in Simplenote. 

![rtlsimplenote](https://user-images.githubusercontent.com/19782997/50920931-56cdc600-140c-11e9-8cde-9084b2e31a68.jpg)

This is related to #19 

User is using Simplenote 4.6.7 and iOS 12.1.2

Reported in #1690812-zen

**Comment by jleandroperez** [comment]
Closed via #460. Tags List got Autolayout, and RTL is now effectively being supported.

**Thank you Megan!!!**

![Simulator Screen Shot - iPhone Xs - 2019-10-23 at 01 11 43](https://user-images.githubusercontent.com/1195260/67356900-289c1b80-f532-11e9-998c-10ba4827f742.png)
