### ISSUE TITLE
New line lost when note open for editing

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#27]
Steps:
1. Create a new note and hit enter at the end of the note to add a new line.
2. Return to the list of notes and then open the note again and tap in the space that is the new line to paste some text.
3. Paste the text. 

It removes the new line and instead appends the pasted text to the line above.

ticketid=2370197, ticketid=2456303

Opened by @rachelsquirrel 

UPDATE: Also reported in #910736-zen 24th January 2018

**Comment by ashercantrell** [comment]
Possibly related? https://simplenotep2.wordpress.com/2016/09/11/tapping-on-a-new-line-in-simplenote-ios/

**Comment by charliescheer** [comment]
Was not able to repo

Tested on iPhone 8, iOS 14.3, SN 4.29

Closing.  If problem persists please feel free to open again.
