### ISSUE TITLE
Cursor jumps to end of note after viewing a long note

### ISSUE THREAD

**Issue by gracie** [Automattic/simplenote-ios#271]
#### Steps to reproduce
1. Create a note that's 200+ lines
2. Create another note that's long-ish - maybe ~150 lines
3. Add text to the end of the 200+ line note
4. Open the 2nd note that's shorter - you'll notice the note jumps to the end.
5. Edit the end of the 2nd note and then return to the original, longer note.
6. It jumps to the middle of that longer note.

#### What I expected
To load the top of the notes.

#### What happened instead
With long notes, the cursor jumps to whatever line you were on in one note for the new note selected.

#### Simplenote version

ios 1.3.8
#### iOS version

Reported in #1676813-zen.

**Comment by mgalbritton** [comment]
Another instance reported in #1698379-zen.
