### ISSUE TITLE
Issues with copying, cutting, and pasting text

### ISSUE THREAD

**Issue by mikeicode** [Automattic/simplenote-ios#279]
**User reported:**

> Since an update yesterday of the Simplenote iphone app, I am having a lot of trouble copying, cutting, and pasting text. I tried restarting the app, and completing re-starting my phone. I can cut and paste fine in other applications (e.g. text messages).

> It occassionally will work, but often when I try to double tap to highlight something it won't stay highlighted, and sometimes when I single tap the cut/copy/paste disappears before allowing you to select anything.

Issue was reported by a user: #1783877-zen

I couldn't reproduce the issue on my iPhone 7 using the same iOS and App version. 

We had the user try deleting and reinstalling the app but they still have the issue.

#### Simplenote version

4.6.8

#### iOS version

12.1.4 on iPhone 6S

**Comment by bummytime** [comment]
Unable to repro on iOS 12.2. Closing the issue for now, will reopen if needed.
