### ISSUE TITLE
"Search" instead of "Notes" for back button

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#28]
To make it even more clear, the back button should read "Search" instead of "Notes" so the user knows what to expect when they tap the button.

Also, the results text is off center at the bottom.

![img_1751](https://cloud.githubusercontent.com/assets/618551/10233550/b7cbc338-6854-11e5-93ed-0b4152aac903.jpg)

Opened by @drw158

**Comment by jleandroperez** [comment]
Fixed via #75. Props to @khoiln!
