### ISSUE TITLE
Cannot Highlight/Copy First Word of a Line

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-ios#280]
#### Steps to reproduce
1. Open a note in Simplenote.
2. Try to double tap to highlight the first word of the note.
3. See that it sort of jumps and won't highlight. 

#### What I expected
Double tapping the first word of the note would highlight the word and bring up options to copy/cut

#### What happened instead
The screen flashes the copy/cut options and the cursor jumps. The word is not highlighted

#### Simplenote version
4.6.8

#### iOS version
12.1.2

#### Screenshot / Video
https://cld.wthms.co/JuRxey

Also reported in #1784941-zen

**Comment by mgalbritton** [comment]
another report in #1791526-zen

**Comment by edequalsawesome** [comment]
Also reported in #1801450-zen
