### ISSUE TITLE
Text Selection Options Require Long Press Instead of Tap

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/simplenote-ios#281]
#### Steps to reproduce
1. Open a note.
2. Place the cursor where you'd like to select text.
3. Tap to display the Select/Select All options.

#### What I expected
When tapping within a text field, the Select/Select All options should be displayed as they do throughout the rest of the system.

#### What happened instead
Nothing is displayed. You must tap and hold or double tap in order to display the Select/Select All options.

#### Simplenote version
4.6.8

#### iOS version
12.1.4

#### Screenshot / Video

https://d.pr/free/v/5gHGIK

Note: I'm single tapping throughout all parts of the video, aside from when the text selection options display — the first time I double tap, the second time I tap and hold.

This was initially reported in 1792352-zen and I was able to reproduce it.

**Comment by darnelldibbles** [comment]
This appears to be a same issue reported by a user on Twitter:

https://twitter.com/ridogi/status/1097869854332325888/video/1

**Comment by roundhill** [comment]
Fixed in #282
