### ISSUE TITLE
Shared checklist "unchecking" causes app to crash on iPhone8 Plus

### ISSUE THREAD

**Issue by sheenalee4** [Automattic/simplenote-ios#288]
User reported that app crashes when unchecking previously checked items on a shared checklist. User reported that this does not happen on non-shared checklists.

#### Steps to reproduce
1. Created a shared checklist, accessed on iPhone 6, iOS v 12.1.4, and iPhone 8, iOS . v 12.1.2. Unable to replicate.

#### Simplenote version
4.6.8

#### iOS version
11.4.1

**Comment by jleandroperez** [comment]
Tested in iOS 12 + 13, Simplenote 4.14, closing as cannot repro. 

Please feel free to reopen if needed, thank you!!
