### ISSUE TITLE
Pressing Enter After Adding Asterisk Deletes Asterisk

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-ios#289]
#### Steps to reproduce
1. Create a note.
2. On a new line add an asterisk.
3. Hit enter after adding it.
4. Watch asterisk be deleted

#### What I expected
To be able to start a new line after an asterisk.

#### What happened instead
Asterisk is deleted.

#### Simplenote version
4.7.0

#### iOS version
12.1.4

#### Screenshot / Video

Video here https://cld.wthms.co/qjABqt

**Comment by bummytime** [comment]
Verified  on iOS 12.2, Simplenote 4.7.0.

**Comment by jleandroperez** [comment]
Closed as duplicated of #147.

Thank you all!!
