### ISSUE TITLE
Search bar stuck in cancel state

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#29]
To reproduce:
1. Tap search bar
2. Type a random word that produces no search results
3. Tap `Search`
4. Tap the `x` icon in the search field
5. The list view now shows the search bar in the cancel state

![img_1743](https://cloud.githubusercontent.com/assets/618551/10195678/6c115bac-6754-11e5-8262-2527aafc4bfe.jpg)

Opened by @drw158

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Still an issue in Simplenote 4.7.0, iOS 12.2

**Comment by jleandroperez** [comment]
Closed as cannot repro. Simplenote 4.12.

The entire SearchBar mechanism has been rebuilt *from scratch* :fire:

Thanks everyone!!
