### ISSUE TITLE
First word on new line sometimes can’t be highlighted in iOS app

### ISSUE THREAD

**Issue by citizenkade** [Automattic/simplenote-ios#290]
#### Steps to reproduce
1. Enter text.
2. Attempt to highlight the first word on any new line by double tapping the word.
3. Sometimes, the highlight will flash on, including the contextual menu options above, then immediately disappear, leaving the cursor in the position where the last tap occurred. (I’m unable to determine exactly what conditions cause this behavior to go away. It doesn’t seem to be related to the number of characters in the first word of a new line.)

#### What I expected

Expect the text to stay highlighted and the contextual menu to be available.

#### What happened instead

The highlight flashes on and immediately disappears. (Using the alternative press and hold method still works consistently).

#### Simplenote version

4.6.8

#### iOS version

12.1.4

**Comment by bummytime** [comment]
Unable to repro on iOS 12.2, Simplenote 4.7.0.

**Comment by mgalbritton** [comment]
@citizenkade this issue was fixed in 4.6.9. Can you try updating the version of Simplenote you are using and try again? 

See: #280
