### ISSUE TITLE
Checklists not available in iOS 10.3.3

### ISSUE THREAD

**Issue by tijosh** [Automattic/simplenote-ios#296]
#### Steps to reproduce
User reported in #1983321-zen that checklists aren't visible on their iPhone 5c running iOS 10.3.3 and the latest version of Simplenote.

#### What I expected
Checklists would be available in notes

#### What happened instead
No icon for checklists is visible:

#### Simplenote version
4.7.0

#### iOS version
10.3.3

#### Screenshot / Video
![Screenshot](https://cld.wthms.co/pkThxa+)

**Comment by bummytime** [comment]
Verified on 10.3.3 simulator — menu icon is missing.

**Comment by jleandroperez** [comment]
Initial implementation left out iOS 10 on purpose, and we'll be dropping support for 10 soonish.

Closing this one as won't fix.
