### ISSUE TITLE
Note Editor: Misspelled Words Cannot Be Corrected with a Single Tap

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/simplenote-ios#297]
#### Steps to reproduce
1. Type out some text within a note that includes a typo
2. Single-tap on the red-underlined word

#### What I expected
The "Replace…" suggestions to appear, allowing you to select from the suggestions in order to make a quick correction. This is expected behavior throughout the rest of iOS and can be seen within the Notes app, Messages, and just about any other system app with a text field.

#### What happened instead
Nothing.

#### Simplenote version
4.7.0

#### iOS version
iOS 12.2 on an iPad Air 2

#### Screenshot / Video
Here is a screen recording of the issue:

https://d.pr/free/v/nNaqWU

The last time I tapped on the misspelled word in the video, I used a double-tap instead, which displayed the contextual menu and allowed me to select "Replace…" and fix the typo. This can be used as a workaround for now, but the single-tap should be available as a shortcut of sorts.

User reported here: 1997067-zen

**Comment by zdenys** [comment]
Additional details shared by the user: `SimpleNote is no longer automatically correcting my mistakes, rather it’s leaving them as is (eg. if I’m typing quickly and I spell the term “different” as “diffrent”, SimpleNote no longer automatically changes it to the correct version of “different”, instead it just underlines it in red as a typographical error)`

**Comment by bummytime** [comment]
I verified this is indeed an issue on (at least) iOS 12.2

**Comment by Shtalin** [comment]
iPhone iOS 13 - all works

**Comment by msilbers** [comment]
reported in 2878415-zen

I recommended the workaround reported in the first comment.

**Comment by sarahfg** [comment]
In the above ticket they were using an iPhone Xr, ios 13.4.1, Simplenote 4.17

**Comment by jleandroperez** [comment]
Closed via #916. Our custom GestureRecognizers were interfering with iOS's innerworkings.

Shipping in iOS 4.26 (later this week).

**Please feel free** to reopen if needed. Thanks everyone!!
