### ISSUE TITLE
I got logged out on ios 6.1.3

### ISSUE THREAD

**Issue by fung1** [Automattic/simplenote-ios#303]
While editing my notes I got logged out and I can not login back again. 

### Expected
Use the app as usual

### Observed
Being sent back to login screen constantly. 

### Reproduced

> 1. Open app
> 2. Get a login screen
> 3. Fill in the login form and go back to login screen again.

Model|iOS Version|App Version
-|-|-|-
Iphone 4|IOS_6.1.3|3.3.5

**Comment by bummytime** [comment]
Howdy @fung1 → Our support staff can help you out. Contact them here: https://simplenote.com/contact-us/
