### ISSUE TITLE
History UI/UX not consistent with other Simplenote clients

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-ios#309]
Looking at the restore a note from history flow on iOS:

<img width="569" alt="Napkin 138 05-23-19, 1 46 48 PM" src="https://user-images.githubusercontent.com/154014/58278286-471ea080-7d61-11e9-92e2-0a8a9f16117d.png">

We can see it is different from the other platforms:

<img width="1067" alt="Napkin 139 05-23-19, 1 49 51 PM" src="https://user-images.githubusercontent.com/154014/58278448-aaa8ce00-7d61-11e9-84d6-ca0927a41707.png">

The major differences include:
1. The history icon is not in the top menu bar, it is buried in the info slide-up panel
2. The history sheet UI uses a horizontally scrollable date selector vs. a simple slider

Let's consider standardizing our approach on this.

/cc @SylvesterWilmott

**Comment by SiobhyB** [comment]
The fact that the feature's a bit hidden away was also noted by the user in 2117109-zen. They had to go searching for it after they accidentally deleted a lot of their note.

**Comment by jleandroperez** [comment]
Closing in favor of #762 (since the new ticket has mockups attached).

Thank you Bummy!!
