### ISSUE TITLE
Share menu not located in top menubar

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-ios#310]
Looking at the current location of the share button in the iOS app, we see it's inside the info sheet:

<img width="286" alt="Napkin 140 05-23-19, 2 05 20 PM" src="https://user-images.githubusercontent.com/154014/58279363-cf05aa00-7d63-11e9-8d2b-b573c2e1e0c7.png">

The other clients expose this on the menu bar itself:

<img width="745" alt="Napkin 141 05-23-19, 2 07 39 PM" src="https://user-images.githubusercontent.com/154014/58279503-302d7d80-7d64-11e9-8138-48b8d4362cad.png">

/cc @SylvesterWilmott

**Comment by jleandroperez** [comment]
Closing this one since, as per Spring Cleaning project, the Share button is not to be on the navigation bar.

Thank you Bummy!!

**Comment by SylvesterWilmott** [comment]
For clarification, this will be addressed at the time of the info sheet refactor in UI spring cleaning phase II
