### ISSUE TITLE
Preferences: Custom Font

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#32]
Add the ability to set a custom font, for note edition / visualization.

Opened by @jleandroperez

**Comment by cecilerainon** [comment]
Another request here: https://woothemes.zendesk.com/agent/tickets/995141

**Comment by aheckler** [comment]
2395781-zen

**Comment by jleandroperez** [comment]
I've added this to our feature requests. Thanks everyone!

**Comment by garretmh** [comment]
Is this being publicly tracked somewhere else now? Since you closed it despite it not being resolved.

**Comment by jleandroperez** [comment]
@garretmh I've moved this to an (internal) feature requests board. I'm afraid there is no ETA for this at the moment, nevertheless, adding a vote on your behalf.

Thank you for reaching out!

**Comment by DesiQuintans** [comment]
I have been waiting for years for Simplenote to add monospace fonts. Please finally do something about this!
