### ISSUE TITLE
Multi-line URLs are broken in exported PDF

### ISSUE THREAD

**Issue by crankygeologist** [Automattic/simplenote-ios#326]
There is an issue with URL link conversion when printed or saved to a PDF. Current functionality recognizes the text after "http://" as a link only until the end of the line on the resulting PDF page. Once the system inserts the new line symbol, the remainder of the URL text is still shown, but it is not the part of the link anymore — this is where the break in link formatting happens.

Steps to Reproduce:

1. Open a note containing a long, multi-line URL.
2. Tap on the Exclamation Point icon.
3. Tap Send, then Print.
4. In the Print share sheet, use the iOS system, two-finger expand gesture over the document preview to render the PDF.

Expected Results:

The full URL should apply to the entire length of linked text.

Actual Results:

The linked text is shown in the resulting PDF, but the URL after the first line is incomplete, which often takes the user to a 404 page for that domain.

Example long, multi-line URL:

http://www.jaycoowners.com/forums/f32/just-bought-jay-feather-2011-x20e-and-cant-turn-on-water-heater-3703.html#post71139

**Comment by charliescheer** [comment]
I took a look into this and it looks like this is an issue with the way that iOS is rendering the previews and detecting the URLS from there.

I was able to replicate the exact same behavior with Apple Notes by following the same  steps of zooming in on a print preview and then clicking on a multi line link.

I spoke with @leandroalonso about this and it isn't something that can be fixed on our end.

I'm going to close this issue.

**Comment by crankygeologist** [comment]
Thank you and @leandroalonso for looking into this. I filed a RADAR with Apple.

**Comment by charliescheer** [comment]
You're welcome!

**Comment by leandroalonso** [comment]
@charliescheer I guess you probably talked to @jleandroperez. :P

Pinging him here just in case there's any additional information on this issue. Sorry about the noise.

**Comment by charliescheer** [comment]
ach yes, sorry  :shame:
