### ISSUE TITLE
Add "Print" to the sharing sheet in the app

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#34]
A user request. They want to be able to use AirPrint - https://support.apple.com/en-us/HT201387

![print](https://cloud.githubusercontent.com/assets/7946521/9966964/bcd01d4c-5e37-11e5-9bca-14cccc0e8ecf.png)

2674754-t, 2700598-t

Opened by @rachelsquirrel

**Comment by jleandroperez** [comment]
Fixed via #70.

Props to @khoiln!!
