### ISSUE TITLE
No Preview When There is a Checklist in the Note

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-ios#344]
If you have a checklist in the note, you can't swipe left for a preview. 

### Expected
That you can preview a note with a checklist in it.

### Observed
Swiping left does not work.

### Reproduced
1. Create a note
2. Add a checklist
3. Try to swipe to see a preview of the note
4. Notice that you can't swipe at all

**Note**: This only happens in 4.8.0; not in 4.7.0

Link to video: https://cld.wthms.co/YtW7rY

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|7|12.3.1|4.8.0

**Comment by bummytime** [comment]
@mgalbritton I couldn’t tell from the video, but was markdown turned on for that test note?

I was able to see the preview in 4.8.0 on iOS 12: https://cloudup.com/cGQbO-EWmSs

**Comment by mgalbritton** [comment]
Closing this. Made the mistake of not having markdown on. Sorry!
