### ISSUE TITLE
Feature request: Add an option to disable data detectors on iOS

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#35]
A user has commented that data detectors can be quite annoying while writing notes and other text. Such as writing a date that automatically highlights blue.

An ideal feature in this scenario, would be to offer a preference of disabling data detectors throughout Simplenote.

Replicate;
1. Write a date, ex. 1/30
2. Hide keyboard.
3. Date becomes highlighted in blue.

Opened by @kurzee

**Comment by serabi** [comment]
A user is finding the data detectors in iOS make the application unusable for them. They would like to be able to disable data detectors throughout Simplenote. 

To replicate the problem, write an album or movie title as a note, hit return, and iOS turns the title into a clickable link that pops up a preview of an IMDB page.

**Comment by jleandroperez** [comment]
I've added this to our feature requests. Thanks everyone for the suggestion!
