### ISSUE TITLE
Tracks: Logging user_account_created event when we shouldn't be

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-ios#365]
I just came across this one while testing another issue. When attempting to sign up for a new account using an existing username, we still log `user_account_created` in tracks even though the signup attempt failed:

![tracks_issue](https://user-images.githubusercontent.com/154014/61407331-19f2f800-a8a3-11e9-83db-03fc50610b1a.gif)

[The code in question](https://github.com/Automattic/simplenote-ios/blob/6c7f2b0ed3258fff725a4e5ff90c466ecc6b38cd/Simplenote/Classes/SPLoginViewController.m#L204) even alludes to the problem: we are missing a `signup` callback.

**Comment by jleandroperez** [comment]
Closing as cannot repro (develop!). **Definitely** fixed (unknowingly) with the new Onboarding project... which is... all new code, yay!!

Thank you Bummy!!
