### ISSUE TITLE
Share extension: Unable to share URL's from certain apps

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-ios#377]
When sharing a URL from certain apps, the share extension UI is empty:

![simple_share_news360](https://user-images.githubusercontent.com/154014/62157029-dac89c00-b2d1-11e9-85b6-9fccb42f8e54.gif)

The issue is [this line here](https://github.com/Automattic/simplenote-ios/blob/develop/SimplenoteShare/Extractors/URLExtractor.swift#L119). Specifically `context.attributedContentText?.string` is sometimes `nil`. So the `guard` fails and the note ends up being blank.

To address this, if the above `guard` fails, lets create a new note just with the `url.absoluteString` (assuming it's not a file link).

### Reproduced
1. Open an article in the News360 app
2. Share the article to Simplenote (v4.9 and above)
3. Notice the UI is empty
4. Close the Simplenote share extension
5. share the article again, but this time to Notes.app
6. Notice the link is shared.

**Comment by jleandroperez** [comment]
Already addressed via #378. Housekeeping!!

Thank you Bummy!!
