### ISSUE TITLE
Remember location in tags list

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#38]
If you have a long list of tags and are viewing notes for a tag near the bottom when you return to the tags list, it takes you back to the top. A user would like it to remember your placement in the list to save having to scroll all the way down again.

ticketid=2288576

Opened by @rachelsquirrel

**Comment by Shtalin** [comment]
Already worked on my SE iOS13

**Comment by jleandroperez** [comment]
Closing this one since it's the current behavior. No need to change anything!
