### ISSUE TITLE
Make temp data like woocommerce provide to test plugin with real time.

### ISSUE THREAD

**Issue by sharazghouri** [Automattic/simplenote-ios#382]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

### What
***(Required)*** What is the feature you are requesting?  Add a concise description of the feature being requested.

I want to to add temporary data to or for initially add temporary data to test features of the plugin.

**Comment by jleandroperez** [comment]
Closing this one since Simplenote does not support plugins.

(Thank you!)
