### ISSUE TITLE
Enable Apple's spotlight search to search Simplenote notes

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#39]
User requested that we enable searching of Simplenote notes with Spotlight

63442-t

https://twitter.com/carosi/status/656518502778576896

https://twitter.com/user/status/688927948196462596

Opened by @rachelsquirrel

**Comment by kevmarsden** [comment]
Another request in 2942273-t

**Comment by jleandroperez** [comment]
Closed via #107 by @michalkosmowski 

Thank you Michal!!
