### ISSUE TITLE
Sign In with Apple

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#391]
### Details:
This is the SIWA's Main Issue:

- [ ] Display Apple's Sign In button with the `Continue with Apple` variant
- [ ] No interstitiall UI after SIWA
- [ ] Immediately trigger the SIWA flow if the credentials were already connected to the account
- [ ] Logging off from iCloud on the device should log you off from Simplenote
- [ ] Using SIWA should work, even if the accocunt had a password set before

**Comment by supernovia** [comment]
Noting a request here:
https://twitter.com/nativehyun/status/1185577973711163392

**Comment by jleandroperez** [comment]
Closing this one **for now**. Let's reopen if needed!!
