### ISSUE TITLE
iPadOS 13: Changing keyboard size temporarily clears editor

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-ios#396]
On iPadOS 13 Beta 5, we are seeing the following when changing the keyboard size while in the editor:

![ios13b5_keyboard](https://user-images.githubusercontent.com/154014/63052258-7a765480-bea4-11e9-8304-e0491e36b194.gif)

### To repro:
1. Open a note and start editing (using the soft key keyboard only)
2. Pinch the keyboard to make it smaller
3. Drag the keyboard around the screen (notice how the note text clears)
4. Expand the keyboard to full size
5. Notice how the text comes back

This issue is unverified on iPadOS 13 Beta 6...we should test it on there as well before digging in!

**Comment by bummytime** [comment]
This issue has been verified on iPadOS 13 beta 6. FWIW, I also tested keyboard resizing on other apps/editors to see if this behavior happens...and it does not.

So looks like we have a legitimate bug.

**Comment by Robertght** [comment]
@bummytime It doesn't happen on my end.

iPad Pro 2018 - iOS 13.1

**Comment by poynton** [comment]
issue confirmed on Simplenote 4.14.2 on iPad Air (3rd), iOS 13.3.

**Comment by erricgunawan** [comment]
I'm not sure if this is the same or related issue but Issue #606 mentioned using it on Split View, which brought me to here.

> I am writing this in my iPad. It seems that when I am writing a note in Split Mode (the other half is safari), Simplenote’s screen goes up up 70%. So it will leave a blank space 30% of the screen on the bottom. While the top portion will not be visible. 

From #2737046-zen

**Comment by jleandroperez** [comment]
Yup @erricgunawan confirming it's the same issue. Thanks for the report!!

**Comment by erricgunawan** [comment]
Another report from #2766713-zen :

> In a recent update I've noticed a change in the way notes are displayed on my iPad Pro, that means the top of the note (its title line and the next line) is out of view above the top of the screen. After a few lines of text are typed, the later lines become visible. It's as though the note is positioned too high in the 'viewing frame'. Dragging the note down with a finger reveals the top two lines, but they drift back up out of view when the drag is released. This seems to be consistent across notes, and in both portrait and landscape orientation.
The issue is not apparent on my iPhone, or on the Mac/web version. 

> This seems to happen in both split-screen and full-screen modes. 

Simplenote 4.15.1
iOS 13.2 
iPad Pro 10.5in.

**Comment by sarahfg** [comment]
Another similar report at #27678180-zen

 Simplenote version 4.15.1 on a 7th Generation iPad running iOS 13.3.1.

**Comment by sarahfg** [comment]
Another instance reported at #2843734-zen
