### ISSUE TITLE
Checklists: tap should toggle check box on iOS app

### ISSUE THREAD

**Issue by herrmanthegerman** [Automattic/simplenote-ios#398]
### What
In the iOS app, I can't toggle a checklist item with a simple tap gesture.

See also this comment:  https://github.com/Automattic/simplenote-electron/pull/1133#pullrequestreview-190517752: "On the mobile and Mac native apps we are simply disabling the checkboxes in the markdown preview (They are only checkable from the editor view)."

### Why
I think this is a major usability issue. Currently to toggle a checklist item, I have to delete the space in the [ ] and add an x to it. That's way too complicated than it needs to be. Think of the small touch screen keyboard on iOS while you are at the supermarket ticking off items of your shopping list. Instead on the web app, I just click on the check box to toggle the status of the task list item.

### How
I see two possible solutions.
Either:
Render checkboxes in edit mode and make them toggleable by a tap.
Or:
Make task lists toggleable in Markdown preview and modify note content when checkboxes are toggled.

### Note
I don't have an Android device available so I could not check if this request also applies to Android version of this app.

I'm running iOS 10.3.3 and Simplenote 4.9.

Thanks.

**Comment by mgalbritton** [comment]
Another request for this in #2282338-zen

**Comment by herrmanthegerman** [comment]
I think this might be an **iOS 10** issue rather than a Simplenote issue. 

What I observed could be a duplicate of or closely related to #296, i.e., on iOS 10.3.3 checklist's check boxes are rendered in preview mode only (where they can not be changed). In text/edit mode, I see "- [ ]" only.

Using an iPad running iOS 12, I the "- [ ]" is not shown in text/edit mode, instead a toggleable check box is shown (as expected / requested by this feature request).

**Comment by herrmanthegerman** [comment]
# iOS version example screenshots
## iOS 10, Edit mode

![IMG_3366](https://user-images.githubusercontent.com/26109745/63229270-0e2a8680-c1ff-11e9-94d6-7d1e31d74670.PNG)

## iOS 10, Preview mode
![IMG_3367](https://user-images.githubusercontent.com/26109745/63229275-15ea2b00-c1ff-11e9-89a7-0734e76b6641.PNG)

## iOS 12, Edit mode

![IMG_0520](https://user-images.githubusercontent.com/26109745/63229237-b0963a00-c1fe-11e9-937b-83bd46681c2b.PNG)


## iOS 12, Preview mode
![IMG_0521](https://user-images.githubusercontent.com/26109745/63229246-c3a90a00-c1fe-11e9-8b0f-4db930b658a2.PNG)

**Comment by jleandroperez** [comment]
Hello there @herrmanthegerman! Checklists aren’t fully supported in iOS 10. Additionally with iOS 13 being released in less than 30 days, we will no longer  support iOS 10.

Would it be possible to upgrade your device to iOS 11 or 12?

**Comment by jleandroperez** [comment]
Closing this one. Thank you all!
