### ISSUE TITLE
Creation date/time

### ISSUE THREAD

**Issue by Shtalin** [Automattic/simplenote-ios#399]
### What
Show date and time of note creation

### Why
After some time I don’t know when note been written ... I have hundreds of notes without time 

### How
Many ways... (best see to iOS standard notes app)
Or others...
  * When open note. In top right corner as background-small-grayed string...
  * Or bottom right(tag opposite corner)
  * Or by clicking info icon(worst way-many taps)

### Yes
We can write date into text...
We can go to desktop app -> modifies date.
We can something else....
But it’s not simple))) it near BUG thing for notesApp

**Comment by jleandroperez** [comment]
In the next release (Simplenote 4.16, out in march) we'll be displaying Creation or Modification date when:

- The app is in Search Mode
- The Sort Mode is relevant (you're sorting by Creation or Modificaiton date).

Closing via #649. 

Thank you for helping us improve Simplenote!
