### ISSUE TITLE
Lock app interface on demand

### ISSUE THREAD

**Issue by damamasss** [Automattic/simplenote-ios#417]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

### What.
When enabled Lock app add ability to block the application only at the touch of a button and on a timer. 

### Why 
When have Lock mode enabled and I often go to the application, the iOS blocking window (TouchID also) starts to annoy

### How.
Add in settings Manual Lock mode 
As in Telegramm. 
1. Timer to block from 1 minute to few hours, by default 1 hour. And if I close and then open App earlier than after 1 hour, then app start unlocked 
2. When lock mode enable and enable manual lock the upside add Lock button, and when I press on IT - app is Locked.

**Comment by charliescheer** [comment]
Added to feature requests
