### ISSUE TITLE
Markdown helper bar

### ISSUE THREAD

**Issue by damamasss** [Automattic/simplenote-ios#418]
### What.
Markdown helper bar In markdown mode as in Bear App 

### Why
Not everyone knows MarkDown language well. But big abilities of Markdown formatting 

### How
Bar in Markdown mode of note
[Screen of Bear note](https://images.app.goo.gl/SVJitYD9NyWuByC7A)

**Comment by jleandroperez** [comment]
Adding a vote to our (Internal) feature requests board for "Format Bar".

Thank you for reaching out!
