### ISSUE TITLE
App becomes unusable when notes number in thousands

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#42]
A user on an iPhone 4 reports that they cannot use the app with an account that contains thousands of notes. When they access a different account which contains just 4 notes it works perfectly. The troublesome account causes the app to freeze and sometimes displays a white screen of death just after signing in.

62976-t

"
@jleandroperez 
#### Update:

I've been trying to reproduce this issue (unsuccessfully) on an iPad Mini 1st gen (the slowest hardware i've got!).

Plus, i've been doing some profiling as well. This user has ~1600 notes in his main account, and the app's _ram_ usage never peaks above 5mb. Disk space shouldn't be an issue.

I'm sorry to say that (unless we can repro it, or get a crashlog at least) there's not much we can do.
"

Opened by @rachelmcr

**Comment by rachelmcr** [comment]
I think this must have been opened by @rachelsquirrel :)

**Comment by bummytime** [comment]
This issue is pretty stale. I’m closing it for now - if it is reported again we can re-investigate.
