### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by rachelwinspear** [Automattic/simplenote-ios#426]
Simplenote search is showing zero results when searching for a certain word in a note.

### Expected
When I search for a word, the number of results in a note should be shown and I should be able to see the results.

### Observed
It lists the notes containing the word, as expected. But, when the app opens a note, the matches all briefly flash blue (blue text, not background), then reports "0 results" at the bottom of the screen, with nothing highlighted.

### Reproduced
Screenshot: https://d.pr/free/i/VY9xTY

Make|Model|iOS Version|App Version
iOS Simplenote version 4.10

**Comment by rachelwinspear** [comment]
#2369040-zen

**Comment by jleandroperez** [comment]
Thank you @rachelwinspear !!! Fixed via #425 earlier today. We'll be shipping 4.10.1 ASAP with the hotfix.

Hope you're doing great over there!!
