### ISSUE TITLE
Push notifications for when shared notes are updated

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#43]
A user suggested this and I thought it sounded like a good idea.

"It would be nice to see at a glance which notes are being collaborated/shared. Also if shared notes are updated, a push notification would be useful."

63065-t

Opened by @rachelsquirrel

**Comment by Tele-Pet** [comment]
+1 
Push notification updates amongst collaborators would be awesome.

**Comment by kriskarkoski** [comment]
We got another request for this in 2906065-t

**Comment by jleandroperez** [comment]
I've added this to our feature requests. Thanks for the suggestion!
