### ISSUE TITLE
Within-Note Search: search provides zero results within notes

### ISSUE THREAD

**Issue by thehenrybyrd** [Automattic/simplenote-ios#430]
In Simplenote iOS 4.10, searching brings up a list of notes with the search term, as expected. However, after tapping one of those notes, instances of the search term are not highlighted and "0 Results" shows at the bottom.

### Expected
I expected (as in previous versions) instances of the search term to be highlighted, "N Results" to show, and tapping < and > to allow navigation between those terms.

### Observed
Instead, instances are highlighted very briefly and then not highlighted. "0 Results" shows, and < and > do nothing.

### Reproduced

> 1. Open Simplenote, make sure you're on 4.10.
> 2. Tap on the search bar and enter a search term that appears in your notes.
> 3. Select a note with that search term, and attempt to navigate through instances of the search term.

![snsearch](https://user-images.githubusercontent.com/15107387/65536986-42a5f800-deb9-11e9-970b-d66edfc7045f.gif)

*Reproduced on*: iPhone | SE |iOS 12.41 | Simplenote iOS 4.10
User report on iPhone 6 and iPad Air 2, in #2371575-zen.

**Comment by thehenrybyrd** [comment]
Another report of this in #2373094-zen.

**Comment by cameronvoell** [comment]
Another report #2375780-zen

**Comment by Robertght** [comment]
Found another report in #2364772-zen

**Comment by jleandroperez** [comment]
Closed via #425. It'll be out **super soon** in a hotfix release (4.10.1).

Thanks everyone!!!

**Comment by ChrissiePollock** [comment]
Another report on #2381746-zen
