### ISSUE TITLE
Selecting text in Markdown mode causes swipe gesture instead of selecting text

### ISSUE THREAD

**Issue by charliescheer** [Automattic/simplenote-ios#435]
If you are looking at the text of a note in markdown and tap on a word to select one word, then use the selection controls and slide them to select more text it is causing a swipe gesture instead of selecting more text, which causes the view to switch back to edit instead of markdown.

Check out this video to see this in action:
<a href="https://charlietestsiteblog.files.wordpress.com/2019/09/rpreplay_final1569618440.mp4" />video</a>

Notice that it starts to select more text and then changes to a swipe gesture

iOS 13.1
Simplenote 4.1

**Comment by msilbers** [comment]
Reported again for iOS and Simplenote 4.11

internal reference #2437417-zen

**Comment by msilbers** [comment]
Reported for iOS 13 and Simplenote 4.10.1
internal reference #2395897-zen

**Comment by msilbers** [comment]
reported for iOS 13.1.3 and iPhone SE

#2445688-zen

**Comment by Robertght** [comment]
#2454180-zen - this happened after the iOS 13 update.

**Comment by jleandroperez** [comment]
@Robertght Regression addressed via #518. Should be out in 4.13, thank you!
