### ISSUE TITLE
Replace AppbotX Dependency

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#439]
### Details:
We've retired the AppbotX dependency several years ago. Let's implement, instead, the new mechanism that allows users to rate our app, without leaving the main interface.

**Comment by dmsnell** [comment]
> the new mechanism

Is this built-in to iOS/AppStore?

**Comment by jleandroperez** [comment]
Yes sir! It's a new OS API... wired years ago in WPiOS. [PR Here!](https://github.com/wordpress-mobile/WordPress-iOS/pull/7369).
