### ISSUE TITLE
Polish letters with rare diacritics rendered incorrectly in Markdown Preview on iPad

### ISSUE THREAD

**Issue by thehenrybyrd** [Automattic/simplenote-ios#446]
### Expected
`ź`, `ż`, `ę`, `ą`, `ś`, `ć` will be rendered normally along with the other Polish diacritical marks.
This is how the text looks on app.simplenote.com:

<img width="529" alt="Screen Shot 2019-10-07 at 3 52 34 PM" src="https://user-images.githubusercontent.com/15107387/66313746-8bc76480-e91b-11e9-9c8f-c148b2ae0e3f.png">

### Observed
`ź`, `ż`, `ę`, `ą`, `ś`, `ć` are rendered incorrectly, being smaller than the rest of the letters.

![polishtextipad](https://user-images.githubusercontent.com/15107387/66314103-2fb11000-e91c-11e9-8f35-3c27ef773fd8.png)

The same occurs with Lithuanian extra diacriticals `č` `ž` `š` `į`, as in the phrase
`norėčiau žemuogės šią rytą nes jie labai skanį`

### Reproduced
1. On an iPad, open Simplenote and create a new note
2. Enable Markdown
3. Type some stuff in Polish, and include the following characters: `ź`, `ż`, `ę`, `ą`, `ś`, `ć`
4. Swipe left to Preview your note.

iPad (6th generation) | iOS 13.1 | Simplenote 4.10.1
cc: @melindahelt 
User report from #2403035-zen

**Comment by charliescheer** [comment]
Tested on iPad mini 5 and iPhone 8  (both iOS 14.3, SN 4.29) and wasn't able to repo.

If problem persist please feel free to re open
