### ISSUE TITLE
Restore button very close to Empty button and easily tapped acciedentally

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#45]
A user reports that when they view the Trash and swipe across the top-most note to restore it, the restore button appears just beneath the Empty trash button with little space in between. This makes it easy to completely empty the trash accidentally when all you want to do is restore a note from the trash. It might be better to move the "Empty" button to the other side of the search bar.

![unnamed](https://cloud.githubusercontent.com/assets/7946521/7978225/e0c914ac-0a8a-11e5-920f-bf82a7321cfc.png)

62952-t

Opened by @rachelsquirrel

**Comment by bummytime** [comment]
Closing for now.
