### ISSUE TITLE
Search bar overlaps note list

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-ios#452]
### Expected

I expect the note list to appear below the search bar at all times.

### Observed

When the app is first opened, the search bar overlaps the first note in the list.

The text from the notes is also visible behind the text in the search bar. This occurs even if you are actively doing a search and then scrolling the note list.

<img src="https://user-images.githubusercontent.com/8658164/66407865-d7dedb80-e9e5-11e9-8043-ee1f6c5085cd.PNG" width="50%">

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|XS|13.1.2|4.11.0.0 beta

**Comment by jleandroperez** [comment]
@rachelmcr Does this happen, on your end, 10 out of 10? is this at launch, without scrolling a tiny bit?

**Comment by rachelmcr** [comment]
This always happens after completely closing (force-closing) the app and then launching the app, without any scrolling (without touching the device at all).

If I pull down on the note list the first note will come out from underneath the search bar and look normal, but if I then force-close and launch the app again it'll return to that state.

**Comment by jleandroperez** [comment]
Closed via #454. Let's reopen if needed!

Thank you @rachelmcr !!
