### ISSUE TITLE
Move tags to top of screen

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#46]
A user reports that if they want to add tags to a particularly long note, they have to scroll all the way to the bottom of the note to see the tags. It might be helpful to move the tags to the top of the note or to put the tags in a floating bar across the bottom so you don't have to scroll down to see them.

62867-t

Opened by @rachelsquirrel

**Comment by jleandroperez** [comment]
We'll revisit the UI in the (upcoming) Spring Cleaning project. Closing this for now, thank you!
