### ISSUE TITLE
Links are hyper-aggressive when scrolling on iOS 13

### ISSUE THREAD

**Issue by marecar3** [Automattic/simplenote-ios#461]
### Reproduced
I’m noticing across a few apps, including yours, that iOS 13 causes links to be hyper-aggressive, so that if I my finger drags one as I scroll, instead of scrolling, it jumps to link in in-all browser. There must be a fix, because Medium, as an example, had this problem and resolved it, and many other apps never had it.

Make|Model|iOS Version|App Version
-|-|-|-
/|/|13|/

**Comment by KokkieH** [comment]
Another report in https://twitter.com/wear_here/status/1182811401192009730

**Comment by jleandroperez** [comment]
Closing this one since it's been fixed via #470.

Thanks everyone!
