### ISSUE TITLE
Add Simplenote to the Apple Watch

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#47]
We're getting lots of requests to add Simplenote to the Apple Watch.

62772-t, 2411510-t

Opened by @rachelsquirrel

**Comment by iamgabrielma** [comment]
+1: 3091551-t

**Comment by stevearends** [comment]
Has anyone figured out a work around yet?

**Comment by mgalbritton** [comment]
Another request in 1280065-zen

**Comment by jleandroperez** [comment]
Closing this one for now. Thanks everyone!

**Comment by ChrissiePollock** [comment]
Another request in #4645703-zen

**Comment by charliescheer** [comment]
This is probably best tracked on the ideas P2.  I have added a these ticket numbers to the existing request for the Apple watch.  internal-ref: p7rJFO-I-p2
