### ISSUE TITLE
Copy Text Not Working iOS 13

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-ios#472]
When trying to copy text while in iOS 13, it will allow you to double tap a single word but if you try to swipe to expand the selection, it disallows copying overall. So you can either select a single word or the whole text of the note. This happens when Markdown is on. 

### Expected
When I select a word to copy, I should be able to swipe and highlight more text. 

### Observed
You cannot select more than one word. You can either select the single word or the whole text.

### Reproduced
1. Open a note.
2. Double tap on a word to copy it. Then try to swipe to expand the text selection to copy.
3. Notice how the highlighting disappears and does not allow you to select anymore. 

Video

https://cld.wthms.co/11WDxO

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|11Pro|13.1.2|4.10.1

**Comment by msilbers** [comment]
Reported internally in #2414765-zen

iPhone 6S, iOS 13.1.2
iPadOS 13.1.2

**Comment by msilbers** [comment]
"The selection disappears. Not the text, but the blue selection highlight. It will deselect the words, and the selection handles will snap together at a seemingly random place. Then, the cursor will look like both handles were snapped together, as if no characters were selected (rather - a selection with a character width of 0). The cursor will operate normally, but with the circles that show the selection handles at the top and bottom. This won't go away until the app is closed and re-opened multiple times (closed through the multitasking selection, not just exited to the home screen)."

 iphone SE, most recent version of iOS (iOS 13 initial public release).

reported internally #2442223-zen

**Comment by jleandroperez** [comment]
Closedf via #518
