### ISSUE TITLE
Dark Mode - Feedback email field has "invisible" text

### ISSUE THREAD

**Issue by MeteC** [Automattic/simplenote-ios#474]
### Expected
When the dialog asking me for feedback pops up, I type my email address into the text field provided, and I should see the text I'm typing.

### Observed
I can't see the text. The text field text colour is no doubt set to "Default Label" so it's going white for Dark Mode, but the text field background is white -> invisible text.

I didn't take a screenshot - sorry! Also now I can't find out how to manually launch the feedback dialog (perhaps it's not possible? I searched in Settings..)

iPhone 8 - iOS 13.1.2

**Comment by codebykat** [comment]
Also reported in 2535915-zen
