### ISSUE TITLE
Rotating device while dragging sidebar open/closed causes layout issues

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-ios#495]
### Expected

I expect that if I _can_ rotate the device, it won't cause any layout issues.

### Observed

I can rotate the device while I am dragging the sidebar open/closed. When I do, it creates extra space at the top or bottom of the screen (depending on whether I'm going from portrait to landscape or vice versa).

### Reproduced

1. With the device in portrait, open the sidebar.
2. Start to drag the sidebar closed, and then rotate the device while the sidebar is partially closed (keeping your finger on the screen).
3. Note that now in landscape there's a space at the top of the screen.
4. Lift your finger and note that the space at the top remains there, even if you interact with the UI.

You can also repeat these steps, but starting with the device in landscape and rotating to portrait. This adds space at the bottom of the screen instead of the top.

<img src="https://user-images.githubusercontent.com/8658164/67398616-dd6e2100-f5a2-11e9-9a46-04c17f243bf7.PNG" width="50%">

<img src="https://user-images.githubusercontent.com/8658164/67398618-dd6e2100-f5a2-11e9-9003-42a7a050fb85.PNG" width="50%">

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPad Mini|13.1.2|4.12.0.1

**Comment by jleandroperez** [comment]
Closed via #502. Thank you Rachel!!
