### ISSUE TITLE
Touch ID not working when returning from a different app with Touch enabled

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#50]
1. Enable Touch ID for Simplenote and Dropbox. 
2. Choose "Save as Dropbox" in Simplenote to save the note in Dropbox.
3. Then return to Simplenote - the Touch ID is displayed but not usable. The app only allows input using the keyboard.

@SergioEstevao was able to reproduce this on an iPhone 6S

Opened by @rachelsquirrel

**Comment by KokkieH** [comment]
Another report via [Twitter](https://twitter.com/user/status/783917475054354432).

**Comment by bummytime** [comment]
Closing as we no longer support Dropbox.
