### ISSUE TITLE
Wonky Highlighting of Search Terms in a Note

### ISSUE THREAD

**Issue by sarahfg** [Automattic/simplenote-ios#501]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected
When searching through a note I expected all instances of that search term to be highlighted the same way.

### Observed
In the note the first instance is highlighted in black, the text turned white. After that blue is used, even if I cycle back through to the first word. It appears in blue

### Reproduced
1. Open Simplenote and type in a term that is used several times in one note
2. Tap the note in the search results. You will see the first black highlight
3. Tap the arrow in the lower right corner to go to the next instance of the serach term

First search term in note
![](https://testingdemosforothersin2018.files.wordpress.com/2019/10/img_0009.png)
(Image link: https://testingdemosforothersin2018.files.wordpress.com/2019/10/img_0009.png )

Second search term in note:

![](https://testingdemosforothersin2018.files.wordpress.com/2019/10/img_0010.png)
(Image link: https://testingdemosforothersin2018.files.wordpress.com/2019/10/img_0010.png )

Back to the first using the arrows:

![](https://testingdemosforothersin2018.files.wordpress.com/2019/10/img_0011.png)
(Image link: https://testingdemosforothersin2018.files.wordpress.com/2019/10/img_0011.png )

Device iPad, OS iPadOS13 App Version 4.10.1

Reported by user in #2433698-zen

**Comment by sarahfg** [comment]
This becomes an issue on Dark mode since the first highlight is difficult to see against the black background

![](https://cld.wthms.co/oV14gt+)

(Image link: https://cld.wthms.co/oV14gt )

Reported by user in #2462626-zen

**Comment by geriux** [comment]
Another user reported this issue in #2485489-zen Dark mode and the highlight of a search term is difficult to see.

**Comment by msilbers** [comment]
"The first search result always backlights the text in black - which, in case of one result in dark mode, is painful. However, on multiple results, when going from first result (black backlight) to second result (this beautiful blue tone), and back to first result - it turns blue."

iOS 12.1.4, Simplenote 4.14.2


Reported in #2649128-zen

**Comment by msilbers** [comment]
"I’ve noticed on my iPhone 11 Pro Max in dark mode that when I use search, the highlighted item is black also and isn’t highlighted as in light mode."

#2668158-zen

**Comment by jleandroperez** [comment]
Confirmed in Simplenote 4.15

**However!!** cannot repro anymore in Simplenote 4.16 (develop as of now). Please reopen if needed, thank you!!
