### ISSUE TITLE
Can't edit EOL for notes copied from Word for iOS

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#51]
I'm not sure if this is something we can fix but a user reports that they can't put the cursor at the end of a line where there's a line break (¶ in Word terms) for notes that have been copied from Word for iOS. I installed the app (Word) and can reproduce the problem. It works for lines that wrap to the next line but not when there's a line break.
#2631101-t

Opened by @rachelsquirrel

**Comment by jleandroperez** [comment]
Closing as cannot repro. iOS 14, Word 2.42.

Copying Word Documents isn't resulting in line break characters, in the Simplenote realm.

Please feel free to reopen if needed, thank you!
