### ISSUE TITLE
Adding emoji to notes is causing crashes for some users

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-ios#511]
### Expected
That adding emoji to notes will work normally (or not work at all if it's unsupported).

Awaiting more details.

### Observed
Two users have reported that adding emoji to notes causes the app to crash.

### Not Reproduced, but the users have described:
1. Open Simplenote
2. Add emoji to a note (various emoji have been reported)
3. The app crashes
4. Reopening the app still crashes it, until uninstalling/reinstalling Simplenote

Make|Model|iOS Version|App Version
-|-|-|-
iPhone | SE | iOS 13.1.1 | 4.11

reported internally in #2460813-zen and #2463456-zen

**Comment by rfaile313** [comment]
Reported in 2474206-zen

> When I write text and insert emoji, the application automatically closes. I open the application again and they immediately close.

**Comment by jleandroperez** [comment]
@rfaile313 would it be possible to get repro steps? (what emojis / app version / iOS version!).

We're currently working on this issue. Thank you!!

**Comment by rfaile313** [comment]
Will ask.

**Comment by sarahfg** [comment]
The emoji that caused the issue was 🌀

**Comment by rfaile313** [comment]
They're using an iPhone XS MAX and iOS 13.2

**Comment by geriux** [comment]
Another user reported this in #2493710-zen 

Mentioned it had issues using the new emojis.

**Comment by jleandroperez** [comment]
Fixed via #525, will be out in release 4.14

Thank you @sarahfg  + @rfaile313  + @msilbers + @geriux !!!
