### ISSUE TITLE
Share as PDF to iBooks Available But Does Not Work

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/simplenote-ios#517]
The option to share a note to Books is available, but does not work

### Expected
After clicking on the Send > Books option, a modal appears saying that a PDF is being created -- at that point, I'd expect to be sent to be sent to Books

### Observed
The modal appears, but I stay in Simplenote, and no new PDF is added to Books.

### Reproduced
1. Create a new note and add content to the note
2. Click on the (i) icon, and choose Send
3. From the app options, choose Books
4. Wait for Creating PDF modal to close
5. Go to Books app, verify no new PDF has been created

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPhone 11 Pro|13.2|4.12
Apple|iPhone Pad|13.2|4.11

Reported in #2471529-zen

**Comment by charliescheer** [comment]
Closing

**Comment by charliescheer** [comment]
Note that while this has been set to won't fix, there is a work around for anyone who still wants to export their notes from SN to a pdf in books.  To do this... From a note go to Options > Share > Markup.

That will create a PDF for you.  Then in markup if you exit the editing options there is a share button.  Tap on that and select books.
