### ISSUE TITLE
Syncing issues with long notes

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#52]
A user reports that when they copy and paste a very long note (> 75,000 words) into the app from Apple's Notes, it doesn't sync with the Mac app or their other iOS device. However the sync does work when they create a note with just a couple of lines. Furthermore when they paste another lengthy note into the Mac app the two iOS devices get a new blank note. 

I can't reproduce this. I've tried with a couple of very long notes and the sync works for me.

ticketid=2556477

Opened by @rachelsquirrel

**Comment by kevmarsden** [comment]
Another report of this issue in 2940662-t.  This user has some notes over 70,000 words.  

I was unable to recreate with a note in excess of 50,000 words.

**Comment by bummytime** [comment]
I also tried to repro this with no luck. Closing for now and will reopen if needed.
