### ISSUE TITLE
Swipe to see notes list in note not available

### ISSUE THREAD

**Issue by sarahfg** [Automattic/simplenote-ios#521]
### Expected
When I'm in a note I expected to be able to swipe from left to right to see my list of notes as in previous versions

### Observed
In iOS app version  4.12 this action no longer works

### Reproduced
1. Open a note on an iOS device using Simplenote 4.12
2. Swipe from left to right

Reported by user # 2472997-zen

**Comment by jleandroperez** [comment]
Closed via #512. Thank you Sarah!!

**Comment by sarahfg** [comment]
A user reported this is not fixed in 4.13 and I'm able to repeat this. If I'm in a note I'm still unable to swipe out of the note to see the notes list. #2503861-zen

**Comment by jleandroperez** [comment]
Hi there @sarahcada !! This is fixed in 4.14 (Internal beta), should be out in a week and a half.

Keeping the issue open just in case, just wanted to give you a heads up.

Thank you!!

**Comment by sarahfg** [comment]
Oh awesome! And @sarahcada probably can ignore this issue :-) I'm @sarahfg

**Comment by jleandroperez** [comment]
LOL Apologies @sarahfg (and -the other Sarah- !!!!) Autocomplete glitch!!!

**Comment by jleandroperez** [comment]
Closing this one. Please feel free to reopen if needed, cannot repro anymore in the latest AppStore build.

Thanks Sarah!!
