### ISSUE TITLE
Note List: Single Line Glitch

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#522]
The Body Preview is expected to display (way more) content. Multiple lines should collapse into a single one (space separated), in order to match the other clients).

h/t @SylvesterWilmott (Thank you sir!)

![Image from iOS](https://user-images.githubusercontent.com/1195260/68593459-46470b80-0474-11ea-8588-16cbfe685c32.png)

**Comment by dmsnell** [comment]
Noting the connection https://github.com/Automattic/simplenote-electron/pull/1647

We ran a new RegExp that matches N character per line and then iterated on that for each line in the preview. May or may not help here.

**Comment by jleandroperez** [comment]
Thank you D!!
