### ISSUE TITLE
Duplicate notes

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#53]
A user reports that occasionally the iOS app will replace one note with the contents of another. They know when this has happened because they end up with two identical notes and the missing note is in the history of one of them. I've seen this come up quite a few times in support but haven't been able to reproduce.

ticketid=2555644

Opened by @rachelsquirrel

**Comment by bummytime** [comment]
Closing for now - not able to repro and issue appears to be stale.
