### ISSUE TITLE
Text selection not working in notes on iOS

### ISSUE THREAD

**Issue by rfaile313** [Automattic/simplenote-ios#532]
Multiple user reports 

> Text selection does not work correctly. After selecting an entire word, it is impossible to select another area.

2503378-zen

This user's device(s): iPhone 7 iOS 12.3 Simplenote 4.12

> I can select one word but it fails as soon as I try to change the selection and therefore currently can’t copy more than one word (or the whole note) at a time.

2498236-zen

This user's device(s): iPhone X and an iPad (6th generation) with iOS 13.2.2 and Simplenote 4.12

----

Here's a video of the bug in action:

[Video Link](https://blogrudyfaile.files.wordpress.com/2019/11/rpreplay_final1574124453.mp4)

### Reproduced

I was **not** able to reproduce this bug using Simplenote 4.12 on my iPhone X using iOS 13.1.3 OR 13.2.3

Here's a video of my test: https://cld.wthms.co/UpRN34

**Comment by belcherj** [comment]
They should update to 4.13 when it is avail: https://github.com/Automattic/simplenote-ios/pull/518

This should be fixed.  Let's leave this open and close when reproduction is not possible on the new version.

**Comment by sarahfg** [comment]
There is a user on Simplenote 4.12 who reproduced this in iOS 13.2

**Comment by jleandroperez** [comment]
@sarahfg Should be fixed in 4.13 (PR #518), would it be possible to ask the user to update?

Thanks!!

**Comment by ErinCall** [comment]
I’m not the person who originally reported this, but I was having the problem in 4.12 and it’s fixed for me in 4.13. 

Many thanks to @jleandroperez for fixing the bug two weeks before I thought to report it! 😄

**Comment by jleandroperez** [comment]
Thank you for your feedback @ErinCall !!! Have an epic weekend over there!

**Comment by jleandroperez** [comment]
Closing as fixed via 4.13. Thanks everyone again!
