### ISSUE TITLE
Unable to add collaborators

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-ios#549]
Got a user report in #2536351-zen that collaborators can no longer be added on the iPad with version 4.14. I have reproduced this on iOS 13. Whether or not I allow access to Contacts, there is simply a blank box displayed without a way to add new collaborators:

![IMG_432DF3268D6C-1](https://user-images.githubusercontent.com/52152/70191306-30acb680-16ad-11ea-89bb-4343e94db4e5.jpeg)

**Comment by jleandroperez** [comment]
Closed via #550. Thanks Kat!!
