### ISSUE TITLE
Problems when typing Korean characters as a tag

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#55]
A Korean user reports that when they type in the tag - 한글 - the app changes it to ㅎㅏㄴㄱㅡㄹ 

I've verified this with @gracejiyoung 

ticketid=2543059

"Similar problem happens with Japanese characters which may be related. The user inputs a Japanese letter and a number shows up on the screen instead. #2681786-t"

Opened by @rachelsquirrel

**Comment by kristarella** [comment]
Also reported in #2755474

**Comment by kristarella** [comment]
And #3164734-t

**Comment by rachelsquirrel** [comment]
Also reported as an issue in the Electron app #831214.
