### ISSUE TITLE
Cannot click links while in editor mode

### ISSUE THREAD

**Issue by belcherj** [Automattic/simplenote-ios#555]
### Expected
While in editor mode links are not clickable 

### Observed
They should be clickable

### Reproduced
1. Add a link to a note with markdown enabled
2. Try to click on the link

 iOS 12.4.3|Simplnote 4.14

**Comment by jleandroperez** [comment]
Closing this one since it's by design: links aren't clickable while the keyboard is onscreen.

As soon as the keyboard is dismissed (top right button), the Linkifier is enabled, and links are clickable.
