### ISSUE TITLE
Stability: Crash at Launch

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#556]
### Details:
We've been getting several reports of a (quite random) crash at launch. Goal of this ticket is to track all of the feedback we could gather.

**Comment by rfaile313** [comment]
User report in 2549222-zen

Gathering information: iOS Version, Device, etc.

**Comment by michaelwexler** [comment]
Just to add: crashes after displaying list of notes on iPhone X, iOS 13.2.2, Simplenote 4.14.1 (latest at this time).  Cell or Wifi makes no difference.  Restarted device, still crashing.

On my iPad, 4.14.1 works fine.  iPadOS (iOS?) 13.2.2

**Comment by michaelwexler** [comment]
As followup, when I deleted the app, and reinstalled (going though first time login), the app now appears to work on the phone.  Perhaps a bug in how it's reading cached notes or something?

**Comment by jleandroperez** [comment]
Closed via @557.

Thanks **Everyone** for the feedback, we'll be releasing a hotfix shortly!! (4.14.2)
