### ISSUE TITLE
Entire note sent as subject when sent via Gmail app

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#56]
If you send a note via email using the Gmail app, the entire note is added to the subject line. It doesn't happen with the native email app is used.

Steps:
1. Open a note.
2. Tap the "i" icon then Send.
3. Choose Gmail and email the note to yourself.

ticketid=2547811

Addendum to this: the user requests that we make the first line of the note the subject which is not what currently happens in the native email app.

Opened by @rachelsquirrel

**Comment by mgalbritton** [comment]
Another report here: #1359308-zen.

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Still an issue in Simplenote 4.7.0, iOS 12.2:

<img width="872" alt="Napkin 135 05-14-19, 3 49 58 PM" src="https://user-images.githubusercontent.com/154014/57731300-f8398280-765f-11e9-8886-c11815157ff6.png">

**Comment by jleandroperez** [comment]
Closing as cannot repro. Simplenote 4.27, iOS 14.

Thanks everyone!!
