### ISSUE TITLE
[Translation] German - the word for "Trash" doesn't translate. 

### ISSUE THREAD

**Issue by ooottttooo** [Automattic/simplenote-ios#566]
### Expected
When left-dragging a note, the Word "Löschen" should appear. 

### Observed
"Trash-verb" is shown

### Reproduced
switch to German language
go to list of notes
swipe left

Changing line 175 in https://github.com/Automattic/simplenote-ios/blob/develop/Simplenote/de.lproj/Localizable.strings should fix this:
`"Delete" = "Delete";`
to
`"Delete" = "Löschen";`

**Comment by charliescheer** [comment]
This is the same problem as https://github.com/Automattic/simplenote-ios/issues/564

The translation problem for the trash button is happening on all non English languages.  Closing in favor of 564
