### ISSUE TITLE
Issues with Chinese input when adding Tags

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#58]
Tested on iOS 9.2 for iPhone 4S, and iPad.

Chinese input works fine to write notes, but when adding Tags, the language input no longer correctly processes the input. Web app is OK, but not iOS app.

This applies to "Chinese (Traditional)", and "Chinese (Simplified)".

To reproduce:
- in iOS, go to Settings > General > Keyboard > Keyboards, add "Chinese (Traditional or Simplified) - Pinyin"
- in Simplenote, in the notes section, type "yingyu" . The romanized Chinese correctly displays as "yingyu", with the suggestion of Chinese characters:
  ![img_1920_](https://cloud.githubusercontent.com/assets/15944096/12551138/56150384-c3a3-11e5-8921-ef1d24da00e1.png)
- in the Tags, type "yingyu", and as soon as you finish typing it, extra characters appear:
  ![img_1921](https://cloud.githubusercontent.com/assets/15944096/12551139/57fbdd62-c3a3-11e5-93b2-faef58d5ff4c.PNG)
- pressing backspace adds some random characters
  ![img_1922](https://cloud.githubusercontent.com/assets/15944096/12551140/59f8e376-c3a3-11e5-9a99-f93816be05c5.PNG)

Tested with other words, and the input consistently fails. For additional testing, you can try another two-characters word,["diannao" for 电脑](http://www.mdbg.net/chindict/chindict.php?page=worddict&wdrst=0&wdqb=diannao). In the notes, it'll be OK, but in the Tags, it will generate a garbled strings of letters.

Copying/pasting Chinese characters to the Tags will get added OK.

Also tested with the keyboard "Chinese (Traditional or Simplified) - Handwriting".
- In the notes, the handwritten sinogram is correctly recognized
  ![img_1923](https://cloud.githubusercontent.com/assets/15944096/12551769/c0f4ed0a-c3a7-11e5-947f-9917f816ff7c.PNG)
- in the Tags, the handwritten sinogram generates different symbols.
  ![img_1924](https://cloud.githubusercontent.com/assets/15944096/12551772/c74e11ea-c3a7-11e5-8a2b-c43ac428194f.PNG)

Let me know if more details or clarifications are needed.
#2503256-t

Opened by @formosattic

**Comment by rachelsquirrel** [comment]
I've got a report of this same issue happening in the Electron app. 

#808832-zen

**Comment by KokkieH** [comment]
A report again on [Twitter](https://twitter.com/deepjia/status/936417443651584000) today.

**Comment by msilbers** [comment]
It looks like this is an issue with Japanese as well, possibly all CJK, reported in #1568851-zen

"If you enter tags in Japanese with iOS application, characters that are not entered will be entered."

**Comment by roundhill** [comment]
Should be resolved via https://github.com/Automattic/simplenote-ios/pull/259

**Comment by bummytime** [comment]
Closing — fixed in #259
