### ISSUE TITLE
Add Tweet to note when shared with sharing sheet

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#59]
If you open the Twitter app and share a Tweet with the iOS sharing sheet, it would be good if it also included the text from the Tweet in addition to the link. When you share a Tweet from Safari, the text from the Tweet is included. But this doesn't happen with the Twitter app and Tweetbot.

ticketid=2498471

Opened by @rachelsquirrel

**Comment by jleandroperez** [comment]
Closing this one since the Share Sheet now works from Twitter.

Thank you all!!
