### ISSUE TITLE
Text Selection Not working with Keyboard Selection

### ISSUE THREAD

**Issue by sarahfg** [Automattic/simplenote-ios#593]
### Observed

1. Launch Simplenote
2. Tap on a note
3. Tap on the notes contents to bring up the keyboard
4. Enter "cursor mode" by pressing and holding on the spacebar
5. Enter "selection mode" by tapping with another finger on the keyboard
6. Make a selection
7. Release your fingers
8. Tap on the selection
 
### Actual Behavior: 
- The selection disappears
 
### Excepted Behavior:
- The text menu appears

### Reproduced
Make|Model|iOS Version|App Version
Apple| iPhone 11 | iOS 13.3 |4.14.2
Apple| iPhoneX | iOS 13.3 |

User Reported #26542890-zen

**Comment by bummytime** [comment]
Verified on iOS 13.3:

![simplenote_selection](https://user-images.githubusercontent.com/154014/73020166-b108b180-3dea-11ea-9a97-6ee91172b3e0.gif)

**Comment by jleandroperez** [comment]
Closing as Cannot Repro. Simplenote 4.27 / iOS 14.

We've recently overhauled the GestureRecognizer handlers, so this was definitely fixed as a side effect.

Thanks everyone!
