### ISSUE TITLE
Scrolling quirk

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#60]
This user has created a video to explain the issue. When moving the cursor with your finger, the screen starts to scroll when the finger is about halfway through the text area - not close enough to the keyboard to be normal behavior:

https://www.dropbox.com/s/qkxn3imoq9imj1a/IMG_0380.mp4

Ticket: 2473154-t

Opened by @shawnajean

**Comment by bummytime** [comment]
Closing this issue because of age — will re-open if needed.
