### ISSUE TITLE
Issue with Simplenote When Using Floating Keyboard on iPad

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/simplenote-ios#606]
When working on a note with Simplenote in Split View, while the keyboard is in floating mode, if you move the keyboard, the content of the note is no longer visible.

(I also just verified this happens with the floating keyboard when Simplenote is the only window open as well, so this is an issue with the floating keyboard in general.)

### Expected
That the note would remain in view

### Observed
The note's content was no longer visible, but was visible if I left the note and went back into it

Video of the issue is available here: [https://d.pr/v/JoPCDz](https://d.pr/v/JoPCDz)

Make|Model|iOS Version|App Version
-|-|-|-
iPad Pro|MTFL2LL/A|13.3|4.15
iPad Pro|MU202LL/A|13.3|4.12

---
Originally reported in #2661608-zen

**Comment by msilbers** [comment]
reported in #2672293-zen on iPad
awaiting more details

**Comment by jleandroperez** [comment]
Closing as duplicated of #396.

Thank you all!
