### ISSUE TITLE
New account contains a note from old account

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#61]
A user reported that they were asked to sign into the app which doesn’t normally happen and because they couldn’t remember the original email address on the account, they created a new account but one of the notes from the original account was in the new one and editable. They’ve since deleted the new account because they remembered the old email address. I can’t reproduce it.

ticketid=2440642

Opened by @rachelsquirrel

**Comment by bummytime** [comment]
Closing because we are not able to repro.
