### ISSUE TITLE
History Ignores Version 1?

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#62]
I've been messing around with note history in simplenote-android, and noticed in iOS that it doesn't appear to show the first revision of the note in the history view. In most cases, the first revision is usually blank so perhaps this was intended?

Opened by @roundhill

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Not seeing this issue in Simplenote 4.7.0, iOS 12.2. Closing.
