### ISSUE TITLE
Tags: allow filtering all notes without tags

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#63]
Currently, it's easy to find notes that are tagged, however it isn't possible to find "untagged" notes.

A user reported that they can find untagged notes in the web app by searching “tag:untagged”, but it isn't possible to do the same on any of the apps.

ticketid=2403989

Opened by @dcoleonline

**Comment by lancewillett** [comment]
+1

This is my most used missing feature from other notes apps, like Notational Velocity. For my GTD flow I review all notes, say once a week.

I usually start with untagged, and tag them or take action. With Simplenote it's hard to find untagged notes, so I spend a lot of time paging through one by one.

**Comment by lancewillett** [comment]
Suggested by a user in 3096496-t

> Can you add a default "un-tag" category for notes that do not have any tags? Sometimes I forget adding a tag and its difficult to find it using the "All Notes" category.

**Comment by lancewillett** [comment]
Oh! I didn't know about `tag:untagged` in web interface. Dang! That's perfect.

**Comment by jmpace** [comment]
Is this still being worked?  This would be a great feature for the Mac desktop app.

**Comment by bummytime** [comment]
On android, this exists:

<img width="260" alt="Napkin 142 05-23-19, 2 17 43 PM" src="https://user-images.githubusercontent.com/154014/58280228-b8605280-7d65-11e9-93b6-d17bb1014fdb.png">

**Comment by janpio** [comment]
> Oh! I didn't know about `tag:untagged` in web interface. Dang! That's perfect.

`tag:untagged` unfortunately doesn't seem to work any more.

**Comment by jleandroperez** [comment]
Implemente via #467 in release 4.12. Thanks everyone!!
