### ISSUE TITLE
Dark Mode: Add dark mode to startup screen

### ISSUE THREAD

**Issue by KokkieH** [Automattic/simplenote-ios#632]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

### What
User requests that we add dark mode support to the app's launch screen as well.

### Why
If opening the app at night, the initial screen is very bright before it switches to dark mode in the notes view.

Requested via [Twitter](https://twitter.com/ZevEisenberg/status/1226713878538702849)

**Comment by jleandroperez** [comment]
Closing in favor of #478.

Thank you sir!
