### ISSUE TITLE
iPad: Split Keyboard Weirdness

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#64]
A user reported this UI glitch, on iPad devices, with Split Keyboard.

Notice that the word `Tomatoes` gets vertically cut.

![img_0185](https://cloud.githubusercontent.com/assets/1195260/10941745/8f5bab50-82eb-11e5-8040-0db5adcc2d7b.png)

Opened by @jleandroperez

**Comment by bummytime** [comment]
Note: this is **not** an issue on the iPad pros as their keyboards do not split. Short video of the issue on the 12.2 sim:

![split_keyboard](https://user-images.githubusercontent.com/154014/57656029-ed69e980-759c-11e9-9309-df61b3e27a1a.gif)
