### ISSUE TITLE
Sync'ing Settings

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#65]
#### Web app settings:

Sorting: Sort By: Modified/Created/Alphabetically Order: Descending, Ascending
Preview lines: 0 - 4
Tab Key Behavior (web only): Tab => Indent? yes/no
#### iOS app settings:
- Sort notes alphabetically: yes/no 
- Condensed note list: yes/no 
- Dark theme: yes/no

**Proposed Bucket:** prefs

There may be multiple objects in the bucket corresponding to different device class
#### Suggested object names/device classes:
- default 
  This is the one we will create for everyone, the web app might use this as well.
- ios-iphone 
  For iPhones, iOS will create this and maintain iOS-specific settings here (the ones prefixed with ios-)
- ios-ipad 
  For iPads, iOS will create this and maintain settings here (so users can have a separate ipad/iphone profile)
- android-phone 
  For android phone devices
- android-tablet 
  For android tablet devices
#### Details:

When modifying a setting, if modifying a global setting, modify the default object, if modifying a device-class specific setting, create or modify the specific object, like ios-iphonefirst

When reading a setting, read the default object and apply whichever settings are applicable for your device, then if it exists, read your device-class specific object, (iphone will look for ios-iphone in that bucket, ipad will look for ios-ipad), and apply the device specific settings from that object (the ones prefixed with ios- if you are an iOS device)

cc @fredrocious (YES this is a rip off from your shared note, minus the TouchID setting)
## 
#### Sample JSON Payload:

```
{
"sort_by" :  possible_values( "modified", "created", "alpha" )
"sort_order" : possible_values( -1, 1 ) (descending, ascending)
"markdown" : possible_values( false, true )

"web_tab" : possible_values( false, true )
"web_preview_lines" : possible_values( 0 - 4 )
"web_theme" : possible_values( "default" )

"ios_preview_lines" : possible_values( 0 - 4 )
"ios_theme" : possible_values( "default", "dark" )

"android_preview_lines" : possible_values( 0 - 4 )
"android_theme" : possible_values( "default", "dark" )
"android_font_size" : ?
}
```

Opened by @jleandroperez

**Comment by bummytime** [comment]
Ref: #204

**Comment by jleandroperez** [comment]
Added to the list of Feature Requests. Thanks eeeveryone!
