### ISSUE TITLE
Remember and restore cursor position per note

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#66]
If you're working on large notes and are switching back and forth between them, the cursor position seems to just stay at where it was in the previous note.

It'd be handy if we could store the last cursor position for a note and restore it when the note is loaded again.

Opened by @roundhill

**Comment by rachelsquirrel** [comment]
I've got a report of the cursor position moving when switching between apps. This is happening on an iPad Mini running 11.2.2. I can't reproduce this on my iPad. It always returns to the same position in the note.

Requested in #894904-zen

**Comment by synora** [comment]
Here is the requested screen recording from https://woothemes.zendesk.com/agent/tickets/894904.

https://drive.google.com/a/helpingpeoplesucceed.org/file/d/1JPMlhYjcxQ5-DrqUReyFLREax35lf_9R/view?usp=drive_web

**Comment by mgalbritton** [comment]
Another report of it here:
https://woothemes.zendesk.com/agent/tickets/1455565

Was able to replicate as well.

**Comment by jleandroperez** [comment]
I've added this to our feature requests. Thanks everyone!
