### ISSUE TITLE
Line spacing: Recent iOS app update increased line spacing, request to restore this

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/simplenote-ios#669]
This is a user's feature request in 2306494-zen

### What

Here is the user's request:

>The most recent update for iOS seems to have significantly increased the line spacing within each note, please consider reverting it back to how it was before, or at least decreasing the line spacing a bit because it has almost doubled the length of each note!

### Why

The changes to line spacing have unnecessarily increased the length of notes in the iOS app.

**Comment by jleandroperez** [comment]
Closing in favor of #480, details on new Editor Metrics there.

Thanks everyone!
