### ISSUE TITLE
Decouple SPTransitionController

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#67]
**SPTransitionController** now might return a `SPInteractivePushPopAnimationController` instance, to handle the Push from Editor to Preview.

Let's improve this, by adding a third class that would contain the two `AnimationControllers`, and return whatever is required, accordingly.

(Possibly closed)

Opened by @jleandroperez

**Comment by jleandroperez** [comment]
Closing this one **for now**. We'll revisit all the things in the upcoming Spring Cleaning project!
