### ISSUE TITLE
Link highlighting is gone after viewing History

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-ios#670]
### Expected

I expect links in the editor to be highlighted in blue.

### Observed

After viewing the History for a note, the blue highlighting is gone for links and they appear with a regular text color.

### Reproduced

1. Create or open a note with at least one link.
2. In the editor, note that the link text is highlighted in blue.
3. Tap the (i) button in the top right and select "History..."
4. Notice that the blue highlighting is gone and the link has a regular text color.

Screencast here: https://cloudup.com/cSRbXcFcXAQ

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPad Mini|iPadOS 13.3|4.16.0.0 TestFlight beta

**Comment by jleandroperez** [comment]
Closing as Cannot Repro. Simplenote 4.27 / iOS 14.

We've recently overhauled the History slider, this was definitely patched up as a side effect.

Thanks everyone!
