### ISSUE TITLE
Passcode prompt can be misaligned on iPad

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-ios#671]
### Expected

I expect the passcode prompt `_ _ _ _` to be center aligned on the screen.

### Observed

When I am confirming my passcode to turn it on or entering my password to turn it off, the passcode prompt `_ _ _ _` is aligned left of center.

I only saw this on my iPad Mini, not on my iPhone XS.

### Reproduced

1. While logged in, open Settings.
2. Select Passcode.
3. On the Set Passcode screen, notice that the prompt `_ _ _ _` is center aligned under the text. Enter a passcode.
4. On the next screen to confirm your password, notice that the prompt `_ _ _ _` is _not_ center aligned. Enter your passcode again to confirm it.
5. Background the app.
6. Launch the app again and enter your passcode (notice that the prompt `_ _ _ _` _is_ center aligned here).
7. Go to Settings and select Passcode again.
8. Notice that the prompt `_ _ _ _` is _not_ center aligned.

<img src="https://user-images.githubusercontent.com/8658164/75350282-21996700-589e-11ea-9557-99a6e991f4f6.PNG" width="50%">
<img src="https://user-images.githubusercontent.com/8658164/75350274-1d6d4980-589e-11ea-86b5-e8b12c3e6867.PNG" width="50%">

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPad Mini|iPadOS 13.3|4.16.0.0 TestFlight beta

**Comment by charliescheer** [comment]
Same issue reported in #126

**Comment by rachelmcr** [comment]
Ah, thanks for catching that! Closing this as a dupe.

**Comment by charliescheer** [comment]
YW.  I had made a PR for this a few days ago, which is the only reason I knew about the older issue report ;)
