### ISSUE TITLE
Search: Tag search returns notes with partial tag match

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-ios#672]
### Expected

When I search for a tag (using the `tag:` syntax) I expect to only get results for notes with an exact tag match.

### Observed

I get results for notes with a partial tag match, e.g. searching for `tag:test` returns notes with the tag `testing` even if they don't have the tag `test` (instead of only notes with the tag `test`).

### Reproduced

1. Create a tag `test`.
2. Create a tag `testing`.
3. Add the tag `testing` to a note (and _don't_ add the tag `test` to it).
4. Search for `tag:test`. Notice that your note with the tag `testing` is in the search results.

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPad Mini|iPadOS 13.3|4.16.0.0 TestFlight beta

**Comment by jleandroperez** [comment]
Closed via #673. To be released in the (next) internal beta.

Thank you Rachel!!
