### ISSUE TITLE
List-depth cutoff

### ISSUE THREAD

**Issue by QuinRider** [Automattic/simplenote-ios#677]
### Expected
Nested lists (bulleted) should render fully regardless of exceeding the devices width!

### Observed
After a depth of 5 bullet indentations, the text does not render; the depth-6 bullet does, however.

This does not occur in the Linux or Windows versions.

### Reproduced
To reproduce this issue, use markdown to create lists of depth > 5; for example:
```markdown
- this will
	- absolutely
		- display wrong
			- on ios
				- (at-least, when using an iPhone 11 Pro)
					-  This text won't render, but the bullet will!
```
Make|Model|iOS Version|App Version
-|-|-|-
?|iPhone 11 Pro|13.3.1|4.15.1

**Comment by jleandroperez** [comment]
Hello there @QuinRider,

I'm afraid, at the moment, nested lists are not supported in iOS. Definitely in our radar, though.

Thank you for reaching out!
Closing as duplicated of #336
