### ISSUE TITLE
iPad: Cannot minimize keyboard after canceling passcode setup

### ISSUE THREAD

**Issue by kevmarsden** [Automattic/simplenote-ios#68]
Steps to recreate:

On an iPad navigate to Settings > Passcode  then click "Cancel"

The keyboard is frozen and cannot be used or minimized.  In order to resolve, the app must be forced closed and then reopened.  

Simplenote version 4.3.3 
iOS 9.3.2

Originally reported in ticket 2778681-t

**Comment by jleandroperez** [comment]
Closed via #69. Props to @diejmon!!
