### ISSUE TITLE
Checklists: Marker incorrectly prepended

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#680]
Reported in #664
h/t @aerych (Thank you Eric!!)

<br>

> When the cursor precedes the checkbox, hitting enter will create a new checkbox on the same line. Also, when enter is pressed any empty lines preceding the checkbox will be deleted. 
Here's a demo:

<br>

<img width="300" src="https://user-images.githubusercontent.com/1435271/75486051-73f78800-5971-11ea-982c-3ad070c1c1fc.gif">

**Comment by charliescheer** [comment]
Wasn't able to reproduce, however it does still have the issue that is reported in #592 gonna close the issue

Video:
<img width="300x;" src="https://cdn-std.droplr.net/files/acc_593859/6B3rAo" />
