### ISSUE TITLE
RTL letter are reversed in order in note list

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-ios#697]
### Expected
I would expect the letters to remain in the order ABC in the note list as well as in the note directly when using RTL language like Arabic.

### Observed
Letters are reversed from ABC to CBA in the note list in the iOS app but remain in the correct order when viewing the single note.

### Reproduced

> 1. Go to the iOS app and add a new note with RTL language (e.g. Arabic Unicode)
> 2. Letters stay in the correct order when viewed in the single note. 
> 3. Navigate back to the note list, the orders reverse themselves (ABC to CBA).

![Image from iOS](https://user-images.githubusercontent.com/10325627/76527882-d3709000-6467-11ea-89dc-8881ade91623.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/10325627/76527897-da979e00-6467-11ea-9dd2-55516f7d8def.png)

Make|Model|iOS Version|App Version
-|-|-|-
iPhone X|MQAD2B/A|iOS 13.3.1|4.16
iPhone 7| |iOS 13.3.1|4.16
iPad Mini| | |

Reported by a user in 2777608-zen

**Comment by jleandroperez** [comment]
@rezzap just to confirm (for paranoia's sake!!), the problem is in **the editor**, but the Notes List is okay, would that be accurate?

Thank you!!

**Comment by jleandroperez** [comment]
Re-re-read it x3. Is the actual problem in the Notes List? (Isn't RTL expected to actually invert the text?)

**Comment by rezzap** [comment]
The issue is in the note list, it's okay in the editor! 

Note List: CBA
Editor: ABC

**Comment by jleandroperez** [comment]
Thank you @rezzap !!

**Comment by erricgunawan** [comment]
Another possibly similar report on 2784131-zen

Waiting for the device info and some screenshots to determine whether it's just on the editor, note list or both.

**Comment by rezzap** [comment]
Another report in 2784955-zen

![Image](https://user-images.githubusercontent.com/10325627/76683267-d8b21400-65fa-11ea-9813-75c54e7bc472.jpeg)
![Image (1)](https://user-images.githubusercontent.com/10325627/76683269-da7bd780-65fa-11ea-8e64-b7cdb5944f61.jpeg)

They mention this only started after updating to the most recent version of the app.

**Comment by rezzap** [comment]
Another report in 2795486-zen

**Comment by SiobhyB** [comment]
Another report of this in 2795227-zen.
