### ISSUE TITLE
Remove AutoScroll to the top

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#7]
Reported by one of our users via email:

`When I hold my finger on text to magnify it and move the cursor to the right character the page scrolls up and I can't make the change. It scrolls until I remove my finger.`

"I can recreate this (iOS 7.0.4, iPhone 5s). I can make it happen on a long note, when trying to move the cursor in the lower 3rd or so of the text are."

Originally opened by @jleandroperez

**Comment by bummytime** [comment]
Tested on iOS 12.2 — the current scroll behavior worked as expected. Closing for now.
