### ISSUE TITLE
Broken Translations

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#702]
### Details:
I've noticed that the Welcome Note's key is off:

- English Localizable.strings has the `welcomeNote-iOS` key
- All of the remaining Localizable files have the full length english string

And of course, we call `NSLocalizableString(@"welcomeNote-iOS", ...)`. This is causing the Welcome Note not to be properly generated in any language other than English.

This appears to be the exact same issue reported in #564.

**Comment by rachelmcr** [comment]
I saw the same issue with the `collaborators-description` key. As a result, that description text isn't translated in non-English languages:

<img src="https://user-images.githubusercontent.com/8658164/77553332-94512e80-6eac-11ea-9c57-d6880f76d599.png" width="30%">

**Comment by jleandroperez** [comment]
Already fixed in Simplenote 1.10

✅  Welcome Note is getting localized
✅  Add Collaborator screen is also being localized

Thank you Rachel!!
