### ISSUE TITLE
Checklist items difficult to select

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-ios#711]
### Expected
I would expect that by clicking on the checkbox it would be marked as complete.

### Observed
It's not always what happens. Sometimes this can be quite tricky and you need to move the cursor around to be able to get the box to select. 

### Reproduced
> 1. Go to a note with a list included.
> 2. Tap on the screen to get your cursor around the checkbox
> 3. Try to select the checkbox item, it won't work.
> 4. Move the cursor in the middle of the sentence by the checklist item.
> 5. Try to select the checkbox item, this time it works. 

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.
![Screen Recording 2020-03-25 at 01 43 pm](https://user-images.githubusercontent.com/10325627/77542853-bba0ff00-6e9e-11ea-82fa-b6eba76b0afd.gif)

***(Optional)*** If you reproduced the bug on a specific device, please replace DEVICE_MAKE, DEVICE_MODEL, IOS_VERSION, and APP_VERSION below with the details for that device.  If you reproduced the bug on multiple devices, please add a row for each device.

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPhone X|13.3.1|4.16

Reported in 2814594-zen

**Comment by charliescheer** [comment]
I tried to replicate on a few different devices and wasn't able to replicate what is appearing in the video.
SN 4.28, iOS 14.3

Closing, but if problem persists please feel free to open back up
