### ISSUE TITLE
Checklists: Adding checkbox deletes empty line above cursor

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-ios#714]
### Expected

I expect that when I add a checkbox, it will be placed on the same line as my cursor.

### Observed

If I create an empty line and place my cursor on a new line below that, the empty line above my cursor is deleted.

### Reproduced

1. Tap the return key twice, to create an empty line with the cursor on a new line below it.
2. Tap the checklist icon to add a checkbox.

Screencast: https://cloudup.com/ch6UT4Znnyl

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPhone XS|13.3.1|4.17.0.0 TestFlight Beta

**Comment by jleandroperez** [comment]
Thank you Rachel! Fixed via #708 (to be shipped in 4.17).

**Comment by rachelmcr** [comment]
You are too quick for me! :) Thanks!
