### ISSUE TITLE
Markdown Links to Shortcut URL Crashing App

### ISSUE THREAD

**Issue by azollafox** [Automattic/simplenote-ios#725]
### Expected
The user is adding shortcut URLs https://support.apple.com/guide/shortcuts/open-create-and-run-a-shortcut-apda283236d7/ios to their notes via markdown. They would expect these URLs to open in the app as any others

### Observed
When they try to open such a link the only thing that happens is that the app closes. The shortcut does not work as expected

![](https://d.pr/v/UnxjTf+)
(Image link: https://d.pr/v/UnxjTf )

Make|Model|iOS Version|App Version
-|-|-|-
DEVICE_MAKE|DEVICE_MODEL|IOS_VERSION|APP_VERSION
iPhone|8|13.4|4.16

#2822590-zen

**Comment by rachelmcr** [comment]
I found the crash in Sentry: [SIMPLENOTE-IOS-9E4](https://sentry.io/share/issue/c8ace5eb2ec3470da839ee6a84fd1d78/)

The crash is NSInvalidArgumentException: The specified URL has an unsupported scheme. Only HTTP and HTTPS URLs are supported.

**Comment by charliescheer** [comment]
Was able to reproduce this crash.

Steps:
1.  In a note with markdown activated add a link that points to another app using another apps URL scheme, for example: 
```
[shortcut](shortcuts://)
```
2. go to markdown and click on the link
3. the app will crash.
