### ISSUE TITLE
Nü Passcode

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#761]
### Guidelines
- New code should always be Swift
- Autolayout **is always preferred**
- Please drop outdated components when appropriate! 🔥🔥🔥

### Details
- [ ] Encapsulate all of the Pincode support (currently spread in the AppDelegate)
- [ ] Encapsulate our FaceId + TouchID support
- [ ] Unit Test all the things
- [ ] Implement the new Passcode UI
- [ ] Please keep the Attempts Limit logic

### Mockups
<img width="200" src="https://user-images.githubusercontent.com/1195260/97208912-6f9e9b80-179a-11eb-9795-3a4848df350b.png"> <img width="200" src="https://user-images.githubusercontent.com/1195260/97208918-72998c00-179a-11eb-996f-7c1a2bd02b23.png"> <img width="200" src="https://user-images.githubusercontent.com/1195260/97208924-73322280-179a-11eb-9e43-a44951f45c9c.png">

<img width="200" src="https://user-images.githubusercontent.com/1195260/97208927-73cab900-179a-11eb-8199-0974b40fdabe.png"> <img width="200" src="https://user-images.githubusercontent.com/1195260/97208928-74634f80-179a-11eb-957d-bdf6cbb31172.png">

**Comment by mattdc28** [comment]
If an incorrect pin is entered do we want to retain the current behaviour which shows you how many failed attempts you have and shakes the pin field?
![Simulator Screen Shot - iPhone 11 Pro - 2020-08-08 at 08 36 34](https://user-images.githubusercontent.com/68430728/89705135-85968000-d952-11ea-817e-303778d91c98.png)

**Comment by jleandroperez** [comment]
@mattdc28 nicely spotted! Mockups updated / Issue Description updated.

Thank you!

**Comment by eshurakov** [comment]
Note: on iPhone we want to support only Portrait orientation. If the phone is in landscape, force passcode screen to be in a Portrait orientation

**Comment by jleandroperez** [comment]
@eshurakov I think this is 100% done right?

**Comment by eshurakov** [comment]
@jleandroperez indeed, will close it now.
Thank you!
