### ISSUE TITLE
Bug: Note editor doesn't take into account bottom safe area insets when opened for the first time

### ISSUE THREAD

**Issue by eshurakov** [Automattic/simplenote-ios#769]
### Expected
Expected note editor to respect bottom safe area insets and have some space between bottom edge of my device and text or tags view.

### Observed
Opening a note after cold start of the app shows text or tags behind the home indicator. Which means that safe area wasn't taken into account. 
On subsequent opening of any of the notes or after editing an opened one the issue fixes itself.

### Reproduced
> 1. Cold start the app (kill it if it's running and open again)
> 2. Tap on any note
> 3. Depends on how much text the note has, either text or tags is shown behind the home indicator

On a screenshot red is a frame of the editor, green is a frame of the tags view.
![Simulator Screen Shot - iPhone Xs - 2020-06-04 at 23 18 43](https://user-images.githubusercontent.com/54751/83812579-16837d80-a6bc-11ea-9608-739e75d06cad.png)

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|Xs|13.5|4.19

**Comment by eshurakov** [comment]
I took a quick look at the code :-)
The following code in `SPNoteEditorViewController` doesn't work as expected because when `viewWillAppear` is called `view` isn't yet added to its superview, which results in a `safeAreaInsets` values being 0.
```
- (void)viewWillAppear:(BOOL)animated {
    ...
    [self adjustFrameForSafeInsets];
    ...
}
- (void)adjustFrameForSafeInsets
{
    CGRect viewFrame = _noteEditorTextView.frame;
    viewFrame.size.height = self.view.bounds.size.height - self.view.safeAreaInsets.bottom;
    _noteEditorTextView.frame = viewFrame;
}
```

A quick and easy solution would be to call `[self adjustFrameForSafeInsets]` with a delay, either using `[[NSRunLoop currentRunLoop] performBlock:^{}]` or via `GCD`

But I think less magic and better solution would be to convert current editor view to use constraints :-)

**Comment by jleandroperez** [comment]
@eshurakov Done (definitely with autolayout) !! Thank you for opening this issue!
