### ISSUE TITLE
Crash when editing note text

### ISSUE THREAD

**Issue by sarahfg** [Automattic/simplenote-ios#775]
The user is reporting a crash when editing one specific note on their iOS device. This only happens on iOS, with this particular note, when editing the text area around `2017 年` . They can reproduce this by copy and pasting the same content into a new note. I have not been able to reproduce it by copy and pasting the text into my Simplenote account and trying to edit the same text, using my iPad. 

Text:
```
ポートフォリオ
1970年生まれ

プロフィール

略歴
映画学校卒業後、映像プロダクションに勤務。セルアニメーション撮影助手、VFX・SFX撮影助手、モーションコントロールカメラオペレーターを担当。その後フリーとして活動後、現在はフイルム映像のデジタル化、旧方式ビデオテープのデジタル化に従事。2018年よりフイルムアーカイブでの小型映画機材の調査に協力。

研究
「小型映画フィルム調査のための技術と資料の研究」ＮＰＯ法人映画保存協会、平成 21 年度笹川科学研究助成

研究発表
「戦前小型映画の調査研究ー『片岡コレクション』を中心に」（共同発表者 片岡一郎）『第 5 回映
画の復元と保存に関するワークショップ』於・京都府京都文化博物館、2010 年 8 月 29 日

「機材と技術からみたパテ・ベビー～カメラから現像・編集、映写機まで～」おもちゃ映画ミュージ
アム、2016 年 6 月 25 日

展示
「戦前・戦後のアマチュア映画カメラと映写機展」第 57 回神田古本まつり、於・東京古書会館、2016
年 11 月 1～11 月 6 日

論文・記事
「『春のをどり』の撮影方法・撮影技術」『映画学』28 号、早稲田大学映画学研究会、2014 年
『旧安田楠雄邸所蔵 8 ミリフィルム調査報告書』、ＮＰＯ法人映画保存協会 小型映画部、2007 年
『戦前小型映画資料集』ＮＰＯ法人映画保存協会、2009 年
『フィルム調査報告書―02 片岡一郎 9.5mm コレクション』 ＮＰＯ法人映画保存協会、2009 年

ブックレット
おもちゃ映画ミュージアム ブックレット 3 『パテ・バビーの時代』共著 森末典子、おもちゃ映
画ミュージアム、2017 年

映像作品
『点景』16 ミリ映画、2017 年。イメージフォーラム・シネマテーク 「！8 to !! 16 [exclamation-
8 to exclamation-16]」2018 年 1 月 27 日～28 日。

イベント・展示協力
8 ミリフィルム上映イベント「ホームムービーの日」根津会場ほか、2007 年-2017 年。
川崎市市民ミュージアム「映像の創出 – イメージと装置」
9.5mmパテベビー上映会、2007年１２月22〜23日
東京都写真美術館「エクスパンデット・シネマ再考」関連イベント 8 ミリフィルム撮影・8 ミリ自家
現像ワークショップ、2017 年 9 月 23 日～9 月 24

韓国映像資料院

```

Information:

The user has included a video of the crash in the ticket at #2993732-zen

Make|Model|iOS Version|App Version
-|-|-|-
DEVICE_MAKE|DEVICE_MODEL|IOS_VERSION|APP_VERSION
iPhone| SE| 13.4.1| 4.18
iPad| 7th gen| 13.4.1|4.19

**Comment by jleandroperez** [comment]
Tested on my end on these devices:

- iPhone SE 1nd Gen / iOS 13.5 / Simplenote 4.18
- iPhone SE 2nd Gen / iOS 13.5 / Simplenote 4.18
- iPhone X / iOS 13.5 / Simplenote 4.19

I'm afraid I cannot repro, so far. Will dig into the crashlog reports, perhaps we can find a lead there.

Thank you Sarah!

**Comment by jleandroperez** [comment]
Closing as cannot repro. Simplenote 4.25 / iOS 14. 

By all means, please reopen if we do crack down a way to trigger this! Thank you!!
