### ISSUE TITLE
Translations are still broken / missing after bugfix release

### ISSUE THREAD

**Issue by fstraetz** [Automattic/simplenote-ios#781]
### Expected
The Simplenote app should display translations for all menu items and other controls.

### Observed
While #564 got closed and an updated version of the app was apparently uploaded to the App Store, the translations for everything related to „trash“ are still / again broken in version 4.19 (the latest version in the german App Store). This concerns the „Trash-noun“ as well as the „Trash-verb“. Additionally, the title of the welcome note is also not translated, and it‘s content (if there should be any content) is completely empty.

### Reproduced
1. Download Simplenote 4.19 in the german App Store.
2. Open Simplenote.
3. Register a new account.
4. Open various dialogs / menus:
4.1. The (broken) welcome note is visible right on the start screen.
4.2. Open the burger menu. Notice the broken „trash-noun“ menu item.
4.2 Swipe left on a note. Notice the broken „trash-verb“ item.
4.3 Open a note and open the note information screen. Notice the broken „trash-verb“.

### Screenshots
![6D0AC735-C1CE-465F-BF6A-FC341B506947](https://user-images.githubusercontent.com/13198846/85225481-f220e400-b3d1-11ea-9861-87d285d0f324.png)
![BB8B759D-7CEB-4FBD-BB36-0EDB90078B60](https://user-images.githubusercontent.com/13198846/85225483-f4833e00-b3d1-11ea-9a95-17e7631b3ab0.png)
![A628FC6B-EDA5-4CA0-9E5E-072913A09FC4](https://user-images.githubusercontent.com/13198846/85225485-f51bd480-b3d1-11ea-8ce7-d9aacd5c0900.png)

### Device
Make|Model|iOS Version|App Version
-|-|-|-
Apple iPhone|XR|13.5.1|4.19

**Comment by jleandroperez** [comment]
Hello there @fstraetz,

I'm afraid I cannot repro on my end (screenshots at the bottom). Would it be possible to confirm if this is still an issue on your end? Is it possible this was actually in 4.18?

**Localizations in 4.19:** [Trash-noun](https://github.com/Automattic/simplenote-ios/blob/4.19/Simplenote/de.lproj/Localizable.strings#L518) and [Trash-verb](https://github.com/Automattic/simplenote-ios/blob/4.19/Simplenote/de.lproj/Localizable.strings#L518)

Translations are handled via GlotPress (you [can suggest new strings here](https://translate.wordpress.com/projects/simplenote/ios/)). Those strings are pulled automatically when a new release is done.

**Thank you** for helping us improve Simplenote!

<img width="300" src="https://user-images.githubusercontent.com/1195260/87177409-f98d2c00-c2b1-11ea-80ee-49b6a7e0aa9b.png"> <img width="300" src="https://user-images.githubusercontent.com/1195260/87177422-fe51e000-c2b1-11ea-977c-9b23182f0173.png">

**Comment by fstraetz** [comment]
Hi, I’m pretty sure I encountered this in version 4.19 (because I actually double checked the version, as the bug was supposed to be fixed). Anyway, I just discovered that everything’s fine in the newest version (i. e. 4.20.1 or even 4.20, I’m not sure), so I‘m going to close this report. Thanks for your assistance!

**Comment by jleandroperez** [comment]
Thanks for confirming @fstraetz!
