### ISSUE TITLE
Change controls or translations to allow for readable captions

### ISSUE THREAD

**Issue by fstraetz** [Automattic/simplenote-ios#782]
### What
The Simplenote app should either resize controls based on the width of the translated caption (instead of the original caption?), at least if there is enough space to do so, or it should use shorter translations which fit the existing controls.

### Why
Some controls are virtually impossible to read because the translated caption is too long / the controls don‘t get resized to fit the translated caption, so the user has to find out their function by trial and error or by guessing what the readable parts of the caption might hint at. While this doesn‘t break any functionality, it makes the app less pleasing to use. 

### How

![4806CB02-AC1D-45C9-8DAA-45810349CF1F](https://user-images.githubusercontent.com/13198846/85225964-04e8e800-b3d5-11ea-979e-f5cb27447ed8.jpeg)

Since there is a lot of whitespace available, the best option would be to resize the controls / their captions. This screenshot shows the german translation of the app, I‘m not sure whether other translations have this problem in other parts of the app.

**Comment by jleandroperez** [comment]
Closing in favor of #763

We'll be refreshing the Note Options / Info UI(s) later this year, (and!) we'll accommodate for different string lengths.

Thanks for reaching out @fstraetz !!
