### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Yusadolat** [Automattic/simplenote-ios#789]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected
***(Required)*** Add a concise description of what you expected.

It is expected to login after inputting the credentials 
### Observed
***(Required)*** Add a concise description of what you observed.

![image](https://user-images.githubusercontent.com/10975011/85916328-b9589300-b847-11ea-9db4-934b73f5dd08.png)
### Reproduced
***(Required)*** If you cannot reproduce this bug consistently, please elaborate.  List the steps to reproduce the behavior.  For example:
> 1. Go to...
> 2. Tap on...
> 3. See error...
Type credentials and click sign in

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

***(Optional)*** If you reproduced the bug on a specific device, please replace DEVICE_MAKE, DEVICE_MODEL, IOS_VERSION, and APP_VERSION below with the details for that device.  If you reproduced the bug on multiple devices, please add a row for each device.

Make|Model|iOS Version|App Version
-|-|-|-
DEVICE_MAKE|DEVICE_MODEL|IOS_VERSION|APP_VERSION

**Comment by jleandroperez** [comment]
Hello there @Yusadolat ,

Would it be possible to try connecting form a different network, and checking if the problem persists?
We'd love to follow up via email, we really use GutHub for code related issues: **support [AT] simplenote.com**

Closing this one for now,
Thanks in advance!!

**Comment by Yusadolat** [comment]
The issue still persists. I was able to login with the same details on the browser and different connection.![image](https://user-images.githubusercontent.com/10975011/86543867-5edfc680-bf1a-11ea-83ff-917b8fe028ea.png)
