### ISSUE TITLE
Bug: Web app won't let me log in with short password -- but also doesn't generate a reset email

### ISSUE THREAD

**Issue by skyfein** [Automattic/simplenote-ios#797]
I've been using Simplenote since 2009. Three days ago, when I tried to log in, I got an error message: I would need to reset my ancient 6-character password. The web app showed me a button that would generate a password-reset email. I've clicked that button a dozen times in the past 3 days, but I've never gotten a password-reset email. I've also emailed customer service twice -- no reply. 

### Expected
An email with password-reset link. A response from customer service.

### Observed
No email. No response from customer service.

### Reproduced
I've repeated the procedure a couple times a day for the past 3 days. Results are the same every time.

Thanks for your attention, and for any suggestions you can offer!

**Comment by jleandroperez** [comment]
I'm sorry you're having issues @skyfein !! 

We'd need to ask you the `username / email address` that's causing you trouble.

Mind mailing at support@simplenote.com (and please do CC myself: `jorge.perez` (at `automattic dot com`).

Thanks in advance!

**Comment by jleandroperez** [comment]
Closing this issue since it's been addressed over Zendesk.

Thank you for reaching out!
