### ISSUE TITLE
iPad: Share and Collaborate Buttons Stopped Working (iOS 9.3.4)

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-ios#80]
A user reported and I reproduced on my iPad:

1. Open a note, tap info button.
2. Tap on `Send`. Nothing happens.
3. Tap on `Collaborate`. Nothing happens.

The other buttons do appear to work fine, like history and trash. Also, the blue background behind 'markdown' is a lot lighter on the iPad for some reason.

**Comment by roundhill** [comment]
Screenie of the light blue background:
<img width="187" alt="screen shot 2016-08-26 at 9 21 04 am" src="https://cloud.githubusercontent.com/assets/789137/18012485/7dfa2730-6b6e-11e6-87bb-5222d419f0fa.png">

**Comment by eduardozulian** [comment]
Reported also on #2794030-t
