### ISSUE TITLE
Add ‘Pure Black’ option for Dark Mode

### ISSUE THREAD

**Issue by mahdqureshi** [Automattic/simplenote-ios#809]
### What
An option to use pure black with the dark mode interface.

### Why
Pure black can help reduce battery usage on OLED devices. It’s also _subjectively_ more comfortable to use at night.

**Comment by jleandroperez** [comment]
Hello there @mahdqureshi,

**Actually** we just did that in #788. Scheduled out in 4.21, should hit the AppStore in about two weeks.

Thank you for reaching out!
