### ISSUE TITLE
Conflicting detection/validation of email address

### ISSUE THREAD

**Issue by dmsnell** [Automattic/simplenote-ios#832]
[`NSPredicate+Email`](https://github.com/Automattic/simplenote-ios/blob/develop/Simplenote/NSPredicate%2BEmail.swift#L11) says an email as long as it has an `@` and ends in a TLD of at least two characters.

`".+@([A-Za-z0-9-]+\\.)+[A-Za-z]{2}[A-Za-z]*"`

[`NSString+Metadata`](https://github.com/Automattic/simplenote-ios/blob/develop/Simplenote/Classes/NSString%2BMetadata.m#L21) adds tighter constraints and only allows TLDs with 2-4 characters, incorrectly rejecting many modern gTLDs such as `.coffee`, `.email`, and `.education`.

`"[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}"`

It would be ideal if these agreed or shared their validation. Currently `containsEmailAddress` is rejecting collaborators with valid email TLDs.

#3153839-zen

**Comment by jleandroperez** [comment]
Thank you for filing this one!!
