### ISSUE TITLE
Tags: Can't use non-Latin keyboard when editing tag names

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-ios#841]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected

I expect to be able to use any of my device keyboards in the app.

### Observed

I can use any of my device keyboards in other parts of the app, like the note editor or search field, but I can't use all of them when I am editing (renaming) tags.

In that case, I only have access to Latin keyboards such as English, German, or Spanish. I can't access my emoji keyboard, and I can't access other language keyboards such as Arabic, Farsi, or Greek even if the App UI language is set to one of those languages.

### Reproduced

1. In the Settings app, go to General > Keyboard > Keyboards > Add New Keyboard and add a non-Latin keyboard to your device (e.g. Arabic).
2. Open the Simplenote app.
3. Open the note editor and confirm you can switch between keyboards using the globe icon.
4. Open the app drawer and select "Edit" next to Tags.
5. Tap into a tag name field to bring up the keyboard.
6. Try switching between keyboards and notice that non-Latin keyboards are not available, even if you had them enabled elsewhere in the app.

All Keyboards in Note Editor|Limited Keyboard in Tags Editor
-|-
![IMG_4004](https://user-images.githubusercontent.com/8658164/89914544-1092a700-dbed-11ea-884c-de72d8a92319.PNG)|![IMG_4005](https://user-images.githubusercontent.com/8658164/89914533-0cff2000-dbed-11ea-8b3d-de45492183f4.PNG)

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPhone XS|13.5.1|4.23.0.0 beta

**Comment by jleandroperez** [comment]
Closed via #871
