### ISSUE TITLE
Selecting Text in iOS app 4.22 very finicky

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-ios#842]
A user has reported having difficulty selecting text in the latest release of the iOS app. I've replicated the issue with text often jumping multiple lines with selection and being difficult to target only a few lines of text. 

### Expected

I would expect that when I try to select text within a note it goes slowly enough that I can control which text is selected.

### Observed

This jumps around a lot making it very challenging to select only a portion of text. 

### Reproduced
> 1. Go to any note in Simplenote 4.22
> 2. Long push on the screen to get the cursor in select mode. 
> 3. Move the cursor down a few lines to try and select it. Notice the issue. 

![Screen Recording 2020-08-12 at 04 26 pm](https://user-images.githubusercontent.com/10325627/90034749-ea3a3d80-dcb8-11ea-8887-185eb84f0ad3.gif)

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPhone X|13.6|4.22
Apple|iPad Air 2|13.6|4.22

**Comment by msilbers** [comment]
reported in 3217374-zen

iOS 13.3.1
Simplenote ver.4.22

**Comment by msilbers** [comment]
reported in 3220146-zen

asked for iOS and Simplenote versions

**Comment by msilbers** [comment]
reported in 3223123-zen

Simplenote 4.22
asked for iOS version

**Comment by msilbers** [comment]
reported in 3228480-zen

iPhone
Simplenote 4.22

**Comment by rezzap** [comment]
Reported in 3232729-zen

iPhone 8S

**Comment by jleandroperez** [comment]
Closed via #847. Shipping soon in 4.22.1 (hotfix).

Thanks everyone!!
