### ISSUE TITLE
Highlighting Text Quickly Scrolls you to the bottom in 4.22

### ISSUE THREAD

**Issue by sarahfg** [Automattic/simplenote-ios#844]
### Expected
When highlighting text to copy, paste or otherwise modify in the update to iOS I should be able to scroll smoothly to get the text I need, as I could in other releases

### Observed
In Version 4.22 when I start to highlight text the app immediately jumps to the bottom of my text. 

### Reproduced
1. Make sure your app is updated to 4.22
2. Open a note with a bunch of text, that goes beyond 1 page on your screen
3. Long press to start highlighting and start to slowly drag your finger down the screen

Make|Model|iOS Version|App Version
-|-|-|-
DEVICE_MAKE|DEVICE_MODEL|IOS_VERSION|APP_VERSION
iPad|7th gen|13.6|4.22
iPad|5th gen|13.6|4.22
iPhone| 8|13.6|4.22 

User reported in #3214992-zen. Ticket has attached videos of the issue

**Comment by jleandroperez** [comment]
Closing in favor of #842 (since there are multiple reports in there as well!).

Thank you Sarah, fixing this one ASAP!!
