### ISSUE TITLE
iPad Send and Collaborate do not work after recent update.

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/simplenote-ios#86]
iOS 9.3.5

When in a published note, clicking on the "i" button, and then attempting to click on Send or Collaborate does not work. The buttons do not respond. The issue does not seem to exist on iPhone, only iPad.

There have been several user tickets on the issue.

**Comment by frosty** [comment]
Thanks for the report, @chrisfromthelc – we've already fixed this one (#80, fixed in #81). Our update is with Apple now, awaiting review. 👍
