### ISSUE TITLE
User cannot edit when returning to the app with passcode enabled on iPad

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/simplenote-ios#88]
This could be related to #87. When returning to an individual note with passcode enabled, I'm unable to edit the note on my iPad Air 2. 

Steps to reproduce:
1. Enable a passcode and Touch ID
2. Open Simplenote.
3. Click on a note to open it.
4. Click on the home button to exit the app.
5. Click back on the icon to open the app. You won't be prompted for a passcode (issue in #87), but when you tap on the note, you're unable to type into it (new issue).

I have to restart the app to get it to work again.

Video: https://cloudup.com/cctTCjzrN1m (at the end, I'm tapping on the screen trying to edit the note)

Reported in 2826252-t.

**Comment by debex** [comment]
This same behavior has been reported by another user, also using an iPad Air 2. 2863769-t.

**Comment by kriskarkoski** [comment]
Another in 2851682-t

**Comment by GertjanLind** [comment]
I still have this problem on my Ipad mini

**Comment by rachelsquirrel** [comment]
#3185082-t

**Comment by GertjanLind** [comment]
Rachelsquirrel, what am I to do with this number you provided?

**Comment by rachelsquirrel** [comment]
Ah sorry, GertjanLind. I should have been more clear. It's just a reference to another report of this same issue. It's for internal tracking.

**Comment by GertjanLind** [comment]
Ah Okay. 

It's still not resolved is it?

Veel groeten,
Gert-Jan

**Comment by jleandroperez** [comment]
Closing as cannot repro. Simplenote Mark 4.12.

If needed, please, feel free to reopen. **Thanks everyone!!!**
