### ISSUE TITLE
Navigating/Scrolling issue on iOS14

### ISSUE THREAD

**Issue by jgwill** [Automattic/simplenote-ios#888]
### Expected
***(Required)*** 

Be able to scroll and select where I want to position myself.

### Observed
***(Required)*** 

When the cursor is somewhere and scrolling few pages then select where to position next, it does not, instead it position somewhere in between (which is undesired)

### Reproduced
***(Required)*** 

> 1.make a few pages text on a note on iOS 14
> 2. Navigate to first page
> 3.scroll down 2 pages and position somewhere in the page
> 4. It should not position there but somewhere in between

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

***(Optional)*** If you reproduced the bug on a specific device, please replace DEVICE_MAKE, DEVICE_MODEL, IOS_VERSION, and APP_VERSION below with the details for that device.  If you reproduced the bug on multiple devices, please add a row for each device.

Make|Model|iOS Version|App Version
-|-|-|-
IPhone |8 plus|IOS 14| 4.23

**Comment by reginabally** [comment]
Also reported in 3334157-zen on iPhone 8, iOS 14, App version 4.23.

**Comment by msilbers** [comment]
reported in 3337179-zen on iOS 14

**Comment by reginabally** [comment]
Device information for 3337179-zen: iPhone 7, iOS 14, App version 4.23.

Can also replicate this on iPhone SE, iOS 14, App version 4.23.

**Comment by jleandroperez** [comment]
3332890-zen

**Comment by jgwill** [comment]
I am also experimenting text-navigation issue in other app on iOS 14, they are just not that bugging the whole navigation process so we might have to report or collaborate with Apple on it because its source might be iOS itself.

**Comment by jleandroperez** [comment]
I'll do my best to take a look at this one next week. Thanks everyone for the heads up!

**Comment by azollafox** [comment]
I think this is likely the same issue, but wanted to share in case I'm off about that

>I've noticed that since iOS 14 and still with 14.0.1 and Simplenote 4.24, I have problems selecting words and sentences. Usually you click a little longer on sth and iOS offers that little menu for selecting, copying and pasting text. A lot of times it doesn't come at all, despite clicking several times at different words, varying time I keep clicked. Then I gotta close the note and reopen it. I never had this before iOS 14. 

Reported in iOS 14.0.1 , Simplenote 4.24 #3353257-zen

**Comment by reginabally** [comment]
Reported in iOS 14.0.1, Simplenote 4.24, #3357888-zen.

**Comment by malinajirka** [comment]
Reported in iOS 14.0.1, Simplenote 4.24, #3374715-zen.

**Comment by azollafox** [comment]
Reported again on iPad and iOS #3382212-zen

```
Its difficult to, as in no or slow resonse, for the “select all/copy/ paste” to appear when you put down the cursor, You have to try several times.

And when you scoll down the page to find the place to paste text -if you are not fast enough in putting the cursor down, holding it there, it autoscrolls back to the last place the cursor was set on. Its very irritating, and time consuming :-) 
```

**Comment by jleandroperez** [comment]
Closed via #916. 

Thank you for reporting this @jgwill, and apologies it took a while to get this patched up!!

**Comment by jleandroperez** [comment]
By the way: Shipping next week in 4.26!

**Comment by jgwill** [comment]
> Closed via #916. 
> 
> 
> 
> Thank you for reporting this @jgwill, and apologies it took a while to get this patched up!!

Your welcome !!
But I am still struggling with it, I'm wondering why?  It might be accessibility tool I'm using or is there anyone who still has issue with navigating ?
Regards

**Comment by jleandroperez** [comment]
Apologies about the late reply @jgwill, lost the notification somehow!!
Would it be possible to get a demo video? (that'd help a loot narrowing things down).

Thanks in advance!!

P.s.: For the record we're further improving Navigation / Scrolling in Simplenote 4.27 (out in a few weeks). Ref #921

**Comment by jgwill** [comment]
I've recorded a video of the issue in action
Regards
spectateurs:

(Edited for privacy reasons)

**Comment by jleandroperez** [comment]
@jgwill  Thanks a lot for taking the time!! 

Reopening this issue to further investigate!

**Comment by jgwill** [comment]
I deeply appreciate you care about it :)

**Comment by jgwill** [comment]
Just let you know that with latest version 4.26 it is now working fine :)  
thanks 
Regards 

close #888

**Comment by jleandroperez** [comment]
Awesome! I'm glad to hear all is good!

@jgwill Thank you for helping us improve Simplenote!!!
