### ISSUE TITLE
Swipe causes notes to disappear

### ISSUE THREAD

**Issue by KokkieH** [Automattic/simplenote-ios#89]
Reported via [Twitter](https://twitter.com/blockloop/status/777355558965776384).

A user reported that if they are viewing a note, swipe to the notes list, then cancel, i.e. swipe back before the change completes, the note content disappears. User is on iPhone 6S Plus, iOS 10, app version 4.4.1

Video clip of what happens at the Twitter link.

We've not been able to reproduce the issue yet.

**Comment by nagpai** [comment]
Similar issue reported by user  on 

#729062-zd

**Comment by roundhill** [comment]
1 year later, I'll have a look at this 🤦🏻‍♂️
