### ISSUE TITLE
Clicking links on the notes does not launch a browser on iOS

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-ios#895]
### Expected
I would expect clicking the links on the notes will launch a browser to visit the link.

### Observed
Clicking links on the notes changes the styling to plain text and does not launch a browser.

### Reproduced

1. Open a note with links created on the Simplenote app
2. Tap on a link
3. The styling of the link changes to plain text

**Screen recording**

![Screen Capture on 2020-09-25 at 10-45-18](https://user-images.githubusercontent.com/40906847/94220750-44ffbf80-ff1c-11ea-80c9-b4a04efe3701.gif)

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|SE (2nd edition)|iOS 14|4.24

Reported in 3341835-zen but I'm able to reproduce this with the same device, iOS and app version.

**Comment by jleandroperez** [comment]
Hi there @reginabally !!

I'm afraid that's expected behavior. Links are actually handled by means of a **Long Press** (which will open the target URL).

A single tap is always expected to switch to Edition Mode.

Thank you!!
