### ISSUE TITLE
Support accent characters in search

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#9]
Originaly opened by @fredrocious

**Comment by avernet** [comment]
I am seeing that this issue is still open, but this is working for me on the iOS app (at least with not-so-fancy latin1 accents, e.g. "é"). So maybe this one can be closed.

**Comment by jleandroperez** [comment]
Tested over here, and turns out Search wasn't diacritic (accent characters work in search, but you need to actually type them in the search field).

To be addressed in the next release, thanks everyone!
