### ISSUE TITLE
Switching to another app and back leads to table of contents

### ISSUE THREAD

**Issue by madhattermattic** [Automattic/simplenote-ios#90]
According to ticket #2850777:

`My app started playing up recently. When I switch to it from another app it doesn't take me back to where I left off in a note. Instead it takes me to the table of contents again. 
As you can imagine when I flicking between another app and Simplenote repeatedly like when I'm taking notes this is annoying. Especially if I have to scroll to the bottom of a long note each time. Incidentally, I would love a feature to scroll to the bottom of a long note from the top with the touch of a button.

I'll leave my review as five stars and I hope you get this issue fixed soon. 

I appreciate your work and have been with you from the beginning.`

**Comment by bummytime** [comment]
Closing in favor of #5
