### ISSUE TITLE
New Note from 3D Press menu

### ISSUE THREAD

**Issue by lukewlms** [Automattic/simplenote-ios#901]
### What
When 3D pressing (force pressing) the app icon, show "new note" as a menu option

### Why
Currently the "new note" experience is clunky.
1. Open app
2. Tap "Notes" to go backward
3. Tap small "Add note" icon

Since this is the most common thing I'm doing in Simplenote, I'd appreciate removing a step and the need to search for these UI elements.  Currently 3D pressing on the app icon does not show any app-specific options (only delete/share/edit home screen).

### How
This would be a very simple option added to the 3D Press menu: "New Note".  I expect that's the only 3d press option I'd use but there may be other useful ones like Most Recently Used tags, or Search.  You know your users better than I do!

Thanks for the consideration.

**Comment by jleandroperez** [comment]
Thank you for reaching out @lukewlms, we'll be working on this feature soon-ish. No ETA at the moment, but definitely in our list!

**Comment by jleandroperez** [comment]
Closing in favor of #950, with extra details. We'll be adding quick actions for New Note / Share / Recent.

Thank you for reaching out Luke!
