### ISSUE TITLE
Simplenote causes wifi to fail on iPhone 7

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/simplenote-ios#91]
Submitted via support email:

> I have a new iPhone 7 128gb When trying to restore it from my iPhone 6S backup, simple note would cause it to lose all internet access. this happened on three phones until Apple was able to figure out what was happening. I finally deleted simple note and was able to place my iPhone 7 in service.
> 
> I have not tried to install it since I am finally up and working. It was my observation that simple note was causing the problem. Two times when I tried to submit my sign it I observed my wi-fi quit. I returned the first two iPhones for replacement before Apple came up with a way to restore the third one.

**Comment by bummytime** [comment]
Issue appears to be stale - closing for now.
