### ISSUE TITLE
Unable to select multiple notes

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-ios#913]
### Expected
I would expect by long pressing on the note list, I'm able to trigger the multiple selection feature to select multiple notes in the app.

### Observed
Long pressing on the app didn't trigger the multiple selection feature. Once I released my finger, the selected note opened in editing mode.

### Reproduced
1. Launch the Simplenote iOS app
2. Tap on a note and hold it for at least 2 seconds
3. The app does nothing so far
4. Release the finger and see the app opens up the note in editing mode

### Additional details

This issue doesn't happen on Simplenote Android version 2.12-rc-1 (120). Tested on Oppo Reno 4, Android 10.

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPhone SE|14.0.1|4.25

**Comment by jleandroperez** [comment]
Closing in favor of #1043. We're bringing support for multiple row selection!

Thank you @reginabally !!
