### ISSUE TITLE
[Notes List] 'Sort by' section is shown at the bottom of the notes lists and it's not working

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-ios#945]
### Expected
'Sort by' section should either work, if shown, or should not be shown at all

### Observed
It's possible to see the 'Sort by' section after executing steps below

### Reproduced
> 1. Make sure there's at least one note
> 2. Show all notes
> 3. Set focus to the searchbar - keyboard will appear (which most probably hides the 'Sort' section)
> 4. While not entering any text to seach for, tap any available note
> 5. Once note is open, go back
> 6. There will be 'Sort' by' section shown at the bottom (see picture), it will not work, and the selected sorting will not be related anyhow to the sorting selected in the app Settings

![photo_2020-10-24_00-29-04](https://user-images.githubusercontent.com/73365754/97055669-f6335d00-158f-11eb-964a-72b18d442cb9.jpg)

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|XR|14.0.1|4.26

**Comment by jleandroperez** [comment]
The SortBar actually alters the way in which search results are ordered. Since there are no keywords, what's on the list is the "unfiltered list of notes".

Solution for this issue would probably involve hiding the SortBar unless there's an actual keyword (which may be an overkill).

Thanks for the report @pachlava!

**Comment by pachlava** [comment]
Thank you for clarification @jleandroperez - it was not intuitive for me. It works when keyword is present.

**Comment by pachlava** [comment]
Sortbar is no longer available, closing
