### ISSUE TITLE
Text inside Pin note button Simplenote iOS 4.26

### ISSUE THREAD

**Issue by marianearchimbaud** [Automattic/simplenote-ios#947]
Device/Version: iPadOS 14.1

### What
***(Required)*** What is the feature you are requesting? Add a concise description of the feature being requested.

Text inside Pin note button is not displayed completely in Spanish. Maybe a shorter word can be used instead of the current phrase. Or be replaced by icons.
Image 1: Button shows "Ancl...perior" which has no meaning and there is no way to see the complete text/description.
Image 2: Button shows "Pin to top"

### Why
***(Required)*** Why are you requesting this feature?  Add a concise description of the problem this feature solves.

There was no way to guess what was the button for, because the text inside it was not visible. This is related on how iOS makes the app's translation. (According to the Help Center : _You can change the language on iOS or Android by changing it from your device settings._ )

### How
***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate how the feature could be done.

* Choose another word or phrases that fit into the button.
* Choose an icon to replace text inside button.

![IMG_0854](https://user-images.githubusercontent.com/72237737/97127781-8bf1f800-1708-11eb-9728-b84193aa1801.PNG)
![IMG_0853](https://user-images.githubusercontent.com/72237737/97127784-8d232500-1708-11eb-9d0a-0d8069db67ef.PNG)

**Comment by jleandroperez** [comment]
Hi there @marianearchimbaud,

Closing this one since it's been addressed via #763. Shipping in Simplenote version 4.27 soon!

Thank you for reaching out!
