### ISSUE TITLE
Search Minimap

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#953]
### Details:
- [ ] Render a touchable minimap on the right hand side of the editor
- [ ] Quickly navigate to search hits when pressing dent marks on the right hand side
- [ ] Refresh the Minimap whenever remote updates come thru (ensure the map integrity!)

### Mockups:
<img width="300" src="https://user-images.githubusercontent.com/1195260/97210498-68788d00-179c-11eb-95a6-061e17a0696d.png">

**Comment by belcherj** [comment]
Let's double-check with @SylvesterWilmott but I do not think the minimap needs to have touchpoints. They would be too small on mobile.

**Comment by jleandroperez** [comment]
What I had in mind for this one is a behavior similar to the way the `Contacts.app's` Index works. 

It's a bit hard to "tap precisely" somewhere, but lets you quickly traverse your address book. But yup, definitely, let's check with Sly!

**Comment by SylvesterWilmott** [comment]
Being able to tap and drag so the scroll position "clicks" to the next mark on the minimap would be nice to have but not essential.
