### ISSUE TITLE
Editor: Tapping the editor while it is scrolling brings the keyboard up

### ISSUE THREAD

**Issue by eshurakov** [Automattic/simplenote-ios#972]
Tapping on the editor while it is scrolling brings the keyboard up.
Standard iOS behaviour is that when scroll is in deceleration mode, the first touch would stop scrolling and not interact with the content.

### Expected
When editor is scrolling next tap would stop scrolling without bringing the keyboard up.

### Observed
It brings keyboard up.

### Reproduced
1. Open long note
2. Swipe up to initiate scrolling
3. Tap on the editor while it is still scrolling

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iOS|14.1|4.27

Reported in: 3459614-zen

**Comment by rezzap** [comment]
Another report in 3454050-zen for iPhone in 4.26.
