### ISSUE TITLE
Unable to select the existing tag from the tag suggestions while typing tag name

### ISSUE THREAD

**Issue by tarunvijwani** [Automattic/simplenote-ios#974]
### Expected
Should be able to select the existing tag from the tag suggestions while typing tag name

### Observed
Unable to select the existing tag from the tag suggestions while typing tag name in iOS 4.26 version.

### Reproduced
For example, if we have an existing tag "demo" and if we type "dem" and select "demo" from the tag suggestion. It will add "dem"  as a tag instead of "demo"

Make|Model|iOS Version|App Version
-|-|-|-
Apple |iPad mini 5 |14.0.1|4.26

**Comment by eshurakov** [comment]
Thank you for reporting it 👍 

It will be fixed in version 4.27 https://github.com/Automattic/simplenote-ios/pull/964
