### ISSUE TITLE
Login is not required on iOS App while password has been changed on web.

### ISSUE THREAD

**Issue by Chanryma** [Automattic/simplenote-ios#98]
#### Steps to reproduce:
1. Login iOS App.
2. Login [website](https://app.simplenote.com/signin) and change password.
3. Kill iOS App and relaunch it.

You will see that the note list screen is displayed, and no login is required.

**Comment by jleandroperez** [comment]
This is by design. Changing a password is not expected to deauthenticate open sessions.

Thanks for helping us out!
