### ISSUE TITLE
Too easy to activate typing mode when scrolling a note

### ISSUE THREAD

**Issue by ghost** [Automattic/simplenote-ios#988]
### What
Reduce the sensitivity for the activation of the edit mode, currently even a short-ish press will activate it.

### Why
As when scrolling up and down it activates the edit mode, which causes an extra press to go back to view mode. This happens multiple times when viewing a note.

**Comment by jleandroperez** [comment]
Hi there @kevgilmore !!

We've super recently addressed this via #976. It'll be released in Simplenote 4.28, scheduled for release later this month.

Thanks for reaching out!
